
export const RAW_SPS: any[] = [
  [1, "O jaký druh spojení se jedná, pokud jsou dvě součásti spolu spojené pomocí závrtného šroubu?", ["Spojení se silovým stykem", "Spojení s tvarovým stykem", "Spojení s materiálovým stykem", "Spojení se šroubovým stykem"], 0],
  [2, "O jaký druh spojení se jedná, pokud jsou dvě součásti spolu spojené pomocí lícovaného šroubu?", ["Spojení se silovým stykem", "Spojení s tvarovým stykem", "Spojení s materiálovým stykem", "Spojení se šroubovým stykem"], 1],
  [3, "Jaký závit mají nejběžněji šrouby (běžně k zakoupení v hobbymarketu)?", ["Jednochodý pravý", "Jednochodý levý", "Dvouchodý pravý", "Dvouchodý levý"], 0],
  [4, "Jaké označení má nejmenší průměr závitu šroubu?", ["d", "d1", "d2", "d3"], 3],
  [5, "Jaké označení má rozteč (stoupání) závitu?", ["D", "P", "S", "R"], 1],
  [6, "Na šroubu je vyroben čtyřchodý závit. Jaký je vztah mezi jeho stoupáním a roztečí?", ["Stoupání je dvakrát větší než rozteč", "Stoupání je čtyřikrát větší než rozteč", "Rozteč je dvakrát větší než stoupání", "Rozteč je čtyřikrát větší než stoupání"], 1],
  [7, "Jaký druh závitu je závit s označením Tr48x8?", ["Metrický závit", "Trubkový závit", "Lichoběžníkový rovnoramenný závit", "Lichoběžníkový nerovnoramenný závit"], 2],
  [8, "V možnostech jsou uvedeny účely použití podložek ve šroubových spojích. Která možnost mezi ostatní nepatří?", ["Vytvoření tvarového styku mezi šroubem (maticí) a spojovanou součástí", "Pojištění šroubového spoje proti povolení", "Zamezení odírání součástí při častém povolování a utahování", "Rozdělení tlaku mezi hlavou šroubu (maticí) a spojovaném materiálu"], 0],
  [9, "Pokud je realizováno pojištění šroubového spoje pomocí korunové matice, pak je nutné zároveň použít i další součást. Kterou?", ["Polyamidový kroužek", "Závlačku", "Podložku s jazýčkem", "Stavěcí šroub"], 1],
  [10, "Pokud první číslo pevnostní třídy šroubu vynásobíme krát 100, pak vypočítáme u materiálu šroubu jeho mez:", ["pevnosti.", "kluzu.", "úměrnosti.", "elasticity."], 0],
  [11, "Závit M20x2-6H. O jaký závit se jedná?", ["Levý vnitřní metrický závit", "Pravý vnitřní metrický závit", "Levý vnější metrický závit", "Pravý vnější metrický závit"], 1],
  [12, "Závit M30x3(1,5) LH-6g. O jaký závit se jedná?", ["Trojchodý levý vnější metrický závit", "Dvouchodý levý vnější metrický závit", "Dvouchodý pravý vnitřní metrický závit", "Trojchodý levý vnitřní metrický závit"], 1],
  [13, "Co musí být splněno, aby byl závit samosvorný?", ["Třecí úhel musí být větší než úhel stoupání", "Úhel stoupání musí být větší než třecí úhel", "Úhel stoupání musí být větší než úhel profilu závitu", "Třecí úhel musí být větší než úhel profilu závitu"], 0],
  [14, "Na jaké druhy namáhání se pevnostně kontroluje závit šroubu?", ["Pouze na tah", "Pouze na střih", "Na otlačení a střih", "Na tah a tlak"], 2],
  [15, "Na jaké druhy namáhání se pevnostně kontroluje dřík lícovaného šroubu?", ["Pouze na tah", "Pouze na střih", "Na otlačení a střih", "Na tah a tlak"], 2],
  [16, "Jaký šroub vidíte na obrázku?", ["Lícovaný", "Stavěcí", "Závrtný", "Vratový"], 1],
  [17, "Jakou matici vidíte na obrázku?", ["KM", "Korunovou", "Křídlovou", "Samojistnou"], 1],
  [18, "Jakou podložku vidíte na obrázku?", ["Pružnou", "Vějířovou", "Nord-Lock", "Ozubenou"], 1],
  [19, "Jaký závit má šroub na obrázku?", ["Jednochodý levý závit", "Dvouchodý pravý závit", "Trojchodý levý závit", "Čtyřchodý pravý závit"], 0],
  [20, "Šroub na obrázku má velikost (je označen jako) M10 x 45 dle normy ISO 4014. Které písmenko na obrázku lze nahradit číslem 45 (tedy délkou šroubu v mm)?", ["A", "B", "C", "D"], 1],
  [21, "Který z těchto druhů spojů se považuje za nerozebíratelný?", ["Šroubový spoj", "Kolíkový spoj", "Čepový spoj", "Nýtový spoj"], 3],
  [22, "Který z těchto spojů se primárně nepovažuje za spoj s tvarovým stykem?", ["Šroubový spoj", "Kolíkový spoj", "Čepový spoj", "Nýtový spoj"], 0],
  [23, "Která z těchto spojovacích součástí se kontroluje i na ohyb?", ["Šroub", "Kolík", "Čep", "Nýt"], 2],
  [24, "Ke kterému z uvedených účelů je nejméně vhodný kolíkový spoj?", ["K ustavení vzájemné přesné polohy", "K vytvoření kloubového spoje", "K přenosu síly kolmé k ose kolíku", "K přenosu kroutícího momentu z hřídele na náboj"], 1],
  [25, "Který druh kolíku má vůči ostatním nejnižší hmotnost (při podobných rozměrech)?", ["Válcový kolík", "Kuželový kolík", "Pružný kolík", "Rýhovaný kolík"], 2],
  [26, "Který druh kolíku je pojištěn vůči vypadnutí samosvorností?", ["Válcový kolík", "Kuželový kolík", "Pružný kolík", "Rýhovaný kolík"], 1],
  [27, "Který druh kolíku je pojištěn vůči vypadnutí správným uložením (nejčastěji H7/m6)?", ["Válcový kolík", "Kuželový kolík", "Pružný kolík", "Rýhovaný kolík"], 0],
  [28, "Kterou z těchto spojovacích součástí nekontrolujeme primárně (pouze) na otlačení a střih?", ["Lícovaný šroub", "Válcový kolík", "Dutý čep", "Nýt s půlkulovou hlavou"], 2],
  [29, "Čepy jsou v otvorech spojovaných součástí uloženy", ["s vůlí.", "s přesahem.", "přechodně.", "libovolně."], 0],
  [30, "Při použití které z těchto normalizovaných součástí (v souvislosti s pojištěním čepového spoje) není potřeba dělat v čepu drážku určitého tvaru?", ["Přídržka čepu", "Třmenový kroužek", "Vnější pojistný kroužek", "Závlačka"], 3],
  [31, "Přímé nýtování za studena znamená, že se jedná o nýtování ...", ["bez použití nýtu při běžné okolní teplotě.", "bez použití nýtu při teplotě pod bodem mrazu.", "s použitím nýtu při běžné okolní teplotě.", "s použitím nýtu při teplotě pod bodem mrazu."], 0],
  [32, "Po nýtování za tepla vzniká nýtový spoj...", ["pouze se silovým stykem.", "pouze s tvarovým stykem.", "s tvarovým i silovým stykem.", "pouze s materiálovým stykem."], 2],
  [33, "Který z uvedených parametrů nepatří mezi výhody nýtových spojů (oproti svarovým spojům)?", ["Lze spojovat různé materiály", "Lze vytvářet spoje v hůře přístupných místech", "Vysoká pružnost spoje", "Těsnost spoje"], 3],
  [34, "Který z uvedených parametrů nepatří mezi nevýhody nýtových spojů (oproti svarovým spojům)?", ["Vysoká hlučnost při nýtování", "Vyžadují spoustu přípravných prací", "Zeslabení materiálu v místě spoje", "Dochází k deformacím nahromaděním tepla"], 3],
  [35, "Pro které druhy kolíků je nutné vyrobit ve spojovaných součástech přesnou (vystruženou) díru?", ["Pro válcové a kuželové kolíky", "Pro kuželové a rýhované kolíky", "Pro pružné a válcové kolíky", "Pro pružné a rýhované kolíky"], 0],
  [36, "Co se nejpravděpodobněji nachází na obrázku?", ["Kolík", "Čep", "Nýt", "Hybná hřídel"], 1],
  [37, "Jaký druh kolíku se nachází na obrázku?", ["Válcový", "Rýhovaný", "Pružný", "Kuželový"], 2],
  [38, "Čím je nejvhodnější pojistit čep na obrázku? Předpokládejte že se na čepu nebudou dělat již žádné úpravy!", ["Pojistným kroužkem", "Křídlovou maticí", "Stavěcí šroubem", "Přídržkou čepů"], 0],
  [39, "Jaký druh nýtu se nachází na obrázku?", ["Rozklepávací sedlářský", "Plný s půlkulovou hlavou", "Dvoudílný uzavřený", "Dutý trhací"], 3],
  [40, "Jakou součástí z uvedených nelze zajistit tento čep na obrázku? Předpokládejte že se na čepu nebudou dělat již žádné úpravy!", ["Vnitřním pojistným kroužkem", "Stavěcím šroubem", "Stavěcím kroužkem", "Třmenovým kroužkem"], 3],
  [41, "Který z těchto spojů se neřadí (ani částečně) mezi spoje s tvarovým stykem?", ["Neokrouhlý spoj", "Klínový spoj", "Drážkový spoj", "Tlakový spoj"], 3],
  [42, "Který z těchto spojů se neřadí mezi spojeny nerozebíratelné?", ["Svarový spoj", "Tlakový spoj", "Svěrný spoj", "Pájený spoj"], 2],
  [43, "Jaká spojovací součást se používá pro vznik svěrného spoje?", ["Šroub", "Kolík", "Pero", "Čep"], 0],
  [44, "Šířka drážky v náboji i hřídeli pro těsné pero dle normy ČSN 02 2562 musí být vyrobena přesně. Jaké parametry z hlediska rozměru a drsnosti se na její boky předepisují?", ["Šířka drážky je vždy v toleranci P9 a na bokách drážek je drsnost Ra 3,2", "Šířka drážky je vždy v toleranci P9 a na bokách drážek je drsnost Ra 6,3", "Šířka drážky je vždy v toleranci H9 a na bokách drážek je drsnost Ra 3,2", "Šířka drážky je vždy v toleranci H9 a na bokách drážek je drsnost Ra 6,3"], 0],
  [45, "Který druh pera se používá pro spojení hřídele s nábojem, pokud požadujeme častý axiální posuv náboje po hřídeli?", ["Těsné pero", "Výměnné pero", "Woodruffovo pero", "Kotoučové pero"], 1],
  [46, "Které pera mezi ostatní logicky nepatří?", ["Výměnné pero", "Kotoučové opera", "Úsečové pero", "Woodruffovo pero"], 0],
  [47, "U kterých druhů per je nutné pojistit náboj vůči hřídeli v axiálním směru?", ["Pouze u spojení těsným perem", "Pouze u spojení woodruffovým perem", "U všech kromě výměnného pera", "U všech kromě woodruffova pera"], 2],
  [48, "Při použití kteréhost druhu pera je nejméně zeslaben průřez hřídele (vzhledem k její pevnosti)?", ["Při použití těsného pera", "Při použití výměnného pera", "Při použití Woodrufova pera", "Při použití úsečového pera"], 0],
  [49, "Na který z těchto druhů namáhání obvykle (pouze) kontrolujeme normalizovaná těsná pera?", ["Otlačení mezi hřídelí a perem", "Otlačení mezi nábojem a perem", "Střih pera", "Střih hřídele"], 1],
  [50, "Které z těchto spojení dokáže (při zachování podobných rozměrů) přenést největší kroutící moment?", ["Spojení se dvěma těsnými pery", "Spojení s rovnobokým drážkováním", "Spojení s jedním ploským klínem", "Svěrný spoj s rozříznutým nábojem"], 1],
  [51, "Který druh drážkování je nejvíce podobný teoretickému použití spojení s několika těsnými pery?", ["Rovnoboké drážkování", "Evolventní drážkování", "Jemné drážkování", "Woodruffovo drážkování"], 0],
  [52, "U kterého z těchto druhů spojení hřídele s nábojem s tvarovým stykem není nutné pojišťovat náboj v axiálním směru?", ["U spojení těsným perem", "U spojení neokrouhlým spojením", "U spojení jemným drážkováním", "U spojení ploským klínem"], 3],
  [53, "U spojení kterým druhem klínu není potřeba dělat tvarové změny na hřídeli při výrobě?", ["Při spojení pomocí třecího klínu", "Při spojení pomocí ploského klínu", "Při spojení pomocí drážkového klínu", "Při spojení pomocí tangenciálního klínu"], 0],
  [54, "Co je jednou ze základních výhod svěrných (a rozpěrných) spojů oproti ostatním druhům spojení hřídele s nábojem?", ["Přenášený největších kroutících momentů", "Jsou výrobně nejjednodušší", "Náboj lze na hřídel namontovat v libovolné poloze", "Dochází u nich částečně i k tvarovému styku"], 2],
  [55, "Tlakový spoj vytvořený lisováním za studena vznikne tak, že ...", ["se hřídel silou (pomocí lisu) vtlačí do díry v náboji za běžné okolní teploty.", "se hřídel silou (pomocí lisu) vtlačí do díry v náboji za teploty pod bodem mrazu.", "se hřícel zchladí a vloží se volně do díry v náboji.", "se náboj zchladí a vloží se volně do díry v hřídeli."], 0],
  [56, "Jaká součást je na obrázku?", ["Pero", "Čep", "Klín", "Kolík"], 2],
  [57, "Jakou hlavu by měl mít šroub, který se vkládá do otvoru v součásti na obrázku?", ["Šestihrannou", "Kuželovou", "Čočkovitou", "Válcovou"], 3],
  [58, "Pro jakou součást je vytvořena drážka v hřídeli na obrázku?", ["Pro Woodruffovo pero", "Pro ploský klín", "Pro těsné pero", "Pro drážkový klín"], 0],
  [59, "Co je na obrázku?", ["Pomůcka pro vytvoření tlakového spoje za studena", "Upínací pouzdro pro přenos kroutícího momentu silovým stykem", "Celek s evolventním drážkováním pro přenos momentu tvarovým stykem", "Tangenciální klín"], 1],
  [60, "Součást na obrázku má uvnitř v otvoru vyrobeno ...", ["vnitřní ozubení.", "rovnoboké drážkování.", "jemné drážkování.", "neokrouhlé spojení."], 1],
  [61, "Která z těchto hřídelí nepřenáší kroutící moment?", ["Nosná hřídel", "Hybná hřídel", "Kliková hřídel", "Předlohová hřídel"], 0],
  [62, "V jakém provedení se konstruují hybné hřídele?", ["Vždy otočně", "Vždy nepohyblivě", "Otočně i nepohyblivě", "Nezáleží na konstrukci"], 0],
  [63, "Na jaký druh namáhání primárně kontrolujeme nosné hřídele?", ["Ohyb", "Střih (smyk)", "Vzpěr", "Krut"], 0],
  [64, "Které tvrzení o hřídelových čepech NENÍ pravdivé?", ["Jsou to části hřídele, které jsou ve styku s ložiskem.", "Přenášejí všechny síly mezi hřídelí a rámem stroje nebo ložiskem.", "Dělíme je na axiální, radiální a kombinované.", "Jsou vždy kontrolovány na ohyb i krut."], 3],
  [65, "Který z těchto hřídelových čepů NENÍ určen k zachycení síly rovnoběžné s osou hřídele?", ["Krční", "Hřebenový", "Kulový", "Kuželový"], 0],
  [66, "Který z těchto hřídelových čepů NENÍ určen k zachycení síly kolmé k ose hřídele?", ["Krční", "Hřebenový", "Kulový", "Kuželový"], 1],
  [67, "Na jaký druh namáhání kontrolujeme axiální hřídelové čepy?", ["Ohyb", "Otlačení", "Krut", "Střih (smyk)"], 1],
  [68, "Který z těchto hřídelových čepů NEPOTŘEBUJE nutně dělený náboj?", ["Krční", "Hřebenový", "Kulový", "Kuželový"], 3],
  [69, "Co se rozumí pojmem 'kritické otáčky hřídele'?", ["Maximální otáčky hřídele, při větších otáčkách hřídel nemůže pracovat.", "Minimální otáčky hřídele, při menších otáčkách hřídel nemůže pracovat.", "Otáčky, při kterých hřídel nemůže pracovat, musí pracovat buď v nižších nebo vyšších otáčkách.", "Otáčky, při kterých dochází ke kmitání hřídele způsobené vlastní tíhou."], 2],
  [70, "Na kterém parametru primárně závisí velikost 'kritických otáček' hřídele?", ["Průhyb hřídele způsobený vlastní tíhou.", "Druh ložisek, ve kterých je hřídel uložena.", "Funkce hřídele, zda je nosná nebo hybná.", "Počet konstrukčních vrubů na hřídeli."], 0],
  [71, "Co způsobuje každý tzv. konstrukční vrub na hřídel?", ["Výrazně zvýšenou koncentraci napětí", "Změnu způsobu namáhání hřídele", "Lepší drsnost povrchu", "Zvýšení ohybového momentu"], 0],
  [72, "Který z uvedených prvků hřídele NENÍ konstrukčním vrubem?", ["Drážka pro pero", "Hřídelový čep", "Zápich", "Jemný závit pro KM matici"], 1],
  [73, "Který z těchto parametrů NENÍ potřebný k výpočtu velikosti přenášeného kroutícího momentu na hřídeli?", ["Přenášený výkon", "Otáčky hřídele", "Ludolfovo číslo", "Modul průřezu v krutu"], 3],
  [74, "Na čem NEZÁVISÍ volba materiálu hřídele?", ["Na způsobu a velikosti zatížení", "Na požadované hmotnosti", "Na požadovaném tepelném zpracování", "Na druhu ložisek na hřídeli"], 3],
  [75, "Který vzorec byste použili pro výpočet redukovaného momentu na hybné hřídeli (kruhového průřezu)?", ["M_RED = sqrt(M_O^2 + 3M_K^2)", "M_RED = sqrt(M_O^2 + 4M_K^2)", "M_RED = sqrt(M_O^2 + 0,75M_K^2)", "M_RED = sqrt(M_O^2 + M_K^2)"], 2],
  [76, "Na obrázku je schéma (řez) jednostupňové převodovky. Jaký způsobem je namáhána výstupní hřídel v (červeně) označeném místě?", ["Pouze na ohyb", "Pouze na krut", "Na ohyb i krut", "Hřídel v tomto místě není namáhána"], 2],
  [77, "Jaký druh hřídele je na obrázku?", ["Nosná", "Kliková", "Vačková", "Na obrázku není hřídel"], 2],
  [78, "K čemu je vyrobena (šipkou) označená drážka na vyobrazené hřídeli?", ["Pro těsné pero", "Pro ploský klín", "Pro MB podložku", "Pro pojistný kroužek"], 2],
  [79, "Na obrázku se nachází Kardanová hřídel. O jaký druh hřídele se tedy jedná?", ["Nosnou", "Hybnou", "Klikovou", "Vyvažovací"], 1],
  [80, "Na obrázku se nachází průřez jednostupňovou šnekovou převodovkou. Vstupní (modrá) hřídel je v místech A a C uložena v ložiscíc... Mezi jakými dvěma místy na této hřídeli působí kroutící moment?", ["Mezi A a C", "Mezi A a D", "Mezi B a C", "Mezi B a D"], 3],
  [81, "Jak se nazývá druh svaru, u kterého svařované součásti leží (plochou) na sobě svar je mezi tĕmito plochami?", ["Tupý svar", "Lemový svar", "Koutový svar", "Přeplátovaný svar"], 3],
  [82, "Do které kategorie svarů lze zařadit svar tvaru 'U'?", ["Tupé svary", "Lemový svar", "Koutový svar", "Přeplátovaný svar"], 0],
  [83, "Který z uvedených materiálů je nejhůře svařitelný (resp. obvykle nesvařitelný)?", ["Oceli", "Neželezné kovy", "Plasty", "Litiny"], 3],
  [84, "Co nepatří mezi výhody svařování?", ["Vysoká produktivita vytváření spojů", "Malá hlučnost v pruběhu práce", "Těsnost vytvořeného spoje", "Poddajnost vytvořeného spoje bez pnutí"], 3],
  [85, "Pro který z uvedených svarů obvykle není potřeba přídavný materiál?", ["Děrový svar", "Rohový svar", "Lemový svar", "Svar tvaru 'V'"], 2],
  [86, "Čému se nejvíce podobá značka pro označení montážního svaru?", ["Kružnici", "Praporku", "Písmenu 'Z'", "Pravoúhlému trojúhelníku"], 1],
  [87, "Jaký druh tepelného zpracování se provádí u svařenců za účelem snížení vnitřního pnutí?", ["Žíhání", "Kalení", "Popouštěni", "Zušlechtování"], 0],
  [88, "Kterou z uvedených zásad NENÍ vhodný dodržet při konstruování velkého složitého svařence se žebry?", ["Přesné rozměry svařence obrábět až po svaření", "Na výkrese předepsat vhodné tepelné zpracování pro snížení pnutí po svaření", "U žeber nepoužívat ostré hrany", "Na výkrese předepisovat raději větší a delší svary bez přerušení"], 3],
  [89, "Na jaký druh namáhání kontrolujeme vždy přeplátované spoje?", ["Tah", "Střih", "Ohyb", "Krut"], 1],
  [90, "Čím vzniká pájený spoj?", ["Adhezí", "Kohezí", "Difuzí", "Natavením stykových ploch"], 2],
  [91, "Co je to 'pájka'?", ["Přístroj pro tavení přídavného materiálu při pájení", "Přídavný materiál pro vznik pájeného spoje", "Nástroj pro přípravu stykových ploch pro pájení", "Kyselina pro chemické očištění stykových ploch před pájením"], 1],
  [92, "Přídavné materiály pro pájení rozlišujeme na měkké a tvrdé. Který z uvedených materiálů by se dal zařadit do měkkých?", ["Měď", "Zinek", "Stříbro", "Cín"], 3],
  [93, "Co nepatří mezi výhody pájených spojů?", ["Možnost spojování i hůře tavitelných materiálů", "Nedochází k tepelnému ovlivnění oblasti kolem spoje", "Jednoduchost zařízení", "Vysoká pevnost spojů"], 3],
  [94, "Co nepatří mezi výhody lepených spojů?", ["Lepidla mají izolační vlastnosti", "Lze spojovat i jinými způsoby nespojitelné materiály", "Nízká hmotnost přídavného materiálu", "Stálost spoje i za vyšších teplot"], 3],
  [95, "Na co si nemusíte dát pozor při konstruování (navrhování) lepeného spoje?", ["Na maximální možnou velikost stykové plochy", "Na skutečnost, aby byl spoj namáhaný pouze na střih", "Na volbu vhodného lepidla", "Na nízkou hmotnost lepidla"], 3],
  [96, "Jaký druh svaru je na obrázku?", ["Tupý", "Lemový", "Koutový", "Přeplátovaný"], 2],
  [97, "Na výkrese se u svaru nachází následující značka. O jaký svar se nejedná?", ["Koutový", "Vypouklý", "Kontinuální (nepřerušovaný)", "Montážní"], 3],
  [98, "Na výkrese se u svaru nachází následující značka (z5 111). O jaký svar se jedná?", ["Přerušovaný", "Obvodový", "Přeplátovaný", "Svar délky 111 mm"], 0],
  [99, "Dvě zobrazené součásti (hranaté trubky) are spojeny červeně vyobrazeným bodovým svarem a are namáhány zakreslenými silami. Jakým způsobem je svar namáhán?", ["Střihem (smykem)", "Tahem", "Tlakem", "Ohybem"], 1],
  [100, "V rámci výroby vyobrazeného celku (žlutá deska a modrý váleček) je potřeba udělat tĕsto operace: 1- Svaření desky s válečkem, 2- Obrobení čelních ploch, 3- Výroba přesného rozměru s tolerancí H7, 4- Výroba hrubého plného válečku s Ø40. Jaký je nejvhodnější postup při výroby vyobrazeného celku?", ["4-1-2-3", "4-2-3-1", "4-3-2-1", "4-3-1-2"], 0],
  [101, "Jak se nazývá součást potrubí, která slouží k vyrovnání změny délek potrubí v důsledku změny teploty?", ["Armatura", "Třmen", "Kompenzátor", "Fitinka"], 2],
  [102, "Která z uvedených součásti potrubí se neřadí mezi armatury?", ["Součást sloužící k regulaci průtoku v potrubí", "Součást sloužící k odvzdušněné potrubí", "Součást sloužící k měření tlaku v potrubí", "Součást sloužící ke změně směru proudění"], 3],
  [103, "Co znamená, když je na trubce napsáno \"PN10\"?", ["Znamená to, že maximální pracovní tlak je 10 MPa.", "Znamená to, že maximální pracovní přetlak je 10 MPa.", "Znamená to, že maximální pracovní tlak je 1 MPa.", "Znamená to, že maximální pracovní přetlak je 1 MPa."], 3],
  [104, "Co znamená, když je na trubce napsáno 'DN400'?", ["Znamená to, že vnitřní průměr potrubí je přibližně 400 mm.", "Znamená to, že vnější průměr potrubí je přibližně 400 mm.", "Znamená to, že vnitřní průměr potrubí je přibližně 40 mm.", "Znamená to, že vnější průměr potrubí je přibližně 40 mm."], 0],
  [105, "Na kterém z uvedených parametrů nezávisí minimální tloušťka stěny potrubí?", ["Na průměru potrubí", "Na materiálu potrubí", "Na pracovním tlaku v potrubí", "Na rychlosti proudění v potrubí"], 3],
  [106, "Jaký druh materiálu trubky je nejméně vhodný pro vedení odpadního potrubí?", ["Ocelové potrubí", "Litinové potrubí", "Plastové potrubí", "Betonové potrubí"], 0],
  [107, "Co nepatří mezi výhody plastových potrubí?", ["Nízká hmotnost", "Hladkost stěn", "Vysoká pevnost", "Jednoduché spojování"], 2],
  [108, "Ke kterému druhu spojení trubek jsou potřeba šrouby a matice jako spojovací materiály?", ["Hrdlové spojení", "Přírubové spojení", "Závitové spojení", "Pájené spojení"], 1],
  [109, "Který druh spojení trubek Ize nejlépe utěsnit pomocí lněných vlasců nebo teflonových pásek?", ["Hrdlové spojení", "Přírubové spojení", "Závitové spojení", "Pájené spojení"], 2],
  [110, "Na kterém z uvedených parametrů NEZÁVISÍ velikost prodloužení trubky při zvýšení její teploty?", ["Světlost trubky", "Počáteční délka trubky", "Materiál trubky", "Rozdíl mezi počáteční a konečnou teplotou"], 0],
  [111, "Jak se nazývá prvek potrubí, který zajišťuje, aby dopravovaná látku proudila pouze v jednom směru?", ["Zpětná klapka", "Pojistný ventil", "Regulační šoupátko", "Trojcestný kohout"], 0],
  [112, "Jak se nazývá prvek potrubí, kterým nelze regulovat velikost průtoku dopravované látky?", ["Škrticí klapka", "Pojistný ventil", "Regulační šoupátko", "Přímý jednocestný kohout"], 1],
  [113, "Pro správnou funkci potrubí je třeba zajistit, aby ...", ["... na začátku a na konci potrubí byl neustále rozdílný tlak.", "... byl tlak po celé délce potrubí konstantní.", "... byl tlak dopravované látky v potrubí pokud možno nulový.", "... byla poloha jejího začátku vždy níže než jeho konce."], 0],
  [114, "Co udává tzv. pracovní stupeň potrubí?", ["Maximální přetlak v potrubí v závislosti na teplotě přepravované látky", "Maximální přetlak v potrubí v závislosti na světlosti potrubí", "Maximální teplotu přepravovaného média v závislosti na tlaku v potrubí", "Maximální teplotu přepravovaného média v závislosti na světlosti potrubí"], 0],
  [115, "Jaká je základní jednotka veličiny 'objemový průtok'?", ["m3/s", "m3/kg", "kg/m3", "kg/s"], 0],
  [116, "Co zobrazuje tato schématická značka na potrubním schématu?", ["Hydromotor", "Tlakoměr", "Filtr", "Kohout"], 3],
  [117, "Jaká součást je na obrázku?", ["Pojistné šoupátko", "Škrticí klapka", "Teplotní kompenzátor", "Třícestný ventil"], 1],
  [118, "O jaké spojení trubek se jedná, pokud se nekolik takových trubek na obrázku spojí za sebe?", ["Hrdlové spojení", "Přírubové spojení", "Závitové spojeni", "Gumové spojení"], 0],
  [119, "Jak se souhrnně nazývají součásti na obrázcích?", ["Armatury", "Třmeny", "Fitinky", "Příruby"], 2],
  [120, "K čemu nelze použít součást na obrázku?", ["Ke snížení přenosu hluku a vibrací po potrubí", "Ke kompenzaci teplotních dilatací potrubí", "K vyrovnání montážních nepřesností", "K regulaci tlaku v potrubí"], 3],
  [121, "Ozubené převody are ....", ["přímé převody se silovým stykem.", "přímé převody s tvarovým stykem.", "nepřímé převody se silovým stykem.", "nepřímé převody se silovým stykem."], 1],
  [122, "Co NEPATŘÍ mezi výhody ozubených převodů?", ["Přenos velkých výkonů", "Stálný převodový poměr", "Velmi dlouhá životnost", "Tlumí rázy"], 3],
  [123, "Osy ozubených kol kuželového soukolí are navzájem ...", ["kolineární.", "rovnoběžné.", "různoběžné.", "mimoběžné."], 2],
  [124, "Jaký je poměr mezi velikostí průměrů základní (Db) a roztečné (D) kružnice u běžného čelního ozubeného kola s vnějším ozubením?", ["Db < D", "Db > D", "Db = D", "Nelze jednoznačně rozhodnout záleží na modulu."], 0],
  [125, "Který z těchto parametrů ozubeného čelního soukolí s vnějším ozubením NELZE spočítat pomocí modulu?", ["Osovou vzdálenost", "Převodový poměr", "Hlavovou vůli", "Šířka ozubení"], 1],
  [126, "Které tvrzení NENÍ pravdivé o 'základním profilu' evolventního ozubení?", ["Průměr roztečné kružnice se rovná nekonečnu.", "Má rovné boky zubů.", "Jeho tvar a parametry are používány při výrobě nástrojů k výrobě ozubených kol.", "Výška hlavy zubu není rovna modulu ozubení (při úhlu záběru 20°)."], 3],
  [127, "Jak NELZE dosáhnout toho, aby nedošlo u čelního ozubeného kola s přímými zuby k podřezání jeho paty?", ["Změnou úhlu záběru", "Změnou profilu boku zubu", "Korekcí ozubení", "Změnou modulu ozubení"], 3],
  [128, "Při kterém z těchto případů dojde k podřezání paty zubu čelního ozubeného kola s přímými zuby s úhlem záběru 20°?", ["Při výrobě ozubeného kola, které má 18 zubů.", "Při výrobě ozubeného kola, které má 15 zubů.", "Při běhu (provozu) ozubeného kola, které má 18 zubů.", "Při běhu (provozu) ozubeného kola, které má 15 zubů."], 1],
  [129, "Který z těchto parametrů se zmĕní, pokud při výrobě čelního ozubeného kola s přímými zuby použijeme korekci (v porovnání s tím, pokud bychom ji nepoužili)?", ["Úhel záběru", "Šířka ozubení", "Modul ozubení", "Výška zubu"], 3],
  [130, "Která z těchto sil je u čelního ozubeného kola s přímými zuby při záběru nulová?", ["Tangenciální síla", "Radiální síla", "Axiální síla", "Normálová síla"], 2],
  [131, "Jak NEJSOU namáhána zuby ozubených kol?", ["Na ohyb", "Na krut", "Na otlačení", "Otěrem"], 1],
  [132, "Který parametr není důležitý při kontrole zubu ozubeného kola na ohyb?", ["Přenášený moment", "Modul ozubení", "Materiál ozubeného kola", "Drsnost boku zubu"], 3],
  [133, "Co NEPATŘÍ mezi výhody čelních ozubených kol se šikmými zuby (v porovnání s přímými zuby)?", ["Tichý chod", "Menší rozměry (moduly) (resp. větší únosnost)", "Přenos vĕtších výkonů", "Menší namáhání ložisek"], 3],
  [134, "Jaká je hlavní výhoda šnekových soukolí?", ["Velká účinnost", "Přenos obrovských výkonů", "Malé namáhání ložisek", "Velké převodové pomĕry"], 3],
  [135, "Která z tĕchto sil je u kuželového ozubeného kola (úhel os 90°) při zábĕru nulová?", ["Tangenciální síla", "Radiální síla", "Axiální síla", "Axiální, radiální i tangenciální are nenulové."], 3],
  [136, "Čím vzniklo typické poškození ozubeného kola na obrázku?", ["Pittingem", "Lomovým porušením", "Gallingem", "Abrazí"], 0],
  [137, "O jaký druh ozubeného soukolí na obrázku se jedná?", ["Čelní", "Paloidní", "Hypoidní", "Šnekové"], 2],
  [138, "Jaký typ ozubeného kola je na obrázku?", ["Čelní ozubené kola s přímými zuby", "Kuželové ozubené kolo", "Čelní ozubené kola s šikmými zuby", "Šnekové ozubené kola"], 3],
  [139, "Na obrázku je nekorigované čelní ozubené kolo s deseti přímými zuby. Kterou kótu na obrázku nelze vypočítat pouze se znalostí hodnoty modulu a zmíněného počtu zubů?", ["A", "B", "C", "D"], 3],
  [140, "Který ze zakótovaných průmĕrů ozubeného kola Ize nazvat jako patní?", ["A", "B", "C", "D"], 2],
  [141, "Jaký druh tření vzniká v kluzných ložiscících?", ["Valivé tření", "Smykové tření", "Vláknové tření", "Nevzniká v nĕm tření"], 1],
  [142, "Který druh tření v kluzných ložiscících má nejnižší součinitel smykového tření?", ["Suché", "Polosuché", "Kapalinné", "Vlhké"], 2],
  [143, "Který druh tření v kluzných ložiscících lze použít pouze pro malé rychlosti pohybu?", ["Suché", "Polosuché", "Kapalinné", "Vlhké"], 0],
  [144, "Které kluzné ložisko se NESKLÁDÁ z více částí?", ["Ložiskové pouzdro", "Ložisková pánev", "Segmentové ložisko", "Pouzdro, pánev i segmentové ložisko se skládají z více částí"], 0],
  [145, "Který z tĕchto materiálů kluzných ložisek nejménĕ snáší rázy?", ["Ložiskové kompozice (Babbit)", "Slitiny mĕdi", "Slitiny hliníku", "Šedá litina"], 3],
  [146, "Kluzná ložiska NEKONTROLUJEME na", ["otlačení.", "oteplení.", "maximální kluznou rychlost.", "ohyb."], 3],
  [147, "K čemu slouží u valivých ložisek klec?", ["Držení valivých elementů (a jejich oddĕlování)", "Zabránĕní vniku nečistot do ložiska", "Uložení ložiska na hřídeli", "Uložení ložiska v náboji"], 0],
  [148, "Které ložisko se NEPOVAŽUJE za ložisko s 'čarovým' stykem?", ["Kuličkové ložisko", "Kuželíkové ložisko", "Válečkové ložisko", "Jehlové ložisko"], 0],
  [149, "Které z tĕchto ložisek NEDOKÁŽE zachytit axiální i radiální sílu dohromady?", ["Kuličkové ložisko s kosoúhlým stykem", "Soudečkové ložisko", "Kuželíkové ložisko", "Jehlové ložisko"], 3],
  [150, "Které z tĕchto ložisek NEDOKÁŽE zachytit žádnou axiální sílu (bez ohledu na speciální konstrukce)?", ["Axiální kuličkové ložisko", "Jednořadé soudečkové ložisko", "Kuželíkové ložisko", "Válečkové ložisko"], 3],
  [151, "Které z tĕchto ložisek je nejménĕ vhodné pro snášení velkých rázů?", ["Kuličkové ložisko", "Kuželíkové ložisko", "Jehlové ložisko", "Válečkové ložisko"], 0],
  [152, "Jaký druh uložení se nejčastěji volí pro uložení valivého ložiska na hřídeli?", ["Uložení s vůlí", "Přechodné uložení", "Uložení s přesahem", "Nezáleží na druhu uložení ložiska na hřídeli"], 1],
  [153, "Který parametr NENÍ potřebný pro výpočet trvanlivosti ložiska v hodinách?", ["Dynamická únosnost 'C'", "Dynamické ekvivalentní zatížení 'P'", "Otáčky hřídele 'n'", "Průmĕr hřídele 'd'"], 3],
  [154, "Který parametr NEHRAJE zásadní roli při výbĕru typu valivého ložiska?", ["Pomĕr axiální a radiální síly působící na ložisko", "Otáčky hřídele, na nichž are ložiska", "Požadovaná trvanlivost ložiska", "Způsob mazání valivého ložiska"], 3],
  [155, "Co je výhodou kluzných ložisek?", ["Teoreticky nepotřebují mazání", "Jejich výroba nemusí být přesná", "Dochází k minimálním ztrátám třením", "Mají velmi jednoduchou konstrukci"], 3],
  [156, "K čemu slouží (šipkou) označená část na zobrazené ložiskové jednotce?", ["K uchycení ložiska ke hřídeli", "Pro pojištění vnĕjšího kroužku ložiska na jednotku", "K mazání ložiska", "Pro zvýšení dynamické únosnosti ložiska"], 2],
  [157, "Pro jaké síly je vhodné ložisko na obrázku?", ["Velké radiální a malé axiální", "Žádné radiální a velké axiální", "Velké radiální a žádné axiální", "Malé radiální a velké axiální"], 1],
  [158, "Která část a proč chybí válečkovému ložisku na obrázku?", ["Chybí vnitřní kroužek, protože je volnĕ posuvný (oddĕlávací)", "Chybí vnĕjší kroužek, protože je ložisko nekompletní", "Chybí klec, aby se válečky mohly přizpůsobit hřídeli", "Chybí valivé elementy, aby se ložisko mohlo valit po vnĕjším kroužku"], 0],
  [159, "Jaký typ valivého ložiska je na obrázku?", ["Kuličkové", "Válečkové", "Jehlové", "Soudečkové"], 3],
  [160, "Které tvrzení o ložisku na obrázku NENÍ pravdivé?", ["Jedná se o kluzné ložisko", "Zvládne přenášet velké axiální zatížení", "Dovoluje natočit vnitřní kroužek vůči vnĕjšímu", "Dochází v nĕm ke smykovému (čepovému) tření"], 1],
  [161, "Jak NELZE vypočítat převodový pomĕr u řetĕzového převodu?", ["Jako pomĕr otáček obou řetĕzových kol", "Jako pomĕr počtu zubů obou řetĕzových kol", "Jako pomĕr roztečných průmĕrů obou řetĕzových kol", "Jako pomĕr výkonů na obou řetĕzových kolech"], 3],
  [162, "Kuželový třecí převod je převod ...", ["se silovým stykem.", "s tvarovým stykem.", "s materiálovým stykem.", "se silovým i tvarovým stykem dohromady."], 0],
  [163, "Kterou z možností NELZE zajistit snížení prokluzu u třecích převodů?", ["Zvýšení přítlačné síly mezi obĕma třecími koly", "Zmĕnou materiálů třecích kol", "Zvýšením otáček třecích kol", "Připevněním obložení ke třecím kolům"], 2],
  [164, "Přes jaké plochy se přenáší síly mezi řemenicemi a úzkým klínovým řemenem? Přenáší se přes ...", ["boky řemene.", "nárazník řemene.", "zuby řemene.", "výztužná vlákna řemene."], 0],
  [165, "Co je výhodou třecích převodů?", ["Malé namáhání ložisek", "Přenos velkých výkonů", "Stálý převodový poměr", "Tlumí rázy"], 3],
  [166, "Řetĕzové převody are převody....", ["nepřímé se silovým stykem.", "nepřímé s tvarovým stykem.", "přímé se silovým stykem.", "přímé s tvarovým stykem."], 3],
  [167, "Jaký je pomĕr obvodových rychlostí obou řemenic v řemenovém převodu při zanedbání prokluzu?", ["Hnací řemenice má vĕtší obvodovou rychlost než hnaná.", "Hnací řemenice má menší obvodovou rychlost než hnaná.", "Hnací řemenice má stejnou obvodovou rychlost jako hnaná.", "Závislost nelze jednoznačnĕ rozhodnout."], 2],
  [168, "Kam se umísťuje napínací kladka v řemenovém převodu?", ["Do ochablé části pásu a co nejblíže malé řemenice", "Do ochablé části pásu a co nejblíže velké řemenice", "Do napnuté části pásu a co nejblíže malé řemenice", "Do napnuté části pásu a co nejblíže malé řemenice"], 0],
  [169, "Co NEPATŘÍ mezi výhody řemenových převodů s ozubenými řemeny?", ["Pracují bez skluzu", "Namáhají ménĕ ložiska", "Mají tichý a klidný chod", "Dobře snáší vysoké teploty"], 3],
  [170, "Co patří mezi výhody řemenových převodů s klínovými řemeny oproti třecím převodům?", ["Malé zatížení ložisek", "Stálý převodový poměr", "Není nutné řešit napínání", "Velká vzdálenost os"], 3],
  [171, "Jaký druh 'opásání' se používá tĕmĕř výhradnĕ u řetĕzových převodů?", ["Uzavřené", "Otevřené", "Zkřížené", "Polozkřížené"], 1],
  [172, "Co NEPATŘÍ mezi výhody řetĕzových převodů?", ["Menší namáhání ložisek", "Vysoká účinnost", "Stálý převodový poměr", "Nevyžaduje mazání"], 3],
  [173, "Který z uvedených řetĕzů NENÍ plnĕ normalizovaný?", ["Článkový řetĕz", "Válečkový řetĕz", "Gallův řetĕz", "Zubový řetěz"], 3],
  [174, "Který z uvedených řetĕzů má nejmenší tření mezi nĕm a řetĕzovým kolem při bĕhu?", ["Pouzdrový řetĕz", "Válečkový řetĕz", "Gallův řetĕz", "Ewartův řetěz"], 1],
  [175, "Jak se jmenuje řetĕz, který je snadno rozebíratelný vzájemným pootočením článků o 90° a vysunutím?", ["Pouzdrový řetĕz", "Ewartův řetĕz", "Gallův řetĕz", "Článkový řetĕz"], 1],
  [176, "Jak se jmenuje řetĕz na obrázku?", ["Fleyerův řetĕz", "Ewartův řetĕz", "Gallův řetĕz", "Energetický řetĕz"], 2],
  [177, "Jaký druh řemenu je na obrázku?", ["Klínový řemen", "Plochý řemen", "Variátorový řemen", "Ozubený řemen"], 0],
  [178, "Jaký druh soukolí je na obrázku?", ["Kuželové soukolí", "Lícní soukolí", "Čelní vnĕjší soukolí", "Šnekové soukolí"], 1],
  [179, "Pro jaký řemen je vhodná řemenice na obrázku?", ["Pro žádný nejedná se o řemenici", "Pro plochý řemen", "Pro klínový řemen", "Pro ozubený řemen"], 3],
  [180, "Jaký úhel opásání má hnaná řemenice na obrázku?", ["Do 90°", "V rozmezí 90° až 180°", "Přesnĕ 180°", "Vĕtší než 180°"], 3],
  [181, "Jaká je hlavní funkce všech spojek?", ["Přenos kroutícího momentu", "Ochrana proti přetížení", "Tlumení kmitů a rázů", "Zajištĕní plynulého rozbĕhu"], 0],
  [182, "Jaká je základní vlastnost pevných (mechanických neovládaných) spojek?", ["Jsou jednoduché a levné", "Umí kompenzovat výrobní nepřesnosti", "Tlumí kmity a rázy", "Zajišťují plynulý rozbĕh"], 0],
  [183, "Jaká je základní vlastnost vyrovnávacích (mechanických neovládaných) spojek?", ["Jsou jednoduché a levné", "Umí kompenzovat výrobní nepřesnosti", "Tlumí kmity a rázy", "Zajišťují plynulý rozbĕh"], 1],
  [184, "Která z tĕchto výsuvných ovládaných spojek NEPŘENÁŠÍ kroutící moment pomocí silového styku?", ["Čelní třecí spojka", "Kuželová třecí spojka", "Lamelová třecí spojka", "Zubová výsuvná spojka"], 3],
  [185, "Která z tĕchto spojek se řadí mezi ovládané spojky?", ["Korýtková spojka", "Kloubová spojka", "Spojka s pryžovou deskou", "Spojka se střižným kolíkem"], 3],
  [186, "Která z tĕchto spojek se NEŘADÍ mezi ovládané spojky?", ["Volnobĕžná spojka", "Rozbĕhová spojka", "Kuličková vysmekávací spojka", "Přírubová spojka"], 3],
  [187, "Jaký obchodní název má spojka s pryžovou deskou?", ["BKN", "HARDY", "BIBI", "PERIFLEX"], 1],
  [188, "Jakým způsobem (stykem) přenáší kroutící moment nejjednodušší trubková spojka?", ["Materiálovým stykem", "Tvarovým stykem", "Silovým stykem", "Trubková spojka neexistuje"], 1],
  [189, "Jak se nazývá spojky, které dokážou přenášet kroutící moment pouze v jednom smĕru otáčení?", ["Rozbĕhové spojky", "Volnobĕžné spojky", "Třecí spojky", "Zubové spojky"], 1],
  [190, "Která spojka se používá pro vytvoření tzv. Kardanova závĕsu, používaného typicky pro pohon vozidel?", ["Kloubová spojka", "Korýtková spojka", "Obručová spojka", "Třecí spojka"], 0],
  [191, "Která z tĕchto brzd funguje primárnĕ na principu vláknového tření?", ["Jednočelisťová brzda", "Pásová brzda", "Kotoučová brzda", "Bubnová brzda"], 1],
  [192, "Která z tĕchto pásových brzd je nejvhodnĕjší pro oba smysly otáčení?", ["Jednoduchá", "Součtová", "Rozdílová", "Diferenciální"], 1],
  [193, "Která z tĕchto brzd NENAMÁHÁ brzdĕnou hřídel na ohyb?", ["Jednočelisťová brzda", "Dvoučelisťová brzda", "Kotoučová brzda", "Pásová brzda"], 1],
  [194, "Na principu jakého jednoduchého stroje funguje jednočelisťová brzda?", ["Páka", "Kladka", "Klín", "Naklonĕná rovina"], 0],
  [195, "Která ze základních typů brzd je nejhůře samočinnĕ chlazena vzduchem?", ["Jednočelisťová brzda", "Pásová brzda", "Kotoučová brzda", "Bubnová brzda"], 3],
  [196, "Která ze základních typů brzd Ize zařadit mezi axiální brzdy?", ["Jednočelisťová brzda", "Pásová brzda", "Kotoučová brzda", "Bubnová brzda"], 2],
  [197, "Která z tĕchto informací obecnĕ o brzdách NENÍ pravdivé?", ["Slouží k zajištĕní klidové polohy", "Mĕní se (při jejich činnosti) potenciální energie na tepelnou", "Brzdného účinku je dosaženo silovým stykem", "Mechanické brzdy se dĕlí na radiální a axiální"], 1],
  [198, "Na kterém z tĕchto parametrů nezávisí velikost ovládací síly jednočelisťové brzdy?", ["Materiál brzdového obložení", "Rozmĕry ovládací páky", "Rozmĕry brzdĕného kotouče", "Úhel opásání čelisti"], 2],
  [199, "Lamelové brzdy are konstrukčnĕ podobné ...", ["spojkám.", "ozubeným kolům.", "pružinám.", "ložiskám."], 0],
  [200, "Jaká síila vždy působí proti síle třecí při brzdĕní?", ["Obvodová síla", "Normálová síla", "Ovládací síla", "Gravitační síla"], 0],
  [201, "Hydrostatické mechanismy se řadí mezi mechanismy ...", ["kinematické.", "pneumatické.", "tekutinové.", "ozubené."], 2],
  [202, "Co NEPATŘÍ mezi výhody hydrostatických mechanismů?", ["Přenos energie na velké vzdálenosti", "Velká životnost", "Vysoká účinnost", "Snadná regulace"], 2],
  [203, "Který prvek NENÍ součástí hydrostatického mechanismu?", ["Nádrž", "Čerpadlo", "Hydromotor", "Vzdušník"], 3],
  [204, "Který druh energie má zcela zanedbatelnou hodnotu při přenosu sil v hydrostatickém mechanismu?", ["Potenciální", "Kinetická", "Tlaková", "Potenciální, kinetická ani tlaková energie nemá zanedbatelnou hodnotu"], 0],
  [205, "Jaký účel má v hydrostatickém mechanismu hydrogenerátor?", ["Mĕní energii mechanickou na tlakovou", "Mĕní energii mechanickou na potenciální", "Mĕní energii tlakovou na mechanickou", "Mĕní energii tlakovou na potenciální"], 0],
  [206, "Které z tĕchto druhů čerpadel má nejmenší tlakové pulzace kapaliny na výstupu?", ["Zubové čerpadlo", "Lamelové čerpadlo s tlakvĕ nevyváženým rotorem", "Jednořadé jednočinné pístové čerpadlo", "Šroubové čerpadlo"], 3],
  [207, "Které z tĕchto druhů čerpadel je konstrukčnĕ nejjednodušší?", ["Zubové čerpadlo", "Lamelové čerpadlo", "Axiální pístové čerpadlo", "Radiální pístové čerpadlo"], 0],
  [208, "Ve kterém z tĕchto čerpadel Ize nalézt klikový mechanismus?", ["Zubové čerpadlo", "Šroubové čerpadlo", "Řadové pístové čerpadlo", "Lamelové čerpadlo"], 2],
  [209, "Které z tĕchto druhů čerpadel Ize regulovat zmĕnou excentricity rotoru vůči statoru?", ["Řadové pístové čerpadlo", "Lamelové čerpadlo", "Šroubové čerpadlo", "Axiální pístové čerpadlo"], 1],
  [210, "Které z tĕchto druhů čerpadel Ize regulovat naklopením desky ovládající pohyb pístů?", ["Řadové pístové čerpadlo", "Lamelové čerpadlo", "Radiální pístové čerpadlo", "Axiální pístové čerpadlo"], 3],
  [211, "Jaký základní tvar má značka for čerpadlo v normalizovaných hydraulických schématech?", ["Kružnice", "Čtverec", "Obdélník", "Šestiúhelník"], 0],
  [212, "V normalizovaných hydraulických schématech se elektrický motor značí písmenkem M, kolem nĕhož je...", ["kružnice.", "čtverec.", "obdélník.", "trojúhelník."], 0],
  [213, "Která z možností nevyjadřuje funkci nádrže v hydrostatických mechanismech?", ["Zásobování (uchování) pracovní kapaliny", "Akumulace tlakové energie pracovní kapaliny", "Zachycení nečistot v pracovní kapalinĕ", "Chlazení pracovní kapaliny"], 1],
  [214, "K čemu slouží v hydrostatickém mechanismu pojistný ventil?", ["K řízení velikosti tlaku v obvodu", "K řízení velikosti průtoku pracovní kapaliny v obvodu", "K řízení smĕru toku pracovní kapaliny v obvodu", "K akumulaci energie"], 0],
  [215, "K čemu slouží v hydrostatickém mechanismu škrtící ventil?", ["K řízení velikosti tlaku v obvodu", "K řízení velikosti průtoku pracovní kapaliny v obvodu", "K řízení smĕru toku pracovní kapaliny v obvodu", "K akumulaci energie"], 1],
  [216, "Celek na obrázku lze nejlépe použít jako", ["jednočinný hydrogenerátor.", "dvojčinný hydrogenerátor.", "jednočinný hydromotor.", "dvojčinný hydromotor."], 3],
  [217, "Jaký celek je na obrázku?", ["jednočinný hydrogenerátor.", "dvojčinný hydrogenerátor.", "jednočinný hydromotor.", "dvojčinný hydromotor."], 3],
  [218, "Který prvek hydraulického systému má schématickou značku na obrázku?", ["Zpĕtný ventil", "Kulový kohout", "Škrtící klapka", "Dvoucestný rozvadĕč"], 0],
  [219, "Jaký druh hydrogenerátoru je na obrázku?", ["Radiální pístový", "Axiální pístový", "Rotační vřetenový", "Rotační lamelový"], 1],
  [220, "Jakou funkci má prvek na obrázku v hydrostatickém systému?", ["Zvyšování potenciální energie kapaliny", "Snižování kinetické energie kapaliny", "Hromadĕní tlakové energie kapaliny", "Regulace velikosti průtoku kapaliny"], 2],
  [221, "Který z uvedených druhů dopravníků se NEŘADÍ mezi dopravníky s tažným elementem?", ["Pásový dopravník", "Korečkový dopravník", "Podvĕsný dopravník", "Šnekový dopravník"], 3],
  [222, "Který z uvedených druhů dopravníků se řadí mezi dopravníky s tažným elementem?", ["Eskalátor", "Válečková trat'", "Vibrační dopravník", "Šnekový dopravník"], 0],
  [223, "Který z uvedených druhů dopravníků se jinak nazývá 'elevátor'?", ["Pohyblivé schodištĕ", "Korečkový dopravník", "Článkový dopravník", "Hřeblový dopravník"], 1],
  [224, "Který převod principiálnĕ pohání pásový dopravník?", ["Řemenový převod", "Řetĕzový převod", "Třecí převod", "Ozubený převod"], 0, 2],
  [225, "K jakému druh dopravy primárnĕ není určen pásový dopravník?", ["Ke kontinuální dopravĕ", "K horizontální dopravĕ", "K vertikální dopravĕ", "K šikmé dopravĕ"], 2],
  [226, "Kterým z tĕchto způsobů NELZE zvýšit dopravované množství materiálu pásovým dopravníkem?", ["Zvĕtšením ložné šířky pásu", "Víceválečkovou stolicí", "Zrychlením pohybu pásu", "Prodloužením délky pásu"], 3],
  [227, "Který buben u šikmého pásového dopravníku (doprava materiálu smĕrem nahoru) bude hnací?", ["Vždy ten výše položený", "Vždy ten níže položený", "Oba musí být hnací", "Nezáleží na tom, který bude hnací"], 0],
  [228, "Který druh válečků pod pásem NENALEZNEME u pásového dopravníku?", ["Vodící válečky", "Napínací válečky", "Podpůrné válečky", "Hnací válečky"], 3],
  [229, "Při výpočtu výkonu motoru pro pásový dopravník NENÍ nutné uvažovat ...", ["třecí síly.", "setrvačné síly.", "gravitační síly.", "elektromagnetické síly."], 3],
  [230, "K jakému druhu dopravy je primárnĕ určen korečkový dopravník?", ["K přerušované dopravĕ", "K horizontální dopravĕ", "K vertikální dopravĕ", "K osobní dopravĕ"], 2],
  [231, "Který z uvedených druhů dopravníků NENÍ vhodný pro přepravu sypkého materiálu?", ["Článkový dopravník", "Korečkový dopravník", "Redler", "Hřeblový dopravník"], 0],
  [232, "Který z uvedených druhů dopravníků je NEJMÉNĚ vhodný pro přepravu horkého materiálu?", ["Článkový dopravník", "Pásový dopravník", "Redler", "Hřeblový dopravník"], 1],
  [233, "Lze hřeblovými dopravníky a redlery dopravovat materiál horizontálnĕ, šikmo i vertikálnĕ?", ["Ano, obĕma je to možné.", "Ne, není to možné ani u jednoho.", "Lze to pouze redlery, jelikož mají uzavřenou konstrukci", "Lze to pouze hřeblovými dopravníky, jelikož mají otevřenou konstrukci"], 1],
  [234, "Kterému dopravníku je nejblíže princip fungování pohyblivého schodištĕ?", ["Elevátoru", "Článkového dopravníku", "Podvĕsnému dopravníku", "Pásového dopravníku"], 1],
  [235, "U kterého z uvedených dopravníků by NEMOHLO být tažným elementem lano?", ["Vozíkový dopravník", "Podvĕsný dopravník", "Pásový dopravník", "Článkový dopravník"], 2],
  [236, "Na obrázku je bĕžný pásový dopravník zobrazený bez samotného pásu. K čemu slouží váleček označený červenou šipkou?", ["Pro podporu pásu ve vratné vĕtvi", "Pro zvýšení úhlu opásání pásu na hnacím bubnu", "Pro napínání pásu po celé délce", "Pro vedení pásu v tažné vĕtvi"], 3],
  [237, "Jaký typ typ dopravníku s tažným elementem je na obrázku?", ["Korečkový", "Hřeblový", "Podvĕsný", "Nejedná se o dopravník s tažným elementem"], 1],
  [238, "S jakým typem dopravníku nejpravdĕpodobnĕji souvisí tato součást?", ["S elevátorem", "S redlerem", "S eskalátorem", "S válečkovou tratí"], 0],
  [239, "Pásový dopravník na obrázku má konstruktér v úmyslu umístit pod úhlem 20°. K jakému účelu slouží označená oblast a kde by mĕla být umístĕna?", ["Jedná se napínání pásu umístí se tudíž v nejvyšším možném místĕ", "Jedná se o pohon pásu umístí se tudíž v nejvyšším možném místĕ", "Jedná se napínání pásu umístí se tudíž v nejnižším možném místĕ", "Jedná se o pohon pásu umístí se tudíž v nejnižším možném místĕ"], 2],
  [240, "Jakým přízviskem by se dal nejlépe označit tento dopravník?", ["Článkový", "Pásový", "Podvĕsný", "Korečkový"], 0],
  [241, "Který z uvedených druhů dopravníků se NEŘADÍ mezi dopravníky bez tažného elementu?", ["Korečkový dopravník", "Válečková trat'", "Vibrační dopravník", "Šnekový dopravník"], 0],
  [242, "Který z uvedených druhů dopravníků se řadí mezi dopravníky bez tažného elementu?", ["Elevátor", "Pásový dopravník", "Hřeblový dopravník", "Šnekový dopravník"], 3],
  [243, "Kterým z tĕchto způsobů NELZE zvýšit dopravované množství materiálu šnekovým dopravníkem?", ["Zvýšením otáček šneku", "Zvĕtšením průmĕru šneku", "Zvĕtšením rozteče šnekovice", "Snížením hustoty dopravovaného materiálu"], 3],
  [244, "Ke kterému z uvedených druhů dopravy primárnĕ NESLOUŽÍ šnekový dopravník?", ["K horizontální dopravĕ", "K vertikální dopravĕ", "K šikmé dopravĕ", "Ke kontinuální dopravĕ"], 1],
  [245, "Jak se nazývá křivka, která tvoří šnek šnekového dopravníku?", ["Šroubovice", "Evolventa", "Cykloida", "Parabola"], 0],
  [246, "Lze naplnit dopravní žlab šnekového dopravníku na 100%?", ["Ano, zvýší se tím dopravní množství", "Ano, ale jen u nĕkterých dopravovaných materiálů", "Ne, došlo by k pĕchování dopravovaného materiálu, a to je nežádoucí", "Ano, ale pouze pokud je žlab uzavřený, aby nedocházelo k úniku přepravovaného materiálu mimo žlab"], 2],
  [247, "Který z tĕchto dopravníků bez tažného elementu nikdy nepotřebuje pro svoji funkci pohon?", ["Šnekový dopravník", "Dopravní žlab", "Válečková trat'", "Vibrační dopravník"], 1],
  [248, "Který z tĕchto dopravníků bez tažného elementu bude při pořízení pravdĕpodobnĕ nejlevnĕjší?", ["Šnekový dopravník", "Dopravní žlab", "Válečková trať", "Vibrační dopravník"], 1],
  [249, "Co je základní podmínkou pro to, aby mohl být přepravován materiál v dopravním žlabu?", ["Dostatečný náklon dopravního žlabu, aby bylo překonáno smykové tření", "Dostatečný náklon žlabu, aby byla překonána setrvačná síla", "Dostatečný výkon motoru", "Přepravovaný materiál musí mít při umístĕní do žlabu určitou počáteční rychlost"], 0],
  [250, "Jaký materiál lze přepravovat pomocí válečkové tratĕ?", ["Jakýkoliv", "Pouze sypké materiály", "Pouze materiály v kapalném stavu", "Pouze kusové materiály"], 3],
  [251, "Jak nemůže být přepravován materiál pomocí válečkové tratĕ?", ["Posouváním lidskou silou", "Samočinnĕ gravitací", "Pomocí pohonu válečků", "Překonáním setrvačné síly"], 3],
  [252, "Při rychlém pohybu vibračního dopravníku vzad (proti smĕru dopravy materiálu) je...", ["třecí síla vĕtší než setrvačná.", "setrvačná síla vĕtší než třecí.", "třecí síla vĕtší než gravitační.", "třecí síla nulová."], 1],
  [253, "Při pomalém pohybu vibračního dopravníku vpřed (ve smĕru dopravy materiálu) je...", ["třecí síla vĕtší než gravitační.", "setrvačná síla vĕtší než třecí.", "setrvačná síla menší než gravitační.", "třecí síla nulová."], 1],
  [254, "U pohánĕné válečkové tratĕ musí být pohánĕn ...", ["každý váleček.", "alespoň každý druhý váleček.", "alespoň každý třetí váleček.", "alespoň každý čtvrtý váleček."], 1],
  [255, "U kterého z tĕchto dopravníků bez tažného elementu haje nejmenší roli smykové tření?", ["Šnekový dopravník", "Dopravní žlab", "Válečková trať", "Vibrační dopravník"], 2],
  [256, "Jaký druh dopravníku bez tažného elementu je na obrázku?", ["Nejedná se o dopravník bez tažného elementu, ale s tažným elementem", "Vibrační", "Válečkový", "Šnekový"], 1],
  [257, "K dopravĕ jakého materiálu se nejlépe hodí šnekovice na obrázku?", ["Lepivého tekoucího materiálu", "Drobného kusového materiálu", "Hutnému sypkému materiálu", "Hustému plynnému materiálu"], 2],
  [258, "K jakému účelu slouží zakroužkovaná část na obrázku tohoto šnekového dopravníku?", ["Jako vstup dopravovaného materiálu do dopravníku", "Jako vstup potenciální energie do dopravníku", "Jako převod požadovaných otáček šnekovice do dopravníku", "Jako převod rotačního pohybu z motoru na posuvný pohyb šnekovice"], 2],
  [259, "Na obrázku je dopravník, u kterého lze upravit jeho celkovou délku. Jak Ize takový dopravník použít for dopravu kusového materiálu?", ["Jakkoliv dlouhý, ale vždy musí být sklonĕný pod určitým úhlem, a proto má nastavovací nohy.", "Musí být maximálnĕ tak dlouhý, aby přepravované kusy nepropadly mezi dvĕma sousedními válečky", "Dlouhý maximálnĕ tak, aby kusový materiál v jakémkoliv místĕ trasy ležel alespoň na třech válečcích", "Dlouhý tak, aby přepravovaný materiál mĕl délku maximálnĕ v délce rozteče dvou sousedních válečků"], 2],
  [260, "K jakému účelu je na tom dopravníku umístĕný označený motor s převodovkou?", ["Proto, aby roztočil válečky přes pomocný převod", "Proto, aby roztočil jediný váleček zhruba uprostřed dopravníku", "Proto, aby zajistil pohyb celého dopravníku při jeho přesouvání", "Proto, aby došlo k vibracím dopravníku a díky nim se materiál pohyboval"], 0],
  [261, "Existuje případ, kdy může do klece výtahu se zakázanou dopravou osob vstoupit osoba?", ["Ne, v žádném případĕ", "Ano, pokud se jedná o řidiče daného výtahu", "Ano, ale pouze u nĕkterých druhů a pokud je to nutné k nakládání", "Ano, ale pouze v případech daných zákonem, resp. ústavou ČR"], 2],
  [262, "Do které skupiny výtahů se podle normy řadí tzv. páternoster?", ["Výtahy pro dopravu osob", "Výtahy se zakázanou dopravou osob", "Nákladní výtahy", "Je samostatnou skupinou výtahů"], 3],
  [263, "Jaký druh zdvihadla je výtahový stroj, který zvedá a spouští klec?", ["Zvedák", "Kladkostroj", "Navíjedlo", "Visutá kočka"], 2],
  [264, "Jaký druh lan se nejčastĕji používá jako zvedací prostředky u výtahů?", ["Protismĕrnĕ vinutá ocelová lana", "Protismĕrnĕ vinutá konopná lana", "Stejnosmĕrnĕ vinutá ocelová lana", "Stejnosmĕrnĕ vinutá konopná lana"], 2],
  [265, "Jaký druh řetĕzů se nejčastĕji používá jako zvedací prostředky u výtahů?", ["Gallův řetĕz", "Ewartův řetĕz", "Válečkový řetĕz", "Zubový řetěz"], 0],
  [266, "Na co je nutné dát pozor při konstrukci uchycení kabiny výtahu?", ["Počet lan držící výtahovou klec je dán normou a tíhu výtahové klece je nezbytné rozdělit rovnomĕrnĕ na všechna lana", "Počet lan držící výtahovou klec je libovolný, ale tíhu výtahové klece je nezbytné rozdělit rovnomĕrnĕ na všechna lana", "Počet lan držící výtahovou klec je libovolný a tíhu výtahové klece Ize rozdělit různĕ na všechna lana", "Počet lan držící výtahovou klec je dán normou a tíhu výtahové klece Ize rozdělit různĕ na všechna lana"], 0],
  [267, "Co musí být v prostoru výtahu vedeno?", ["Jen kabina (klec)", "Jen protizávaží", "Klec i protizávaží", "Nemusí být vedena kabina ani protizávaží"], 2],
  [268, "Na jaký druh namáhání are namáhána lana?", ["Tah", "Tlak", "Krut", "Ohyb"], 0],
  [269, "Jak se nazývá prostor, ve kterém se pohybuje kabina výtahu?", ["Šachta", "Strojovna", "Závĕs", "Mezanin"], 0],
  [270, "Jakou hmotnost musí mít protizávaží?", ["Stejnou jako kabina výtahu", "Stejnou jako maximální nosnost kabiny výtahu", "Jako součet hmotnosti kabiny a půlky maximální nosnosti kabiny", "Jako součet maximální nosnosti a půlky hmotnosti kabiny výtahu"], 2],
  [271, "Na čem z uvedených NEZÁVISÍ volba výkonu elektromotoru pro pohon výtahu?", ["Na rychlosti pohybu kabiny výtahu", "Na maximální nosnosti kabiny výtahu", "Na tření ve výtahovém stroji (pohonném mechanismu)", "Na výšce zdvihu kabiny výtahu"], 3],
  [272, "Co z uvedených NENÍ součástí výtahové šachty?", ["Nárazníky", "Vodítka", "Zachycovače", "Armatury"], 3],
  [273, "Co NEPATŘÍ mezi nevýhody páternosteru?", ["Složitá konstrukce", "Nízká bezpečnost", "Malé dopravní rychlosti", "Nízká přepravní kapacita"], 3],
  [274, "K čemu obvykle slouží páternoster?", ["Ke kontinuální přepravĕ osob", "Ke kontinuální přepravĕ nákladů", "K přetržité dopravĕ osob", "K přetržité dopravĕ nákladů"], 0],
  [275, "Co NEPATŘÍ mezi výhody hydraulických výtahů?", ["Tichý chod", "Plynulá jízda kabiny výtahu", "Možnost různého umístĕní strojovny", "Vysoké dopravní rychlosti"], 3],
  [276, "Co spojuje celek na obrázku u výtahů?", ["Kabinu s vodícími lištami", "Kabinu s nosnými lany", "Lana s pohonným bubnem", "Lana s výtahovou šachtou"], 1],
  [277, "Jak se nazývá výtah, jehož zjednodušené schéma a reálná podoba je na obrázku?", ["Obĕžný", "Stolový", "Výsypný", "Hydraulický"], 0],
  [278, "Na obrázku je lano vhodné pro nesení výtahové klece. Jak se nazývá jeho část označený šipkou?", ["Pramen", "Drát", "Duše", "Lanovice"], 2],
  [279, "Jak se nazývá zařízení výtahu na obrázku?", ["Vodítko", "Závĕs", "Nárazník", "Zachycovač"], 3],
  [280, "Jak se nazývá zařízení na obrázku v souvislosti s výtahy?", ["Omezovač", "Protizávaží", "Nárazník", "Zachycovač"], 2],
  [281, "Co se rozumí pojmem 'vyložení jeřábu'?", ["Maximální výška, do které lze břemeno jeřábem zvednout", "Maximální vzdálenost mezi zvedaným břemenem a hlavní osou jeřábu", "Maximální hmotnost břemene, kterou lze jeřábem zvednout", "Maximální úhel, o který se může jeřáb s břemenem otočit"], 1],
  [282, "Co se rozumí pojmem 'klopný moment'?", ["Síla [N], která se snaží při transportu břemene naklápĕt jeřáb", "Okamžik [s], při kterém dojde k překlopení jeřábu", "Vzdálenost [m], do které se nesmí břemeno dostał od místa zakotvení jeřábu", "Moment [N.m], který vyjadřuje míru stability jeřábu"], 3],
  [283, "Do které z tĕchto kategorií lze zařadit mostový jeřáb", ["Vĕžové jeřáby", "Mobilní jeřáby", "Skladové jeřáby", "Sloupové jeřáby"], 2],
  [284, "Čím se vyznačuje vĕžový jeřáb?", ["Nosná konstrukce je příhradová", "Celková konstrukce má tvar brány", "Nosnou konstrukcí je masivní otočný sloup", "Jeřáb má velmi malé rozmĕry"], 0],
  [285, "Prolamovaný profil nosné konstrukce jeřábu vznikne tak, dojde k úpravĕ válcovaného ocelového profilu nejčastĕji tvaru", ["U", "L", "T", "I"], 3],
  [286, "Zdvihací ústrojí jeřábu je kombinací", ["kladkostroje a zvedáku.", "zvedáku a navíjedla.", "navíjedla a kladkostroje.", "zvedáku a visuté kočky."], 2],
  [287, "Který ze zmínĕných parametrů NENÍ nutné zohlednit při návrhu elektromotoru pro zdvíhací zařízení jeřábu?", ["Nosnost jeřábu", "Hmotnost háku jeřábu", "Rychlost zvedání břemene", "Vyložení jeřábu"], 3],
  [288, "Na kterém z uvedených parametrů NEZÁVISÍ rychlost zdvihání břemene jeřábem?", ["Otáčky elektromotoru", "Celkový převodový pomĕr zdvihacího ústrojí", "Průmĕr lanového bubnu", "Vyložení jeřábu"], 3],
  [289, "Která z uvedených možností se NEPOUŽÍVÁ jako zdvíhací prostředek u jeřábů?", ["Textilní lana", "Ocelová lana", "Řetĕzy", "Řemeny"], 3],
  [290, "Který z uvedených názvů NEOZNAČUJE název ocelového lana?", ["Seal", "Warrington", "Herkules", "Henry"], 3],
  [291, "Který z uvedených typů řetĕzů se NEPOUŽÍVÁ u jeřábů jako zvedací prostředek?", ["Článkové řetĕzy", "Fleyerovy řetĕzy", "Gallovy řetĕzy", "Pouzdrové řetĕzy"], 3],
  [292, "Který z nabízených uchopovacích prostředků drží transportované tĕleso pomocí smykového tření?", ["Dvojitý hák", "Lamelový hák", "Břemenové kleštĕ", "Elektromagnet"], 2],
  [293, "Na jaký druh namáhání (z nabízených možností) se kontrolují pojezdové kolejnice for pojezd jeřábů?", ["Krut", "Otlačení", "Tah", "Střih"], 1],
  [294, "Co NEPATŘÍ mezi výhody textilních lan jako zvedacích prostředků u jeřábů?", ["Nízká hmotnost", "Tichý provoz", "Pružnost", "Odolnost vůči otĕru"], 3],
  [295, "Jakým převodem je nejčastĕji realizován mechanismu otáčení jeřábu kolem své osy?", ["Retĕzovým", "Řemenovým", "Ozubeným", "Třecím"], 2],
  [296, "Jaký typ typický druh jeřábu je na obrázku?", ["Vĕžový", "Sloupový", "Portálový", "Mostový"], 2],
  [297, "Jakým způsobem je primárnĕ namáhán označený profil (červeně vyznačený) na obrázku při zvedání břemene tímto sloupovým jeřábem?", ["Na tah", "Na ohyb", "Na krut", "Na střih"], 0],
  [298, "Jak se nazývá konstrukce, ze které je vyroben výložník tohoto jeřábu?", ["Prolamovaná", "Příhradová", "Pilířová", "Převislá"], 1],
  [299, "Jakým slovem by se nejlépe dal označit prostředek na obrázku for uchopování břemen jeřábů?", ["Drapák", "Vidle", "Hák", "Kleštĕ"], 3],
  [300, "Jak se nazývá (označené) červené zařízení na obrázku?", ["Kladkostroj", "Navíjedlo", "Výložník", "Visutá kočka"], 0],
  [301, "Co je to pístové čerpadlo?", ["Hnací pístový stroj sloužící pro dopravu kapalin", "Hnaný pístový stroj sloužící pro dopravu kapalin", "Hnací pístový stroj sloužící pro dopravu plynů", "Hnaný pístový stroj sloužící pro dopravu plynů"], 1],
  [302, "Kterému rovinnému obrazci se nejvíce podobá teoretický pracovní digram jednočinného pístového čerpadla?", ["Obdélníku", "Kosodélníku", "Lichobĕžníku", "Trojúhelníku"], 0],
  [303, "Následující informace popisují fázi sání u jednočinného pístového čerpadla. Která informace NENÍ pravdivá?", ["Píst se pohybuje z horní úvratĕ do dolní.", "Zmenšuje se pracovní prostor čerpadla.", "V pracovním prostoru čerpadla vzniká podtlak.", "Sací ventil je otevřený a výtlačný uzavřený."], 1],
  [304, "Následující informace popisují fázi výtlaku u jednočinného pístového čerpadla. Která informace NENÍ pravdivá?", ["Píst se pohybuje z dolní úvratĕ do horní.", "Zmenšuje se pracovní prostor čerpadla.", "V pracovním prostoru čerpadla vzniká podtlak.", "Výtlačný ventil je otevřený a sací uzavřený."], 2],
  [305, "Na kterém z uvedených parametrů NEZÁVISÍ výkon motoru pístového čerpadla?", ["Geodetická dopravní výška", "Požadovaný objemový průtok", "Druh čerpané kapaliny", "Kompresní pomĕr mechanismu"], 3],
  [306, "Které z uvedených druhů čerpadel má nejménĕ rovnomĕrný výtok čerpané kapaliny?", ["Jednočinné čerpadlo", "Dvojčinné čerpadlo", "Diferenciální čerpadlo", "Křídlové čerpadlo"], 0],
  [307, "Které z uvedených druhů čerpadel má nejrovnomĕrnĕjší výtok čerpané kapaliny?", ["Jednočinné čerpadlo", "Zdvižné čerpadlo", "Diferenciální čerpadlo", "Membránové čerpadlo"], 2],
  [308, "U kterého z uvedených druhů pístových čerpadel Ize použít zkrácený klikový mechanismus?", ["Jednočinné čerpadlo", "Dvojčinné čerpadlo", "Diferenciální čerpadlo", "Zdvižné čerpadlo"], 2],
  [309, "Jak se jmenuje součást pístových čerpadel, která pomáhá zmenšit pulzování tlaku v kapalinĕ?", ["Vzdušník", "Ventil", "Píst", "Křižák"], 0],
  [310, "U kterého z uvedených druhů pístových čerpadel NEDOCHÁZÍ k sání pouze při jednom pohybu pístu?", ["Jednočinné čerpadlo", "Dvojčinné čerpadlo", "Diferenciální čerpadlo", "Zdvižné čerpadlo"], 1],
  [311, "U kterého z uvedených druhů pístových čerpadel se nachází ventily přímo v pístu?", ["Jednočinné čerpadlo", "Dvojčinné čerpadlo", "Diferenciální čerpadlo", "Zdvižné čerpadlo"], 3],
  [312, "U kterého z tĕchto druhů pístových čerpadel NEDOCHÁZÍ alespoň při jednom pohybu pístu zároveň k sání i výtlaku?", ["Jednočinné čerpadlo", "Dvojčinné čerpadlo", "Diferenciální čerpadlo", "Zdvižné čerpadlo"], 0],
  [313, "Na kterém z tĕchto parametrů NEZÁVISÍ rychlost zavírání ventilů pístových čerpadel?", ["Otáčky motoru čerpadla", "Výška zdvihu ventilu", "Síla pružiny ventilu", "Účinnost čerpadla"], 3],
  [314, "Jaký hydraulický prvek z uvedených je obvykle umístĕn v sacím koši na počátku sacího potrubí čerpadla?", ["Redukční ventil", "Zpĕtný ventil", "Rozvadĕč", "Hydromotor"], 1],
  [315, "Jak se nazývá druh pístu pístových čerpadel válcového tvaru, který se vyznačuje tím, že je jeho délka vĕtší než průmĕr?", ["Kotoučový píst", "Trubkový píst", "Plunžrový píst", "Trojhranný píst"], 2],
  [316, "Na obrázku je (ideální) pracovní p-V diagram pístového čerpadla. Jak se nazývá fáze, která nastává z bodu 3 do bodu 4?", ["Izochorické sání", "Izobarické sání", "Izobarický výtlak", "Izochorický výtlak"], 2],
  [317, "Na obrázku je (ideální) pracovní p-V diagram pístového čerpadla. Ve kterých dvĕma bodech diagramu se píst nachází v dolní úvrati?", ["1 a 2", "2 a 3", "3 a 4", "1 a 4"], 1],
  [318, "Jaké typické pístové čerpadlo je na obrázku?", ["Diferenciální", "Vačkové", "Zdvižné", "Křídlové"], 3],
  [319, "Na obrázku je obecné schéma čerpací soustavy. Jak velká je celková 'manometrická' dopravní výška?", ["Přesnĕ jako kóta 'A'", "Přesnĕ jako kóta 'C'", "V rozmezí kót 'A' a 'C'", "Vĕtší než kóta 'A'"], 3],
  [320, "Jak se nazývá součást související s pístovými čerpadly na obrázku?", ["Vzdušník", "Křižák", "Sací koš", "Sací ventil"], 0],
  [321, "Co je to kompresor?", ["Hnací pístový stroj sloužící pro dopravu kapalin", "Hnaný pístový stroj sloužící pro dopravu kapalin", "Hnací pístový stroj sloužící pro dopravu plynů", "Hnaný pístový stroj sloužící pro dopravu plynů"], 3],
  [322, "Následující informace popisují fázi komprese u pístového kompresoru. Která informace NENÍ pravdivá?", ["Píst se pohybuje z dolní úvratĕ do horní.", "Sací i výtlačný ventil je uzavřený.", "V pracovním prostoru vzniká přetlak.", "Zvĕtšuje se pracovní prostor."], 3],
  [323, "Následující informace popisují fázi expanze u pístového kompresoru. Která informace NENÍ pravdivá?", ["Píst se pohybuje z dolní úvratĕ do horní.", "Sací i výtlačný ventil je uzavřený.", "Fáze probíhá teoreticky podle adiabatického dĕje.", "Zvĕtšuje se pracovní prostor."], 0],
  [324, "Následující informace popisují fázi výtlaku u pístového kompresoru. Která informace NENÍ pravdivá?", ["Píst se pohybuje z dolní úvratĕ do horní.", "Sací i výtlačný ventil je otevřený.", "Fáze probíhá teoreticky podle izobarického dĕje.", "Zmenšuje se pracovní prostor."], 1],
  [325, "Následující informace popisují fázi sání u pístového kompresoru. Která informace NENÍ pravdivá?", ["Píst se pohybuje z horní úvratĕ do dolní.", "Výtlačný ventil je uzavřený.", "Fáze probíhá teoreticky podle izochorického dĕje.", "Zvĕtšuje se pracovní prostor."], 2],
  [326, "Co se rozumí pojmem 'kompresní pomĕr'?", ["Podíl počátečního a konečného objemu plynu při jeho stlačování", "Podíl počátečního a konečného tlaku plynu při jeho stlačování", "Podíl počáteční a konečné teploty plynu při jeho stlačování", "Podíl počáteční a konečné hustoty plynu při jeho stlačování"], 1],
  [327, "Čeho NELZE dosáhnout pomocí vícestupňové komprese?", ["Nižší teploty plynu na konci komprese", "Vyšší objemové účinnosti kompresoru", "Ušetření potřebné práce for stlačování", "Vysokého sacího tlaku do prvního stupnĕ"], 3],
  [328, "Co je řazené mezi jednotlivými stupni při vícestupňové kompresi?", ["Chladič", "Dmychadlo", "Vývĕva", "Expandér"], 0],
  [329, "Při vícestupňové kompresi: Jaké parametry bude mít plyn na vstupu do druhého stupnĕ oproti výstupu z prvního stupnĕ?", ["Bude mít stejnou teplotu, tlak i objem", "Bude mít stejný objem, ale nižší teplotu a tlak", "Bude mít nižší tlak, teplotu i objem", "Bude mít vyšší tlak, teplotu i objem"], 2],
  [330, "Jak se nazývají ventily, které are nejčastĕji používány u pístových kompresorů?", ["Membránové ventily", "Destíčkové ventily", "Sedlové ventily", "Talířové ventily"], 1],
  [331, "Kterým z tĕchto zařízení NELZE regulovat činnost kompresoru, resp. tlak a průtok plynu na výtlaku?", ["Vzdušníkem", "Pojistným ventilem", "Samotným kompresorem", "Zpĕtným ventilem"], 3],
  [332, "Jak se nazývá zařízení, kterým se mĕní velikost škodlivého pracovního prostoru pístového kompresoru?", ["Reduktor", "Reflektor", "Reaktor", "Restriktor"], 0],
  [333, "Kterou z tĕchto činností NELZE regulovat činnost pístového kompresoru?", ["Vhodným ovládáním sacího ventilu", "Zmĕnou otáček kompresoru", "Přepouštĕním vytlačovaného plynu do sání", "Chlazením klikového mechanismu"], 3],
  [334, "Jakou funkci NEMÁ přívod oleje ke klikovému mechanismu pístového kompresoru?", ["Mazání kompresoru", "Chlazení kompresoru", "Odvod odrolených částí materiálů", "Regulace chodu kompresoru"], 3],
  [335, "Jak se jmenuje 'kompresor s rotačním pohybem pístu', který se často používá k přeplňování spalovacích motorů?", ["Rootsovo dmychadlo", "Vodokružná vývĕva", "Spirálový kompresor", "Kompresor s krouživým pohybem pístu"], 0],
  [336, "Na obrázku je teoretický pracovní p-V diagram pístového kompresoru. Jak se nazývá fáze, která nastává z bodu 2 do bodu 3?", ["Adiabatická komprese", "Izochorická komprese", "Adiabatická expanze", "Izochorická expanze"], 0],
  [337, "Na obrázku je (tlustou černou čarou nakreslený) skutečný pracovní p-V diagram pístového kompresoru. Co se dĕje bĕhem červenĕ zakroužkované fáze?", ["Pracovní médium je v pracovním prostoru kompresoru a je stlačováno", "Pracovní médium je v pracovním prostoru kompresoru a expanduje", "Pracovní médium se dostává z pracovního prostoru kompresoru", "Pracovní médium se dostává do pracovního prostoru kompresoru"], 3],
  [338, "Jak se jmenuje přístroj ke stlačování plynu na obrázku?", ["Pístový turbokompresor", "Spirálový kompresor", "Vodokružná vývĕva", "Rootsovo dmychadlo"], 3],
  [339, "Na obrázku je typický pístový kompresor. Jak se nazývá červená součást, která je jeho součástí?", ["Reaktor", "Vývĕva", "Vzdušník", "Boiler"], 2],
  [340, "Jak by se dala nejlépe pojmenovat součást související s pístovými kompresory na obrázku?", ["Píst kompresoru", "Destíčkový ventil", "Reduktor tlaku", "Hlava válce"], 1],
  [341, "Co je to zážehový spalovací motor?", ["Tepelný hnací pístový stroj", "Tepelný hnaný pístový stroj", "Tepelný hnací lopatkový stroj", "Tepelný hnaný lopatkový stroj"], 0],
  [342, "Jak se nazývá zážehový spalovací motor, jehož píst koná rotační pohyb?", ["Stirlingův motor", "Wankelův motor", "Vznĕtový motor", "Krokový motor"], 1],
  [343, "Bĕhem kolika otáček klikové hřídele probĕhne jeden pracovní cyklus dvoudobého zážehového spalovacího motoru?", ["Bĕhem 1 otáčky klikové hřídele", "Bĕhem 2 otáček klikové hřídele", "Bĕhem 3 otáček klikové hřídele", "Bĕhem 4 otáček klikové hřídele"], 0],
  [344, "Jak se jinak nazývá uspořádání válců 'boxer' spalovacího motoru?", ["Řadové uspořádání", "Vidlicové uspořádání", "Hvĕzdicové uspořádání", "Uspořádání s protibĕžnými písty"], 3],
  [345, "Následující informace popisují fázi zážehu u čtyřdobého zážehového spalovacího motoru. Která informace NENÍ pravdivá?", ["K zážehu dochází samovznícením", "K zážehu dochází, když je píst před horní úvratí", "Zažehává se smĕr vzduchu s benzínem", "Po zážehu prudce vzrůstá tlak ve válci"], 0],
  [346, "Jaká z následujících podmínek NEPLATÍ for vytvoření ideálního (teoretického) pracovního diagramu zážehového spalovacího motoru?", ["Dochází k výmĕnĕ obsahu válce", "Přívod a odvod tepla nastává za konstantních podmínek", "Termodynamické dĕje probíhají dle dĕjů ideálního plynu", "Klikový mechanismus pracuje bez tření"], 0],
  [347, "Jaké je přibližnĕ účinnost čtyřdobého zážehového spalovacího motoru?", ["10%", "30%", "50%", "70%"], 1],
  [348, "Který z tĕchto parametrů NENÍ nutné mĕřit při určování 'mĕrné spotřeby paliva' spalovacího motoru?", ["Hmotnost spotřebovaného paliva", "Výkon spalovacího motoru", "Doba bĕhu (práce) spalovacího motoru", "Hustotu dodávaného paliva"], 3],
  [349, "Jak se nazývá mechanismu, který ovládá činnost ventilů spalovacího motoru?", ["Rozvodový mechanismu", "Klikový mechanismus", "Kulisový mechanismu", "Šroubový mechanismus"], 0],
  [350, "Ve kterém technickém detailu z uvedených není podstatný rozdíl mezi dvoudobým a čtyřdobým zážehovým spalovacím motorem?", ["V rozvodovém mechanismu", "V pracovním prostoru", "V pracovním cyklu", "Ve způsobu zapalování"], 3],
  [351, "Co NEPATŘÍ mezi nevýhody dvoudobých zážehových spalovacích motorů (oproti čtyřdobým zážehovým)?", ["Nižší účinnost", "Vyšší spotřeba paliva", "Nižší výkon", "Vyšší emise"], 2],
  [352, "Jakou veličinu vyjadřuje plocha (obsah) ohraničená skutečným pracovním diagramem dvoudobého zážehového motoru?", ["Maximální výkon motoru", "Užitečnou práci motoru", "Skutečnou účinnost motoru", "Mĕrnou spotřeba paliva"], 1],
  [353, "Pokud se palivo (benzín) dostává do sacího potrubí před škrtící klapkou pomocí přetlaku, pak hovoříme o ...", ["karburátoru.", "jednobodovém nepřímém vstřikování.", "vícebodovém nepřímém vstřikování.", "přímém vstřikování."], 1],
  [354, "Která součást z uvedených NENÍ součástí ventilového rozvodu OHC?", ["Vratná pružina", "Vahadlo", "Vačková hřídel", "Rozvodová tyč"], 3],
  [355, "Během které fáze pracovního cyklu čtyřdobého zážehového spalovacího motoru koná motor práci?", ["Během sání", "Během komprese", "Během expanze", "Během výfuku"], 2],
  [356, "Na obrázku je ideální pracovní p-V diagram zážehového motoru. Jak se nazývá fáze, která nastává z bodu 4 do bodu 1?", ["Adiabatická komprese", "Adiabatická expanze", "Izochorický přívod tepla", "Izochorický odvod tepla"], 3],
  [357, "Na obrázku je skutečný pracovní p-V diagram dvoudobého zážehového motoru. Ve kterém z červenĕ označených bodů dochází k zážehu (vytvoření jiskry svíčkou)?", ["A", "B", "C", "D"], 1],
  [358, "Jak se nazývá motor (uspořádání motoru), pokud jsou písty umístĕny tak, jak je vidĕt na obrázku?", ["Hvĕzdicový", "Boxer", "Vidlicový", "Wankelův"], 1],
  [359, "Jak se nazývá celek na obrázku?", ["Karburátor", "Vahadlo", "Setrvačník", "Ojnice"], 0],
  [360, "Kterou písmennou zkratkou by se dal nejlépe označiť rozvodový mechanismu motoru na obrázku?", ["SV", "OHV", "SOHC", "DOHC"], 2],
  [361, "Bĕhem kolika otáček klikové hřídele probĕhne jeden pracovní cyklus čtyřdobého vznĕtového spalovacího motoru?", ["Bĕhem 1 otáčky klikové hřídele", "Bĕhem 2 otáček klikové hřídele", "Bĕhem 3 otáček klikové hřídele", "Bĕhem 4 otáček klikové hřídele"], 1],
  [362, "Co se nachází ve válci čtyřdobého vznĕtového motoru na začátku kompresní fáze?", ["Pouze vzduch", "Pouze nafta", "Pouze benzín", "Smĕs paliva se vzduchem"], 0],
  [363, "Následující informace popisují fázi vstřiku paliva u čtyřdobého vznĕtového spalovacího motoru. Která informace NENÍ pravdivá?", ["Palivo se vstřikuje do vzduchu o vysoké teplotĕ", "K vstříknutí paliva dochází, když je píst přesnĕ v horní úvratí", "Palivo se vstřikuje do silnĕ stlačeného vzduchu", "Po vstříknutí paliva postupnĕ prudce vzrůstá tlak ve válci"], 1],
  [364, "Jaká z následujících podmínek platí for vytvoření skutečného pracovního diagramu zážehového spalovacího motoru?", ["Zjišťuje se pomocí složitých výpočtů", "Přívod a odvod tepla nastává za konstantních podmínek", "Kompresní a expanzní fáze probíhají podle polytropického dĕje", "Klikový mechanismus nepracuje s reálnými ztrátami"], 2],
  [365, "Jaké je přibližnĕ maximální účinnost čtyřdobého vznĕtového spalovacího motoru?", ["20%", "30%", "40%", "50%"], 2],
  [366, "Co NEPATŘÍ mezi výhody vznĕtových spalovacích motorů v porovnání s motory zážehovými?", ["Nižší hlučnost", "Nižší spotřeba paliva", "Vyšší účinnost", "Vyšší efektivní výkon"], 0],
  [367, "Co rozumíme pojmem 'kompresní pomĕr'?", ["Podíl mezi maximálním a minimálním objemem válce motoru", "Podíl mezi maximálním a minimálním tlakem ve válci motoru", "Podíl mezi množstvím vzduchu a paliva dopravovaného do válce motoru", "Podíl mezi maximální a minimální teplotou ve válci motoru"], 0],
  [368, "Jaký dĕj ideálního plynu popisuje odvod tepla z pracovního prostoru motoru?", ["Izotermický dĕj", "Izobarický dĕj", "Izochorický dĕj", "Adiabatický dĕj"], 2],
  [369, "Která součást z uvedených NENÍ součástí ventilového rozvodu SV?", ["Vratná pružina", "Vahadlo", "Vačková hřídel", "Zdvihátko"], 1],
  [370, "Jaké jsou otáčky vačkové hřídele rozvodového mechanismu v porovnání s otáčkami klikové hřídele u čtyřdobého vznĕtového spalovacího motoru?", ["Vačková hřídel se otáčí dvakrát rychleji než kliková hřídel", "Kliková hřídel se otáčí dvakrát rychleji než vačková hřídel", "Vačková hřídel se otáčí stejnĕ rychle jako kliková hřídel", "Kliková hřídel se otáčí čtyřikrát rychleji než vačková hřídel"], 1],
  [371, "Co NEPATŘÍ (v porovnání s ostatními druhy) mezi nevýhody ventilového rozvodu s visutými ventily (OHV)?", ["Špatný tvar spalovacího prostoru", "Velký počet součástí", "Vyšší hlučnost", "Nesprávné chování mechanismu při vyšších otáčkách motoru"], 0],
  [372, "Který z tĕchto parametrů NENÍ důležitý pro výpočet průmĕru pístu (hlavního rozmĕru klikového mechanismu spalovacího motoru)?", ["Efektivní výkon motoru", "Tlak ve válci motoru", "Způsob činnosti (dvoudobý nebo čtyřdobý)", "Teplota výfukových plynů"], 3],
  [373, "Kam NEMŮŽE být vstříknuto palivo u vznĕtových spalovacích motorů?", ["Do spalovacího prostoru", "Do speciálního prostoru vytvořeného v pístu", "Do speciálního prostoru vytvořeného v hlavĕ válců", "Do sacího potrubí"], 3],
  [374, "Co NEPATŘÍ mezi výhody nepřímého vstřikování u vznĕtových spalovacích motorů?", ["Nižší vstřikovací tlaky", "Menší nároky na jakost paliva", "Tišší chod motoru", "Vyšší účinnost motoru"], 3],
  [375, "Kterou z tĕchto vad by NEZPŮSOBILO špatné chlazení spalovacích motorů?", ["Korozi kovových částí motoru", "Nadmĕrné opotřebení pohyblivých součástí motoru", "Nežádoucí spalování oleje", "Zmĕny tvaru funkčních součástí motoru"], 0],
  [376, "Na obrázku je ideální pracovní p-V diagram vznĕtového motoru. Jak se nazývá fáze, která nastává z bodu 5 do bodu 1?", ["Izotropické sání", "Adiabatická komprese", "Izochorická expanze", "Izobarický výfuk"], 1],
  [377, "Na obrázku je skutečný pracovní p-V diagram čtyřdobého vznĕtového motoru. Ve kterém z červenĕ označených bodů dochází k zavření výfukového ventilu?", ["A", "B", "C", "D"], 2],
  [378, "Z jakého motoru je píst na obrázku?", ["Z dvoudobého zážehového motoru s přímým vstřikováním", "Z čtyřdobého vznĕtového motoru s přímým vstřikováním", "Z čtyřdobého vznĕtového motoru s nepřímým vstřikováním", "Z čtyřdobého zážehového motoru s nepřímým vstřikováním"], 1],
  [379, "K jakému účelu slouží u motoru tento celek?", ["K přeplňování", "K chlazení", "K mazání", "K spalování"], 0],
  [380, "Jak se nazývá součást na obrázku?", ["Katalyzátor výfukových plynů", "Lambda sonda", "Sací ventil", "Vstřikovač paliva"], 3],
  [381, "K jaké přemĕnĕ energie dochází v rotoru odstředivých čerpadel?", ["Mechanická energie se mĕní na kinetickou a tlakovou", "Kinetická energie se mĕní na tlakovou", "Mechanická energie se mĕní na potenciální", "Tlaková energie se mĕní na kinetickou a mechanickou"], 0],
  [382, "Jak se mĕní energie kapaliny v difuzoru odstředivého čerpadla?", ["Zvyšuje se kinetická a tlaková energie kapaliny", "Zvyšuje se kinetická energie kapaliny, ale snižuje se její tlaková energie", "Zvyšuje se tlaková energie kapaliny, ale snižuje se její kinetická energie", "Snižily se kinetická i tlaková energie kapaliny"], 2],
  [383, "Co je to odstředivé čerpadlo?", ["Hnaný hydrodynamický lopatkový stroj", "Hnací hydrodynamický lopatkový stroj", "Hnaný hydrostatický pístový stroj", "Hnací hydrostatický pístový stroj"], 0],
  [384, "Co NEPATŘÍ mezi výhody odstředivých čerpadel (oproti pístovým čerpadlům)?", ["Malý počet pohyblivých dílů", "Menší celkové rozmĕrs", "Vyšší účinnost", "Není vždy nutné pro jejich pohon použít převodovku"], 2],
  [385, "Jakým smĕrem vstupuje kapalina do rotoru všech odstředivých čerpadel?", ["Rovnobĕžnĕ s osou rotoru", "Kolmo k ose rotoru", "Šikmo k ose rotoru", "Mimobĕžnĕ k ose rotoru"], 0],
  [386, "Jakým smĕrem vystupuje kapalina z rotoru radiálního odstředivého čerpadla?", ["Rovnobĕžnĕ s osou rotoru", "Kolmo k ose rotoru", "Šikmo k ose rotoru", "Mimobĕžnĕ k ose rotoru"], 1],
  [387, "Jakou rychlost udává kapalinĕ obvodová rychlost obĕžného kola (rotoru)?", ["Unášivou rychlost", "Relativní rychlost", "Absolutní rychlost", "Dynamickou rychlost"], 0],
  [388, "Které z tĕchto odstředivých čerpadel by se nejpravdĕpodobnĕji použilo for velké průtoky při dopravĕ kapalin?", ["Radiální čerpadlo", "Axiální čerpadlo", "Diagonální čerpadlo", "Vířivé čerpadlo"], 1],
  [389, "Proč má lopatka vrtulového kola smĕrem od středu vrtule (rotoru) stále menší sklon?", ["Kvůli zvĕtšující se obvodové rychlosti", "Kvůli zvĕtšující se absolutní rychlosti", "Kvůli zmenšující se obvodové rychlosti", "Kvůli zmenšující se absolutní rychlosti"], 0],
  [390, "Jakou funkci má v konstrukci radiálního odstředivého čerpadla tzv. lucerna?", ["Spojuje hydraulickou a mechanickou část stroje", "Spojuje hydraulickou a ucpávkovou část stroje", "Spojuje mechanickou a ucpávkovou část stroje", "Slouží k osvĕtlení čerpadla"], 0],
  [391, "Jaká je jednotka veličiny 'mĕrná energie'?", ["J.kg⁻¹", "J.m⁻³", "J.s⁻¹", "J.m⁻¹"], 0],
  [392, "Jaký počet lopatek má obvykle (nejčastĕji) vrtulové kolo axiálního odstředivého čerpadla?", ["2 až 4", "5 až 6", "7 až 10", "více než 10"], 0],
  [393, "Který z tĕchto parametrů je nejdůležitĕjší for to, do jaké výšky dané odstředivé čerpadlo dokáže čerpat kapalinu?", ["Otáčky rotoru", "Objemový průtok", "Mĕrná energie", "Hydraulická účinnost"], 2],
  [394, "Jak se nazývá jev, při kterém v kapalinĕ vzniklé vzduchové dutiny implodují (vyplňují se vodou), čímž dochází k rázům způsobující rozrušování materiálů různých částí odstředivých čerpadel?", ["Kapitace", "Karence", "Kadence", "Kavitace"], 3],
  [395, "Který parametr NENÍ potřebný pro výpočet výkonu motoru odstředivého čerpadla?", ["Množství čerpané kapaliny", "Hustota čerpané kapaliny", "Mĕrná energie předávaná rotorem", "Otáčky rotoru"], 3],
  [396, "Jak se nazývá součást na obrázku?", ["Difuzor", "Vířidlo", "Lucerna", "Ucpávka"], 0],
  [397, "Z jakého typu odstředivého čerpadla je obĕžné kolo na obrázku a jakým smĕrem se otáčí (z pohledu tohoto obrázku) při čerpání kapaliny?", ["Z radiálního čerpadla a točí se po smĕru hodinových ručiček", "Z radiálního čerpadla a točí se proti smĕru hodinových ručiček", "Z axiálního čerpadla a točí se po smĕru hodinových ručiček", "Z axiálního čerpadla a točí se proti smĕru hodinových ručiček"], 1],
  [398, "Pro jaké průtoky a dodané (mĕrné) energie kapalinĕ are nejvhodnĕjší tato obĕžná kola čerpadel?", ["Pro malé průtoky a malé mĕrné energie", "Pro velké průtoky a velké mĕrné energie", "Pro malé průtoky a velké mĕrné energie", "Pro velké průtoky a malé mĕrné energie"], 3],
  [399, "Na obrázku are rychlostní trojúhelníky radiálního obĕžného kola hydrodynamického čerpadla... Které dvĕ rychlosti by se daly nazvat jako 'unášivé'?", ["'b' a 'd'", "'a' a 'f'", "'c' a 'e'", "Unášivé rychlosti se na obrázku nenachází"], 1],
  [400, "Na obrázku je čtvrtinový řez typického provedení radiálního hydrodynamického čerpadla. Co se nachází v zakroužkované oblasti?", ["Unašeč", "Ložisko", "Ucpávka", "Difuzor"], 2],
  [401, "K jaké přemĕnĕ energie dochází ve vodních turbínách?", ["Z mechanické na kinetickou a tlakovou", "Z kinetické a tlakové na mechanickou", "Z kinetické a tlakové na potenciální", "Z potenciální na kinetickou a tlakovou"], 1],
  [402, "Pokud má vodní dílo spád 40 m, pak se s nejvĕtší pravdĕpodobností jedná o vodní dílo ...", ["nízkotlaké.", "středotlaké.", "vysokotlaké.", "přečerpávací."], 1],
  [403, "K čemu ve vodních dílech slouží tzv. česlo?", ["Čistĕní vody (hrubé)", "Zastavení průtoku", "Odvod přebytečné vody", "Demineralizace vody"], 0],
  [404, "Který druh vodní turbíny NENÍ vhodné použít v nízkotlakých vodních dĕlech?", ["Francisova turbína", "Kaplanova turbína", "Bánkiho turbína", "Peltonova turbína"], 3],
  [405, "Které vodní dílo se v České republice nenachází?", ["Nízkotlaké vodní dílo", "Středotlaké vodní dílo", "Vysokotlaké vodní dílo", "Přečerpávací vodní dílo"], 2],
  [406, "U kterého druhu vodního díla (vodní elektrárny) dochází ve výsledku ke ztrátĕ energie (a ne k jejímu získání) ?", ["Nízkotlaké vodní dílo", "Středotlaké vodní dílo", "Vysokotlaké vodní dílo", "Přečerpávací vodní dílo"], 3],
  [407, "Který druh turbíny je nejvíce vhodný pro všechny typy vodních dĕl?", ["Francisova turbína", "Kaplanova turbína", "Peltonova turbína", "Dériazova turbína"], 0],
  [408, "Který druh turbíny se neřadí mezi turbíny přetlakové?", ["Francisova turbína", "Kaplanova turbína", "Peltonova turbína", "Dériazova turbína"], 2],
  [409, "Pouze jakou energii dokáže zpracovávat rovnotlaká vodní turbína?", ["Kinetická energie", "Potenciální energie", "Tlaková energie", "Mechanická energie"], 0],
  [410, "Co se dĕje s tlakovou a kinetickou energií v trysce před rovnotlakou vodní turbínou?", ["Klesá tlaková i kinetická energie", "Stoupá tlaková i kinetická energie", "Kinetická energie stoupá a tlaková energie klesá", "Tlaková energie stoupá a kinetická energie klesá"], 2],
  [411, "Jak se nazývá zařízení, které vypadá jako kuželové potrubí přemĕňující kinetickou energii vody na její tlakovou energii, což zajišťuje odvod vody od turbíny?", ["Savka", "Difuzor", "Tryska", "Stavidlo"], 0],
  [412, "Rotor které z uvedených turbín má obvykle nejmenší počet lopatek?", ["Francisova turbína", "Kaplanova turbína", "Peltonova turbína", "Dériazova turbína"], 1],
  [413, "Rotor které z uvedených turbín má natáčecí lopatky for regulaci jejího chodu?", ["Francisova turbína", "Kaplanova turbína", "Peltonova turbína", "Bánkiho turbína"], 1],
  [414, "Která z uvedených turbín má nejvyšší účinnost?", ["Francisova turbína", "Kaplanova turbína", "Peltonova turbína", "Turbína Turgo"], 1],
  [415, "U které z tĕchto turbín se regulace neprovádí natočením lopatek (ať už tĕch na rotoru nebo stacionárních mimo rotor)?", ["Peltonova turbína", "Kaplanova turbína", "Dériazova turbína", "Francisova turbína"], 0],
  [416, "Jaký typ vodního díla je nejpravdĕpodobnĕji na obrázku?", ["Nízkotlaké", "Středotlaké", "Vysokotlaké", "Přečerpávací"], 1],
  [417, "K jaké turbínĕ patří součást na obrázku?", ["Peltonovĕ", "Francisovĕ", "Kaplanovĕ", "Dériazovĕ"], 0],
  [418, "Rotor které turbíny je na obrázku?", ["Peltonové", "Francisové", "Kaplanové", "Bánkiho"], 2],
  [419, "Na obrázku je Francisova turbína. K čemu slouží zařízení natřené oranžovou barvou?", ["K odvodu vody z turbíny", "K nastavení polohy spirální skřínĕ", "K natáčení rotorových lopatek", "K regulaci turbíny"], 3],
  [420, "Které barvĕ odpovídá oblast použití Peltonovy turbíny?", ["Červené", "Modré", "Zelené", "Žluté"], 3],
  [421, "Co je to parní turbína?", ["Hnací lopatkový stroj", "Hnaný lopatkový stroj", "Hnací pístový stroj", "Hnaný pístový stroj"], 0],
  [422, "K jaké přemĕnĕ energie dochází v parních turbínách?", ["Kinetická a tlaková energie se mĕní na mechanickou", "Tepelná energie se mĕní na mechanickou", "Mechanická energie se mĕní na kinetickou a tlakovou", "Tepelná energie se mĕní na mechanickou"], 1, 3],
  [423, "Ve kterém z uvedených zařízení se nepoužívá (ani nikdy nepoužívala) parní turbína?", ["Uhelná elektrárna", "Jaderná elektrárna", "Vĕtrná elektrárna", "Lodní motor"], 2],
  [424, "Jak se nazývá zařízení (část) parní turbíny, ve které dochází k přemĕnĕ tlakové energie na kinetickou?", ["Rozvádĕcí kolo", "Obĕžné kolo", "Rotor turbíny", "Kondenzátor"], 0],
  [425, "Které tvrzení o 'rovnotlaké parní turbínĕ' NENÍ pravdivé?", ["Rotorem je (plná) hřídel s lopatkami", "Statorové lopatky are vůči rotoru utĕsnĕny labyrintovým tĕsnĕním", "Je pro ni nejvhodnĕjší vstup páry do turbíny po celém obvodu", "Rotor turbíny bývá uložen v kluzných ložiscících"], 2],
  [426, "Které tvrzení o 'přetlakové parní turbínĕ' NENÍ pravdivé?", ["Rotorem je buben (dutá hřídel) s lopatkami", "Před lopatkou rotoru je menší tlak než za ní", "Je pro ni nejvhodnĕjší vstup páry do turbíny po celém obvodu", "Součástí turbíny je tzv. Curtisův stupeň"], 1],
  [427, "Jaké otáčky mají (přibližnĕ) rotory parních turbín provozované v ČR?", ["50 otáček za minutu", "3000 otáček za minutu", "1500 otáček za minutu", "1800 otáček za minutu"], 1],
  [428, "K jaké přemĕnĕ energie dochází v tryskách parních turbín?", ["Tlaková energie se mĕní v kinetickou", "Kinetická energie se mĕní v tlakovou", "Kinetická energie se mĕní v mechanickou", "Mechanická energie se mĕní kinetickou"], 0],
  [429, "Co se dĕje v rychlostí páry v prostoru mezi lopatkami rotoru rovnotlaké parní turbíny?", ["Klesá", "Stoupá", "Je konstantní", "Nelze jednoznačnĕ určit závisí to na otáčkách rotoru"], 0],
  [430, "Co se dĕje v rychlostí páry v prostoru mezi lopatkami statoru přetlakové parní turbíny?", ["Klesá", "Stoupá", "Je konstantní", "Nelze jednoznačnĕ určit závisí to na otáčkách rotoru"], 1],
  [431, "Jak se nazývá zařízení, které nemá spalovací komoru ani turbokompresor?", ["Expanzní turbína", "Spalovací turbína", "Plynová turbína", "Výmĕníková turbína"], 0],
  [432, "Jak se nazývá druh turbíny, u které má spalovací komora zároveň funkci výmĕníku?", ["Spalovací turbína", "Plynová turbína", "Expanzní turbína", "Výmĕníková turbína"], 3],
  [433, "Jak se nazývá druh turbíny, u které spaliny vzniklé hořením proudí přímo na lopatky rotoru?", ["Spalovací turbína", "Plynová turbína", "Expanzní turbína", "Výmĕníková turbína"], 0],
  [434, "Kterou z uvedených částí obvykle neobsahuje otevřený okruh?", ["Kompresor", "Čerpadlo", "Turbína", "Dmychadlo"], 3],
  [435, "Jaký smysl má umístění výměníku do okruhu spalovací turbíny?", ["Zvýšení účinnosti", "Snížení výkonu", "Zabránění zanášení", "Zrychlení spouštění"], 0],
  [436, "Na obrázku je průbĕh tlaku a rychlosti páry v rovnotlaké parní turbínĕ. Která fáze (fialové označené svorkami) odpovídá průbĕhu mezi jejími statorovými lopatkami?", ["A", "B", "C", "D"], 2],
  [437, "Na obrázku je průbĕh tlaku a rychlosti páry v přetlakové parní turbínĕ. Která fáze (fialové označené svorkami) odpovídá průbĕhu mezi jejími rotorovými lopatkami?", ["A", "B", "C", "D"], 0],
  [438, "Jaká část a které parní turbíny se nachází na obrázku?", ["Rotor rovnotlaké parní turbíny", "Stator rovnotlaké parní turbíny", "Rotor přetlakové parní turbíny", "Stator přetlakové parní turbíny"], 0],
  [439, "Pod kterým číslem na schématu přetlakové parní turbíny se nachází rovnotlaký stupeň?", ["1", "2", "3", "5"], 1],
  [440, "Na obrázku je turbodmychadlo automobilu. O jaký okruh plynové turbíny se tedy jedná?", ["Otevřený okruh bez výmĕníku", "Otevřený okruh s výmĕníkem", "Uzavřený okruh bez výmĕníku", "Uzavřený okruh s výmĕníkem"], 0],
  [441, "Proč je potřeba přidávat palivo do parního kotle?", ["Je to nosič chemické energie", "Kvůli chlazení při spalování", "Pro zlepšení hoření vzduchu", "Je to nosič kinetické energie"], 0],
  [442, "Která složka nevstupuje do parního kotle?", ["Voda", "Palivo", "Vzduch", "Vodní pára"], 3],
  [443, "Co vzniká hořením paliva se vzduchem?", ["Voda", "Spaliny", "Led", "Vodní pára"], 1],
  [444, "Jakou teplotu má zhruba u současných parních generátorů vystupující vodní pára?", ["Kolem 250°C", "Kolem 550°C", "Kolem 850°C", "Kolem 1150°C"], 1],
  [445, "Jaký tlak vodní páry se označuje jako 'kritický'?", ["2,21 MPa", "20,1 MPa", "22,1 MPa", "2,01 MPa"], 2],
  [446, "Do jakého tlaku přibližnĕ se vodní pára používá k vytápĕní?", ["Do 0,15 MPa", "Do 1,5 MPa", "Do 11,5 MPa", "Do 115 MPa"], 0],
  [447, "Které ze zmínĕných paliv NELZE zařadit mezi tuhá paliva?", ["Hnĕdé uhlí", "Dřevo", "Biomasa", "Mazut"], 3],
  [448, "Které ze zmínĕných paliv NELZE zařadit mezi plynná paliva?", ["Zemní plyn", "Propan butan", "Biomasa", "Bioplyn"], 2],
  [449, "Který druh kotle se vyznačuje velkou trubkou se zvlnĕným povrchem, ve které hoří palivo?", ["Plamencový kotel", "Žárotrubný kotel", "Vodotrubný kotel", "Průtočný kotel"], 0],
  [450, "Který ze zmínĕných kotlů má nejmenší účinnost?", ["Plamencový kotel", "Žárotrubný kotel", "Vodotrubný kotel", "Velkoprostorový kotel"], 3],
  [451, "Se kterým ze zmínĕných kotlů lze dosáhnout nejvĕtšího tlaku vystupující vodní páry?", ["Plamencový kotel", "Žárotrubný kotel", "Vodotrubný kotel", "Průtočný kotel"], 3],
  [452, "Jak se jmenuje místo parního generátoru, ve kterém dochází k mísení paliva se vzduchem?", ["Ohništĕ", "Komín", "Výparník", "Ohřívák"], 0],
  [453, "Jak se jmenuje místo parního generátoru, ve kterém dochází k přemĕnĕ vody na páru?", ["Kotlový buben", "Vodotrubní výparník", "Ohništĕ", "Komín"], 1],
  [454, "Které z tĕchto druhů ohnišť využívaných for parní generátory neexistuje?", ["Roštové ohništĕ", "Fluidní ohništĕ", "Cyklonové ohništĕ", "Prvkové ohništĕ"], 3],
  [455, "Co z uvedených NELZE zařadit do přípravy tuhého paliva před jeho použitím v parním generátoru?", ["Drcení (mletí) paliva", "Sušení paliva", "Skladování a podávání paliva", "Odstruskování paliva"], 3],
  [456, "Schéma jakého základního typu parního kotle je na obrázku?", ["Válcový", "Vodotrubný", "Průtočný", "Plamencový"], 3],
  [457, "Schéma jakého základního typu ohništĕ parních kotlů je na obrázku?", ["Roštové", "Fluidní", "Práškové", "Cyklonové"], 3],
  [458, "Jak by se dal nejlépe nazvat celek (část parního kotle) na obrázku?", ["Přehřívák páry", "Odlučovač popílku", "Kotlový buben", "Vzduchový chladič"], 0],
  [459, "Na obrázku je schéma vysokotlakého parního kotle s dvĕma tahy. Jak se nazývá jeho část označený číslem 3 (umístĕná na schématu vlevo nahoře)?", ["Tangenciální hořák", "Přehřívák páry", "Kotlový buben", "Ohřívák vzduchu"], 2],
  [460, "K jakému účelu slouží strojní celek na obrázku v souvislosti s parními generátory?", ["K přípravĕ tuhého paliva", "K ohřívání vzduchu před hořením", "K oddĕlení vody od páry", "K elektrostatickému odloučení popílku"], 2],
  [461, "Co je výhodou teplovodního vytápĕní?", ["Systém nepotřebuje expanzní nádobu", "Krátká doba nábĕhu", "Nehrozí nebezpečí zamrznutí", "Bezpečný a jednoduchý provoz"], 3],
  [462, "Co nepatří mezi výhody parního vytápĕní?", ["Rychlý nábĕh topení", "Nízké provozní náklady", "Vysoký topný výkon", "Nízká teplota otopných tĕles"], 3],
  [463, "Kde dochází v přemĕnĕ páry na vodu (kondenzaci) u parního vytápĕní?", ["V rozvodném potrubí", "V otopných tĕlesech", "V expanzní nádobĕ", "V parním kotli"], 1],
  [464, "Pokud je teplo pro celý objekt vyrábĕno v kotli umístĕném například v jeho sklepĕ, pak se jedná o vytápĕní ...", ["lokální.", "etážové.", "ústřední.", "dálkové."], 2],
  [465, "U kterého druhu vytápĕní lze nejhůře regulovat teplotu z hlediska její rovnomĕrnosti v objektu?", ["Lokální vytápĕní", "Ústřední vytápĕní", "Skupinové vytápĕní", "Dálkové vytápĕní"], 0],
  [466, "Podle čeho se dimenzuje otopná soustava resp. výkon kotle?", ["Podle tepelných ztrát z objektu", "Podle počtu místností objektu", "Podle objemu vzduchu v objektu", "Podle tvaru objektu"], 0],
  [467, "Jakou jednotku má veličina 'tepelný tok'?", ["Watt", "Joule", "Kelvin", "Newton"], 0],
  [468, "Co je to 'konvektor'?", ["Otopné tĕleso", "Expanzní nádoba", "Teplovodní kotel", "Rozvodné potrubí"], 0],
  [469, "Teplovodní otopná soustava je vybavena otevřenou expanzní nádobou. Kde se tato otevřená expanzní nádoba nachází?", ["U teplovodního kotle", "V nejvyšší místĕ soustavy", "U každého otopného tĕlesa", "Nezáleží na její poloze"], 1],
  [470, "Pokud v místnosti otevřete okno, pak se jedná o vĕtrání ...", ["přirozené.", "samočinné.", "nucené.", "lokální."], 0],
  [471, "Co nepatří mezi výhody vysokotlaké klimatizace?", ["Menší rozmĕry rozvodného potrubí", "Snazší (i dodatečná) instalace zařízení do objektu", "Nastavení odlišné teploty for každou místnost", "Velmi nízká cena celého zařízení"], 3],
  [472, "Co je to tzv. výparné teplo?", ["Teplo, které látka potřebuje ke zmĕnĕ svého skupenství", "Teplo, které látka vydá do okolí při vypařování", "Teplo, které se z látky samovolnĕ uvolňuje a lze využít k vytápĕní", "Teplo, které se přemĕní v mechanickou energii kompresoru"], 0],
  [473, "Co musí splňovat chladící kapalina, aby byla vhodná pro použití do chladícího okruhu?", ["Musí mít vysokou teplotu varu", "Musí mít vysokou hodnotu výparného tepla", "Musí mít vysokou hustotu v kapalné formĕ", "Musí mít vysokou cenu"], 1],
  [474, "Co se dĕje ve výparníku chladícího obĕhu?", ["Chladivo je do nĕj přivedeno v kapalné formĕ a opouští ho v plynné formĕ", "Chladivo je do nĕj přivedeno v kapalné formĕ a opouští ho taktéž v kapalné formĕ", "Chladivo je do nĕj přivedeno v plynné formĕ a opouští ho taktéž v plynné formĕ", "Chladivo je do nĕj přivedeno v plynné formĕ a opouští ho v kapalné formĕ"], 0],
  [475, "Pokud kompresorový chladicí obĕh principiálnĕ využíváme k vytápĕní, pak se jedná o ...", ["tepelné čerpadlo.", "absorpční chlazení.", "decentralizovanou klimatizaci.", "teplovzdušné vytápĕní."], 0],
  [476, "Jaký druh otopného tĕlesa se nachází na obrázku?", ["Článkové", "Deskové", "Trubkové", "Konvektorové"], 0],
  [477, "K čemu u teplovodního vytápĕní slouží celek na obrázku?", ["K zajištĕní přirozeného proudĕní vody topným okruhem", "K zrychlení doby nábĕhu po spuštĕní topného systému", "K zajištĕní topného okruhu proti zamrznutí v případĕ odstávky", "K zachycování zmĕny objemu vody při zmĕnĕ její teploty"], 3],
  [478, "O jaký druh vytápĕní se jedná, pokud se for vytápĕní použije zdroj tepla na obrázku?", ["Dálkové", "Ústřední", "Lokální", "Etážové"], 2],
  [479, "Na obrázku je schematicky zobrazen chladící okruh bĕžné ledničky s kompresorovým chlazením. Jak se nazývá část okruhu označena písmenem 'A'?", ["Varník", "Absorbér", "Kondenzátor", "Výparník"], 2],
  [480, "Z jednotky tepelného čerpadla na obrázku vlevo vedou trubky pouze do vytápĕného objektu, jak je znázornĕno na schématu. O jaký druh tepelného čerpadla se jedná?", ["Vzdušník - vzduch", "Voda - voda", "Zemĕ - voda", "Vzduch - voda"], 3],
  [481, "Jakou energii získáváme z jaderného reaktoru?", ["Chemickou energii", "Tepelnou energii", "Jadernou energii", "Potenciální energii"], 1],
  [482, "Čím se štĕpí nuklid (atom) uranu?", ["Přívodem tepla", "Volným neutronem", "Gama zářením", "Pomocí moderátoru"], 1],
  [483, "V jádře atomu se nachází ...", ["protony a neutrony.", "protony a elektrony.", "pouze neutrony.", "pouze protony."], 0],
  [484, "Co NEVZNIKNE štĕpením nuklidu (atomu) uranu?", ["Štĕpné trosky (odštĕpky)", "Volné neutrony", "Elektromagnetické záření", "Vodní pára"], 3],
  [485, "Co má za úkol v jaderném reaktoru tzv. moderátor?", ["Pohlcovat neutrony", "Zpomalovat neutrony", "Zrychlovat neutrony", "Odráží neutrony"], 1],
  [486, "U kterého z tĕchto jaderných reaktoru NEHROZÍ nebezpečí neřízené reakce, štĕpení a výbuchu?", ["U tlakovodního reaktoru", "U fúzního reaktoru", "U množivého reaktoru", "U varného reaktoru"], 1],
  [487, "Který druh jaderného reaktoru je používán pro české jaderné elektrárny (Dukovany a Temelín)?", ["Tlakovodní reaktor", "Fúzní reaktor", "Varný reaktor", "Množivý reaktor"], 0],
  [488, "Jak se nazývá jaderný reaktor, který jako palivo používá plutonium?", ["Tlakovodní reaktor", "Fúzní reaktor", "Varný reaktor", "Množivý reaktor"], 3],
  [489, "Který z tĕchto chemických vzorců NEOZNAČUJE látku používanou jako chladivo v jaderných reaktorech?", ["H2O", "D2O", "CO2", "DO2"], 3],
  [490, "K čemu slouží v jaderném reaktoru tzv. reflektor?", ["K pohlcování neutronů", "Ke zpomalování neutronů", "Ke zrychlování neutronů", "K odrážení neutronů"], 3],
  [491, "V jakém skupenství se dopravuje palivo do jaderného reaktoru?", ["V pevném skupenství", "V plynném skupenství", "V kapalném skupenství", "V plazmatickém skupenství"], 0],
  [492, "Která z tĕchto druhů elektráren se NEŘADÍ mezi tepelné?", ["Jaderná elektrárna", "Uhelná elektrárna", "Paroplynová elektrárna", "Solární elektrárna"], 3],
  [493, "Která z tĕchto druhů elektráren se NEŘADÍ mezi ty, které používají pro výrobu elektrické energie obnovitelný zdroj energie?", ["Solární elektrárna", "Vĕtrné elektrárna", "Vodní elektrárna", "Paroplynová elektrárna"], 3],
  [494, "Jak dlouho po vyjmutí z jaderného reaktoru se skladuje (chladí a stíní) použité palivo ve vodĕ?", ["Cca 10 dní", "Cca 10 týdnů", "Cca 10 mĕsíců", "Cca 10 let"], 3],
  [495, "Co NEPATŘÍ mezi nevýhody solárních elektráren?", ["Vysoká pořizovací cena", "Závislost na okolních podmínkách", "Nízká účinnost", "Náročnost na údržbu"], 3],
  [496, "Jakou zkratkou lze označit jaderný reaktor, jehož schéma je na obrázku?", ["PWR", "BWR", "PHWR", "GCR"], 0],
  [497, "Jak by se dal nejlépe nazvat jaderný reaktor, jehož schéma je na obrázku?", ["Tĕžkovodní", "Tlakovodní", "Varný", "Lehkovodní"], 2],
  [498, "K čemu slouží v jaderné elektrárnĕ tento celek na obrázku?", ["K termonukleárnímu štĕpĕní paliva", "K přípravĕ čerstvého paliva", "K zastavení štĕpné reakce", "Ke skladování použitého paliva"], 3],
  [499, "Na obrázku je výřez leteckého pohledu na jadernou elektrárnu Dukovany. K čemu dochází ve čtyřech šedých velkých objektech na obrázku?", ["K odvodu vzniklé páry z jaderném reaktoru", "K chlazení použité chladící vody z kondenzátoru", "K zvýšení tahu spalin z plynové turbíny", "K vypouštĕní nevyužité vodní páry z parogenerátoru"], 1],
  [500, "Na obrázku je schematicky zobrazen štĕpĕní jádra atomu uranu. Jak se nazývá prvek na schématu (nakreslený modrou barvou a označený červenou šipkou)?", ["Absorbátor", "Moderátor", "Odštĕpek", "Kontejnment"], 1]
];
