
export const part1 = [
  [1, "Nástrojové úhly platí α, β, γ, δ jsou úhly:", ["α čela, β břitu, γ hřbetu, δ řezu", "α břitu, β hřbetu, γ čela, δ řezu", "α čela, β břitu, γ řezu, δ hřbetu", "α hřbetu, β břitu, γ čela, δ řezu"], 3],
  [2, "Nástrojové úhly platí ε, κr, κr' jsou úhly:", ["ε špičky nástroje, κr nastavení hlavního ostří, κr' nastavení vedlejšího ostří", "ε špičky nástroje, κr nastavení vedlejšího ostří, κr' nastavení hlavního ostří", "ε řezu, κr nastavení hlavního ostří, κr' nastavení vedlejšího ostří", "ε čela, κr' nastavení hlavního ostří, κr nastavení vedlejšího ostří"], 0],
  [3, "Nástrojové úhly - δ je úhel řezu a platí:", ["δ=γ+β", "δ=α+β", "δ=α+ε", "δ=α+γ"], 1],
  [4, "Kinematika obrábění - hlavní řezný pohyb při soustružení je:", ["přímočarý vratný nástroje", "rotační obrobku", "rotační nástroje", "posuvný obrobku"], 1],
  [5, "Kinematika obrábění - hlavní řezný pohyb při frézování je:", ["posuvný obrobku", "rotační obrobku", "přímočarý vratný nástroje", "rotační nástroje"], 3],
  [6, "Kinematika obrábění - hlavní řezný pohyb při obrážení je:", ["rotační obrobku", "přímočarý vratný obrobku", "přímočarý vratný nástroje", "posuvný obrobku"], 2],
  [7, "Kinematika obrábění - hlavní řezný pohyb při hoblování je:", ["přímočarý vratný nástroje", "přímočarý vratný obrobku", "rotační obrobku", "posuvný nástroje"], 1],
  [8, "Kinematika obrábění - hlavní řezný pohyb při broušení je:", ["rotační nástroje", "přímočarý vratný obrobku", "rotační obrobku", "přímočarý vratný nástroje"], 0],
  [9, "Kinematika obrábění - hlavní řezný pohyb při vrtání je:", ["posuvný nástroje", "posuvný obrobku", "rotační obrobku", "rotační nástroje"], 3],
  [10, "Nástrojové oceli jsou:", ["nelegované, legované, rychlořezné, na lité nástroje", "slinuté karbidy, legované, rychlořezné, technické diamanty", "technické diamanty, nelegované, rychlořezné, na lité nástroje", "technické diamanty, legované, rychlořezné, na lité nástroje"], 0],
  [11, "Tvrdé řezné materiály jsou:", ["slinuté karbidy, nelegované oceli, technické diamanty", "slinuté karbidy, keramika, legované oceli", "slinuté karbidy, keramika, technické diamanty, oceli", "slinuté karbidy, keramické materiály, technické diamanty, kubický nitrid boru"], 3],
  [12, "Tříska tvářená plynulá nebo tvářená článkovitá je charakteristická pro:", ["křehké nekovové materiály", "křehké kovové materiály", "sklo, dřevo", "houževnaté materiály"], 3],
  [13, "Tříska elementární vytrhávaná je charakteristická pro:", ["houževnaté kovové materiály", "houževnaté nekovové materiály (např. pryž)", "slitiny hliníku", "sklo, porcelán"], 1],
  [14, "Největší vliv na drsnost obrobené plochy má:", ["řezná rychlost", "geometrie břitu", "posuv", "řezné prostředí"], 2],
  [15, "Tepelná bilance obrábění nám říká:", ["teplo vzniklé je rovno teplu, které odchází", "teplo nikam neodchází", "teplo je menší", "teplo je větší"], 0],
  [16, "Teplo, které při obrábění vzniká, odchází do:", ["třísky, obrobku, nástroje, okolí", "třísky, nástroje", "nástroje, třísky", "nástroje, okolí"], 0],
  [17, "Rozdělení soustružnických nožů podle materiálu břitu:", ["přímé a ohnuté", "rychlořezné oceli, slinutý karbid, kubický nitrid bóru", "levé, pravé", "ubírací, zapichovací"], 1],
  [18, "Vyměnitelné břitové destičky:", ["mívají více břitů a nepřeostřují se", "mívají více břitů a přeostřují se", "mívají jeden břit", "mívají jeden břit a přeostřují se"], 0],
  [19, "Otáčení obrobku pomocí SRDCE je nutné při upnutí:", ["do univerzálního sklíčidla", "na lícní desku", "mezi hroty", "do kleštin"], 2],
  [20, "Nejpřesnější upnutí obrobku při soustružení je:", ["do sklíčidla", "do kleštin", "na lícní desku", "mezi hroty"], 3],
  [21, "LUNETY slouží k:", ["podpoře na konci", "měření", "podpoře uprostřed", "přenosu momentu"], 2],
  [22, "Soustružení - upínání na lícní desku je určeno pro:", ["tvarově složité součásti", "dlouhé součásti", "nástroje ze SK", "tvarové nástroje"], 0],
  [23, "Soustruhy ČELNÍ jsou určeny pro:", ["dlouhé velké", "dlouhé malé", "krátké malé", "krátké součásti velkých průměrů"], 3],
  [24, "Svislé soustruhy - KARUSELY jsou určeny pro:", ["velké těžké, svislá osa", "malé lehké", "malé lehké, svislá osa", "velké těžké, vodorovná osa"], 0],
  [25, "Poloautomatické soustruhy mají automatický cyklus:", ["kromě upnutí a odepnutí", "včetně upnutí", "včetně upnutí", "kromě upnutí"], 0],
  [26, "Automatické soustruhy mají automatický cyklus:", ["včetně upnutí a odepnutí", "kromě upnutí", "kromě upnutí", "včetně upnutí"], 0],
  [27, "Soustružení - průměr D v řezné rychlosti znamená průměr:", ["před obrobením - m", "po obrobení - m", "před obrobením - mm", "po obrobení - mm"], 2],
  [28, "Při soustružení na hrubo platí - Ra volím:", ["větší (horší), max přídavek", "stejné, min přídavek", "větší (horší), min přídavek", "menší (lepší), min přídavek"], 2],
  [29, "Jaký je rozdíl mezi VRTÁNÍM a VYVRTÁVÁNÍM?", ["do plna obojí", "vrtáme do plna, vyvrtáváme do předchystané", "vyvrtáváme do plna", "do předchystané obojí"], 1],
  [30, "KOPINATÉ vrtáky:", ["špatný odvod, krátké velké průměry", "dobrý odvod", "špatný odvod, krátké malé", "dobrý odvod, dlouhé velké"], 0],
  [31, "ŠROUBOVITÝ vrták pro ocel má úhel špičky:", ["90", "118", "100", "145"], 1],
  [32, "ŠROUBOVITÝ vrták z rychlořezné oceli má:", ["dvě hlavní ostří a jedno příčné", "jedno hlavní", "dvě hlavní a dvě příčné", "jedno hlavní a jedno příčné"], 0],
  [33, "Při broušení ŠROUBOVITÉHO vrtáku z RO dochází ke změně:", ["délky i průměru", "délky", "nepřebrušuje se", "průměru"], 1],
  [34, "Sdružené vrtáky se používají:", ["v kusové", "v hromadné, málo náročné", "v hromadné z důvodu úspory času", "v kusové, dlouhý čas"], 2],
  [35, "VRTAČKA STOLNÍ do průměru:", ["80", "40", "16", "100"], 2],
  [36, "VRTAČKA SLOUPOVÁ do průměru:", ["100", "40", "80", "16"], 1],
  [37, "VRTAČKA STOJANOVÁ do průměru:", ["40", "100", "80", "16"], 2],
  [38, "VRTAČKA RADIÁLNÍ do průměru:", ["40", "16", "80", "100"], 3],
  [39, "Vrtání s vysokou přesností (IT2-5) a roztečí?", ["Sloupovou", "Stojanovou", "Souřadnicovou", "Stolní"], 2],
  [40, "NESOUSLEDNÉ frézování:", ["větší opotřebení", "max tloušťka třísky", "horší kvalita", "zub frézy zabírá z nulové třísky"], 3],
  [41, "SOUSLEDNÉ frézování:", ["zub frézy zabírá v místě max tloušťky", "menší opotřebení", "lepší kvalita", "zub zabírá z nuly"], 0],
  [42, "Rozdělení fréz podle umístění břitu:", ["celistvé", "válcové, čelní, tvarové, kuželové", "přímé zuby", "stopkové"], 1],
  [43, "Rozdělení fréz podle upínání:", ["stopkové, nástrčné", "celistvé", "přímé zuby", "válcové"], 0],
  [44, "Rozdělení fréz podle konstrukce:", ["celistvé, skládané, s VBD", "přímé zuby", "celistvé", "stopkové"], 0],
  [45, "Nástrčné frézy se upínají:", ["do svěráku", "na trn, přenos perem", "ozubeným kolem", "do sklíčidla"], 1],
  [46, "Točivý moment u nástrčné frézy se přenáší:", ["perem", "kolem", "srdcem", "kolíkem"], 0],
  [47, "Frézky jsou:", ["přípravky", "nástroje", "etalony", "stroje"], 3],
  [48, "Vodorovná konzolová frézka - vřeteno je:", ["kolmé", "60 stupňů", "rovnoběžné se stolem", "30 stupňů"], 2],
  [49, "Svislá konzolová frézka - vřeteno je:", ["60 stupňů", "kolmé na stůl", "rovnoběžné", "30 stupňů"], 1],
  [50, "Rovinná frézka - stůl se pohybuje pouze:", ["svisle", "svisle i podélně", "šikmo", "v podélném směru"], 3],
  [51, "Výroba ozubení dělícím způsobem - v dělícím přístroji je:", ["nástroj", "nic", "obrobek", "obojí"], 2],
  [52, "Hoblovací nože jsou podobné:", ["soustružnickým nožům", "frézám", "kotoučům", "vrtákům"], 0],
  [53, "Obrážecí nože jsou podobné:", ["vrtákům", "frézám", "kotoučům", "soustružnickým nožům"], 3],
  [54, "Protahování a protlačování slouží k:", ["jen vnitřní", "jen vnější", "vnitřní i vnější rovinné nebo tvarové", "jen rovinné"], 2],
  [55, "Protahovací trn je:", ["jednobřitý", "vícebřitý kusovka", "hromadná", "vícebřitý v hromadné výrobě"], 3],
  [56, "Brusný kotouč je složen z:", ["brusiva, pojiva a pórů", "brusiva a pojiva", "brusiva a pórů", "brusiva"], 0],
  [57, "Při broušení je v záběru:", ["jeden břit", "velké množství břitů", "jeden", "velké množství břitů jedné velikosti"], 1],
  [58, "Volná brusná zrna najdeme u:", ["pláten", "prášku", "brusných past", "kamenů"], 2],
  [59, "Vázaná brusná zrna najdeme u:", ["prášku", "brusných kotoučů", "papírů", "kapaliny"], 1],
  [60, "Pro tvrdý obrobek volíme kotouč:", ["měkčí", "tvrdší", "žádný", "stejný"], 0],
  [61, "Pro měkký obrobek volíme kotouč:", ["jedno", "měkčí", "tvrdší", "stejný"], 2],
  [62, "Předcházení chvění při broušení?", ["tvrdší", "měkčí", "podložky", "vyvažováním"], 3],
  [63, "Planetové broušení pro:", ["velké obrobky", "malé", "zápich", "rovinné"], 0],
  [64, "Při jemném soustružení mám:", ["vysokou vc", "velkou hloubku", "velký posuv", "malou vc"], 0],
  [65, "Při jemném frézování mám:", ["vysokou vc", "velký posuv", "velkou hloubku", "malou vc"], 0],
  [66, "Při honování vykonává nástroj:", ["přímočarý", "otáčivý i přímočarý vratný", "otáčivý", "posuvný"], 1],
  [67, "Honování je:", ["broušení velkou vc bez kap", "broušení velkou vc s kap", "broušení malou vc bez kap", "broušení malou řeznou rychlostí s kap"], 3],
  [68, "Honovat můžeme:", ["vnitřní rotační", "vnitřní rovinné", "vše", "rotační i rovinné"], 0],
  [69, "Co neopravujeme honováním:", ["ovalitu", "souosost", "kuželovitost", "vlnitost"], 1],
  [70, "Lapovat můžeme:", ["ručně i strojně", "jen strojně", "jen ručně", "strojně ostrým"], 0],
  [71, "Lapování umožňuje:", ["jen rozměry", "jakost, přesné rozměry a tvar", "jakost a tvar", "jakost a rozměry"], 1],
  [72, "Lapovací nástroj:", ["zrna v pastě", "zrna v kap", "negativní tvar plochy", "tvar plochy"], 2],
  [73, "Superfinišovací kámen koná:", ["kmitavý pohyb", "přímočarý", "kmitavý a přímočarý", "rotační"], 0],
  [74, "Superfinišováním lze obrábět:", ["plasty", "sklo", "vše", "oceli a litiny"], 3],
  [75, "Superfinišovat můžeme:", ["vnější", "vnitřní", "vnitřní rovinné", "vnitřní i vnější rotační i rovinné"], 3],
  [76, "Superfinišování zlepšuje jakost, ale:", ["přesnost nezlepšuje", "přesnost kromě souososti", "válcovitost", "geometrickou"], 0],
  [77, "Leštění zlepšuje pouze:", ["vzhled", "geometrii", "vzhled a rozměry", "vzhled a geometrii"], 0],
  [78, "Leštění nepoužíváme před:", ["niklováním", "nátěrem", "chromováním", "chemií"], 1],
  [79, "Při omílání je v bubnu:", ["abrazivo", "tvrdost", "aktivní kapalina, abrazivo a obrobky", "kap a obrobky"], 2],
  [80, "Omíláním zlepšujeme:", ["drsnost a rozměry", "drsnost", "rozměry", "vše"], 1],
  [81, "Válečkování zvyšuje v povrchu:", ["pevnost, tvrdost a tlakové napětí", "pevnost", "pevnost a napětí", "tvrdost"], 0],
  [82, "Kuličkování zvyšuje v povrchu:", ["pevnost a napětí", "tvrdost", "pevnost, tvrdost a tlakové napětí", "pevnost"], 2],
  [83, "Výroba ozubení podle kinematiky:", ["protahování", "obrážení", "dělícím a odvalovacím způsobem", "soustružení"], 2],
  [84, "Výroba ozubení dělícím způsobem - v dělícím přístroji:", ["nástroj i obrobek", "měřidlo", "obrobek", "nástroj"], 2],
  [85, "Frézování ozubení dělícím způsobem:", ["jen stopkovou", "jen nástrčnou", "tvarovou stopkovou nebo nástrčnou", "nástrčnou"], 2],
  [86, "Obrážení ozubení dělícím způsobem - nástroj má:", ["tvar mezery a je v přístroji", "tvar zubu v přístroji", "tvar zubu, obrobek v přístroji", "tvar zubové mezery, obrobek v přístroji"], 3],
  [87, "Obrážení odvalovacím způsobem - nástroj:", ["odvalovací fréza", "kotoučový nůž", "hřebenový nůž", "kotoučový nebo hřebenový nůž"], 3],
  [88, "Výroba ozubení protahováním:", ["hromadná, obrobek v přístroji", "hromadná, nástroj v přístroji", "kusová", "kusová, obrobek v přístroji"], 0],
  [89, "Dokončovací operace čelních ozubených kol NENÍ:", ["ševingování", "lapování", "jemné soustružení", "broušení"], 2],
  [90, "Ševingování je:", ["hrubovací nekalená", "dokončovací pro nekalená kola", "hrubovací kalená", "dokončovací kalená"], 1],
  [91, "Na obrázku je upnutí pomocí:", ["upínky s vačkou", "upínky s výstředníkem", "upínky se šroubem a opěrkou", "žádná"], 2],
  [92, "Na obrázku je dokončování ozubení:", ["ševingováním", "zaběháváním", "lapováním", "broušením"], 0],
  [93, "Na obrázku je výroba ozubení kotoučovým nožem:", ["frézování", "obrážení", "broušení", "hoblování"], 1],
  [94, "Výroba ozubených kol – o jakou technologii kotoučovým nožem se jedná?", ["frézování", "broušení", "hoblování", "obrážení"], 3],
  [95, "Na obrázku je technologie:", ["obrážení", "hoblování", "broušení", "frézování odvalovací frézou"], 3],
  [96, "Na obrázku je:", ["broušení odvalovacím", "broušení dělícím", "frézování dělícím", "frézování odvalovacím"], 1],
  [97, "Výroba ozubených kol – o jakou technologii se jedná?", ["protahování dělícím způsobem", "frézování dělícím způsobem", "protahování odvalovacím způsobem", "frézování odvalovacím způsobem"], 1],
  [98, "Výroba ozubených kol – o jakou technologii se jedná?", ["tváření odvalovacím způsobem", "tváření dělícím způsobem", "frézování dělícím způsobem", "frézování odvalovacím způsobem"], 0],
  [99, "O jakou dokončovací operaci se jedná?", ["válečkování", "superfinišování", "lapování", "honování"], 3],
  [100, "O jaký druh třísky se jedná?", ["elementární", "článkovitá", "tvářená plynulá", "vytrhávaná"], 2],
  [101, "O jaký druh třísky se jedná?", ["vytrhávaná elementární", "tvářená článkovitá", "tvářená plynulá", "tvářená elementární"], 1],
  [102, "O jaký druh třísky se jedná?", ["vytrhávaná elementární", "tvářená článkovitá", "tvářená elementární", "tvářená plynulá"], 0],
  [103, "O jakou dokončovací operaci se jedná?", ["lapování", "superfinišování", "honování", "válečkování"], 1],
  [104, "O jakou dokončovací operaci se jedná?", ["honování", "lapování", "superfinišování", "válečkování"], 1],
  [105, "Na obrázku vidíme univerzální vertikální stroj na:", ["válečkování rovinných ploch", "superfinišování rovinných ploch", "honování rovinných ploch", "lapování rovinných ploch"], 2],
  [106, "O jakou dokončovací operaci se jedná?", ["válečkování", "superfinišování", "honování", "lapování"], 0],
  [107, "O jakou dokončovací operaci se jedná?", ["superfinišování", "kuličkování", "honování", "lapování"], 1],
  [108, "O jaké soustružení se jedná?", ["podélné", "čelní", "upichovací", "zapichovací"], 0],
  [109, "O jaké soustružení se jedná?", ["upichovací", "čelní", "podélné", "zapichovací"], 1],
  [110, "O jaké soustružení se jedná?", ["zapichovací", "čelní", "podélné", "upichovací"], 0],
  [111, "O jaké soustružení se jedná?", ["soustružení kuželu", "upichovací", "podélné", "zapichovací čelní"], 1],
  [112, "Na obrázku vidíme:", ["nožovou hlavu brusky", "nožovou hlavu frézky", "nožovou hlavu soustruhu", "měřič úhlů"], 2],
  [113, "Revolverová hlava na obrázku slouží k upnutí:", ["nástrojů", "kalibrů", "obrobků", "měřidel"], 0],
  [114, "Na obrázku vidíme upnutí:", ["do kleštin", "na lícní desku", "do sklíčidla", "mezi hroty"], 0],
  [115, "Na obrázku vidíme:", ["univerzální sklíčidlo", "lunetu", "lícní desku", "kleštinu"], 0],
  [116, "Na obrázku vidíme:", ["sklíčidlo", "lícní desku", "lunetu", "kleštinu"], 1],
  [117, "Na obrázku vidíme upnutí:", ["do sklíčidla", "na lícní desku", "mezi hroty", "v kleštině"], 2],
  [118, "Na obrázku je soustruh - pozice 5 je:", ["sklíčidlo", "koník", "vřeteník", "suport"], 1],
  [119, "Na obrázku je univerzální hrotový soustruh - pozice 4 je:", ["převodovka", "suport", "vřeteník", "lože"], 1],
  [120, "Na obrázku je univerzální hrotový soustruh - pozice 3 je:", ["suport", "lože", "elektromotor", "převodovka"], 1],
  [121, "Na obrázku je soustruh - pozice 2 je:", ["koník", "lože", "vřeteník", "suport"], 2],
  [122, "Na obrázku je:", ["radiální vrtačka", "univerzální hrotový soustruh", "karusel", "univerzální konzolová frézka"], 1],
  [123, "Na obrázku vidíme schéma soustruhu:", ["hrotového", "revolverového", "čelního", "svislého"], 1],
  [124, "Na obrázku vidíme schéma soustruhu:", ["hrotového", "svislého", "revolverového", "čelního"], 1],
  [125, "Na obrázku je:", ["vrtací hlava", "kopinatý vrták", "dělový vrták", "vrták"], 1],
  [126, "Na obrázku je:", ["šroubovitý vrták", "středící vrták", "dělový vrták", "vrták"], 1],
  [127, "Na obrázku je:", ["středící", "šroubovitý vrták", "hlava", "vrták"], 1],
  [128, "Na obrázku je:", ["vrtací hlava", "jednoduchý dělový vrták", "trepanační vrták", "šroubovitý vrták"], 1],
  [129, "Na obrázku vidíme vrtání:", ["jednoduchým dělovým vrtákem", "šroubovitým vrtákem", "trepanačním vrtákem na jádro", "vrtací hlavou"], 2],
  [130, "Na obrázku vidíme vrtání:", ["středícím vrtákem", "jednoduchým dělovým vrtákem", "trepanačním vrtákem na jádro", "šroubovitým vrtákem"], 1],
  [131, "Na obrázku vidíme vrtání:", ["sdruženým nástrojem", "středícím vrtákem", "jednoduchým šroubovitým vrtákem", "jednoduchým dělovým vrtákem"], 0],
  [132, "Na obrázku je vrtačka:", ["sloupová", "stolní", "stojanová", "souřadnicová"], 0],
  [133, "Na obrázku je vrtačka - pozice 1 je:", ["vřeteník", "vřeteno", "sloup", "motor"], 0],
  [134, "Na obrázku je vrtačka - pozice 2 je:", ["vřeteno", "sloup", "vřeteník", "motor"], 0],
  [135, "Na obrázku je vrtačka:", ["sloupová", "stojanová", "stolní", "souřadnicová"], 1],
  [136, "Na obrázku vidíme postupně operace - z leva:", ["vrtání, vystružování, vyhrubování", "vystružování, vyhrubování, vyvrtávání", "vrtání, vyhrubování, vystružování", "vyvrtávání, vyhrubování, vystružování"], 2],
  [137, "Na obrázku vidíme frézování válcové frézy:", ["čelem - nesousledné", "obvodem - nesousledné", "čelem - sousledné", "obvodem - sousledné"], 1],
  [138, "Na obrázku vidíme frézování válcové frézy:", ["obvodem - nesousledné", "čelem - sousledné", "čelem - nesousledné", "obvodem - sousledné"], 3],
  [139, "Na obrázku je fréza:", ["nástrčná čelní", "stopková čelní", "nástrčná válcová", "nástrčná tvarová"], 2],
  [140, "Na obrázku je fréza:", ["nástrčná válcová", "stopková válcová", "nástrčná čelní", "stopková kuželová"], 1],
  [141, "Na obrázku je fréza:", ["nástrčná tvarová", "stopková válcová", "nástrčná válcová", "stopková tvarová"], 0],
  [142, "Na obrázku je fréza:", ["nástrčná kotoučová", "nástrčná tvarová", "stopková tvarová", "nástrčná válcová"], 0],
  [143, "Na obrázku je fréza s VBD:", ["čelní nástrčná", "tvarová nástrčná", "tvarová stopková", "čelní stopková"], 0],
  [144, "Na obrázku vidíme upnutí obrobku při frézování, pozice 1 je:", ["obrobek", "opěrka", "upínka", "stůl frézky"], 0],
  [145, "Na obrázku vidíme upnutí obrobku při frézování, pozice 2 je:", ["obrobek", "stůl frézky", "opěrka", "upínka"], 3],
  [146, "Na obrázku vidíme upnutí obrobku při frézování, pozice 5 je:", ["obrobek", "upínka", "stůl frézky", "opěrka"], 2],
  [147, "Na obrázku vidíme upnutí obrobku při frézování, pozice 6 je:", ["stůl frézy", "obrobek", "stůl frézky", "opěrka"], 3],
  [148, "Na obrázku vidíme:", ["frézování čelem čelní frézy", "frézování obvodem tvarové frézy", "frézování čelem frézovcí hlavou", "frézování obvodem válcové frézy"], 2],
  [149, "Na obrázku vidíme:", ["frézování obvodem tvarové frézy", "frézování čelem čelní frézy", "frézování obvodem válcové frézy", "frézování čelem kuželové frézy"], 2],
  [150, "Na obrázku je konzolová frézka:", ["svislá", "portálová", "vodorovná", "vodorovně svislá"], 2],
  [151, "Na obrázku je konzolová frézka, pozice 5 je:", ["stůl", "vřeteník", "konzola", "stojan"], 0],
  [152, "Na obrázku je konzolová frézka, pozice 4 je:", ["konzola", "stůl", "stojan", "vřeteník"], 0],
  [153, "Na obrázku je konzolová frézka:", ["vodorovná", "svisle vodorovná", "svislá", "portálová"], 2],
  [154, "Na obrázku je konzolová frézka, pozice 5 je:", ["stojan", "vřeteník", "stůl", "konzola"], 3],
  [155, "Na obrázku je konzolová frézka, pozice 4 je:", ["stojan", "konzola", "vřeteník", "stůl"], 3],
  [156, "Na obrázku je konzolová frézka, pozice 1 je:", ["stojan", "vřeteník", "konzola", "stůl"], 0],
  [157, "Na obrázku je protahovací trn,kóta a je:", ["upínací část", "zadní vedení", "kalibrovací část", "řezná část"], 0],
  [158, "Na obrázku je protahovací trn,kóta c je:", ["kalibrovací část", "řezná část", "upínací část", "zadní vedení"], 1],
  [159, "Na obrázku je protahovací trn,kóta d je:", ["zadní vedení", "upínací část", "řezná část", "kalibrovací část"], 3],
  [160, "Na obrázku je protahovací trn,kóta e je:", ["upínací část", "řezná část", "kalibrovací část", "zadní vedení"], 3],
  [161, "Na obrázku vidíme:", ["kotoučový protahovák", "nástrčnou frézku", "nástrčnou frézu", "obrážecí nůž"], 0],
  [162, "Na obrázku je protahovačka:", ["svislá", "vodorovná", "kruhová", "šikmá"], 1],
  [163, "Na obrázku je protahovačka, pozice 4 je:", ["obrobek", "hydraulický válec", "píst", "protahovací trn"], 3],
  [164, "Na obrázku je protahovačka, pozice 3 je:", ["píst", "obrobek", "protahovací trn", "hydraulický válec"], 1],
  [165, "Na obrázku je protahovačka:", ["kruhová", "šikmá", "vodorovná", "svislá"], 3],
  [166, "Na obrázku je protahovačka, pozice 4 je:", ["píst", "protahovací trn", "hydraulický válec", "obrobek"], 3],
  [167, "Na obrázku je protahovačka, pozice 3 je:", ["hydraulický válec", "protahovací trn", "obrobek", "píst"], 1],
  [168, "Na obrázku je broušení:", ["bezhroté", "hloubkové", "zápichové", "planetové"], 2],
  [169, "Na obrázku je broušení:", ["bezhroté", "hloubkové", "zápichové", "planetové"], 0],
  [170, "Na obrázku je broušení rovinné:", ["brousícím pásem", "obvodem kotouče", "brousící pastou", "čelem kotouče"], 3],
  [171, "Na obrázku je broušení rovinné:", ["čelem kotouče", "brousící pastou", "brousícím pásem", "obvodem kotouče"], 3],
  [172, "Na obrázku je broušení rovinné:", ["obvodem kotouče", "brousícím pásem", "brousící pastou", "čelem kotouče"], 1],
  [173, "Na obrázku je hrotová bruska s:", ["posuvným stolem", "posuvným stojanem", "posuvným vřeteníkem", "posuvným sklíčidlem"], 0],
  [174, "Na obrázku je hrotová bruska s:", ["posuvným stojanem", "posuvným vřeteníkem", "posuvným sklíčidlem", "posuvným stolem"], 1],
  [175, "V plošně středěné mřížce krystalizují:", ["Cr, Mo", "Ti, W", "Pt, Zn", "Měď, hliník, železo gama"], 3],
  [176, "V mřížce prostorově středěné krystalizují:", ["Ti, Ta", "Cu, Ni", "Au, Ag", "Chrom, molybden, železo alfa"], 3],
  [177, "V šesterečné mřížce krystalizují:", ["Li, Zn", "Hg, Be", "Cr, Zn", "Zinek, kobalt, titan"], 3],
  [178, "Co je teplotní hystereze?", ["krystalizace výše", "neexistuje", "stejná", "teplota tání leží výše než krystalizace"], 3],
  [179, "Austenit je:", ["směs cementitu", "směs feritu", "roztok C v Fe alfa", "tuhý roztok uhlíku v železe gama"], 3],
  [180, "Ferit je:", ["směs feritu", "směs cementitu", "roztok C v Fe gama", "tuhý roztok uhlíku v železe alfa"], 3],
  [181, "Teplota AC1 v diagramu Fe-Fe3C je:", ["800", "911", "1400", "727"], 3],
  [182, "Segregační křivka Acm je křivka segregace:", ["feritu", "austenitu", "čistého železa", "cementitu"], 3],
  [183, "Tahový diagram znázorňuje:", ["tvrdost", "měkkost", "ohebnost", "závislost napětí na prodloužení"], 3],
  [184, "Zkušební tělísko u zkoušky tahem má tvar:", ["Tyčinky s vyznačenými body před zkouškou", "Tyčinky ze speciální oceli s trojúhelníkovým průřezem", "Tyčinky, která je zpevněna plastem na obou koncích", "Tyčinky, která má libovolný tvar"], 0],
  [185, "Bod „U“ na tahovém diagramu je:", ["Mez napětí, kde výslednicí ke přímka", "Mez úměrnosti, kde výslednicí je přímka", "Tento bod se v tahovém diagramu nevyskytuje", "Mez úměrnosti, kde výslednicí je lehká křivka"], 1],
  [186, "Urči, co vidíš na obrázku:", ["Žíhání na snížení pnutí", "Rekrystalizační žíhání", "Žíhání na měkko", "Normalizační žíhání"], 1],
  [187, "Bod „E“ na tahovém diagramu je:", ["Mez elasticity, kde se materiál stává kapalinou", "Mez napětí, kde se materiál lehce natrhne", "Mez elasticity, kde vznikne první trhlinka, která se šíří dál", "Mez elasticity, do které se jedná o vratné deformace"], 3],
  [188, "Bod „K“ v tahovém diagramu je:", ["Mez kluzu, která odpovídá hodnotě Rm se strojnických tabulkách", "Mez destrukce, kde vznikne první trhlinka, která se šíří dál", "Mez kluzu, kterému odpovídá hodnota Re ve strojnických tabulkách", "Mez napětí, kde se materiál stává kapalinou"], 2],
  [189, "Bod „P“ v tahovém diagramu je:", ["Mez pevnosti, do které se jedná o vratné deformace", "Tento bod se v tahovém diagramu nevyskytuje", "Mez kluzu, která odpovídá hodnotě Re se strojnických tabulkách", "Mez pevnosti, kde vznikne první trhlinka, která se šíří dál"], 3],
  [190, "Tvárnost u kovů a jejich slitin je:", ["Deformační chování materiálu s porušením materiálu", "Teplota tvárného materiálu", "Tvrdost materiálu", "Schopnost měnit svůj tvar působením vnější síly při plastické deformaci bez přerušení celistvosti materiálu"], 3],
  [191, "Tvárnost u kovů a jejich slitin úzce souvisí s:", ["Vnitřní stavbou materiálu, teplotou tvárného materiálu, druhem tvářecího procesu", "Viskozitou materiálu", "Houževnatostí materiálu", "Chemickým složením, teplotou viskózního toku, teplotou skelného přechodu"], 3],
  [192, "Zkouška rázem v ohybu slouží k:", ["tvrdosti", "houževnatosti", "chemie", "zjištění energie k přeražení"], 3],
  [193, "Výsledkem u zkoušky rázem v ohybu jsou jednotky:", ["N", "N*m", "kWh", "J"], 3],
  [194, "U zkoušky rázem v ohybu zjišťujeme:", ["Výkon", "Hodnotu tvrdosti", "Termodynamickou teplotu", "Houževnatost materiálu"], 3],
  [195, "Tvrdost je:", ["chemická odolnost", "křehkost", "nezkoumá se", "schopnost odolávat pronikání těles"], 3],
  [196, "Tvrdost se zkoumá:", ["Metodou dle Charpyho kladiva", "Metodami jen na základě empirického poznání", "Metodami dle Brinella, Rockwella a Vickerse", "Metodami dle diagramu IRA, ARA"], 2],
  [197, "Zkouška dle Brinella:", ["diamant", "kubický nitrid", "diamantový kužel", "vtlačování kuličky z tvrdokovu"], 3],
  [198, "Zkouška dle Vickerse:", ["kulička", "kužel", "SK kulička", "diamantový jehlan"], 3],
  [199, "HRC min 63 znamená:", ["63 jednotek", "tvrdost 63", "stupnice C Rockwella min 63"], 2],
  [200, "Výroba šedé litiny probíhá nejvíce v:", ["Šachtové peci – kuplovně", "V obloukové peci", "V indukční peci", "V kyslíkové peci"], 0],
  [201, "Litina má obsah uhlíku:", ["do 2.11", "nad 4.3", "kolem 0.657", "nad 2,11 %"], 3],
  [202, "V obloukové elektrické peci je dosahována teplota:", ["Indukcí", "Elektrickým obloukem", "Foukáním kyslíku do taveniny", "Vířivými proudy"], 1],
  [203, "Očkování litiny magnesiem se provádí pro:", ["cenu", "hmotnost", "tvrdost", "vytvoření globulárního grafitu"], 3],
  [204, "Z litiny se vyrábí např:", ["Skříně pro obráběcí stroje, stojany", "Dráty a kabely", "Kryty, dveře pro skříně s nářadím", "Navijáky, kufry, světlomety"], 0],
  [205, "Ocel 19 824 je:", ["Ocel na odlitky", "Ocel uhlíková", "Ocel nízkolegovaná", "Ocel rychlořezná"], 3],
  [206, "Ocel rychlořezná je určena pro:", ["Kladiva, kleště, šroubováky", "Zednické nářadí a vrtáky na dřevo", "Ruční nástroje a nářadí jako třeba nůžky na plech, razidla na mince", "Obzvláště vysoce namáhaná kovátka pro rotační kování"], 3],
  [207, "Ocel 11 373 je ocel:", ["konstrukční obtížná", "nerez", "nevhodná", "konstrukční, tavná svařitelnost zaručena"], 3],
  [208, "Nerezová ocel 42 2905.9 se používá pro:", ["Tlukadla a vysoké duté nýty", "Řezné materiály odolné proti popouštění", "Součásti vyráběné na rychloběžných automatech", "Oběžná kola a lopatky vodních turbín"], 3],
  [209, "Mechanické vlastnosti technických materiálů popisují chování při:", ["Při elektrické vodivosti", "Magnetické zátěži", "Zátěži v chemickém prostředí", "Zatěžování statickými a dynamickými silami"], 3],
  [210, "Technologické vlastnosti popisují chování materiálů při:", ["Zatížení na tah a tlak", "Zkouškách tvrdosti", "Technologických operacích jako např. slévatelnost, obrobitelnost", "Zatížení na ohyb a krut"], 2],
  [211, "Zařízení pro zkoušku tahem se jmenuje:", ["Poldi kladívko", "Vstřikovací a řídící jednotka", "Trhací stroj", "Charpyho kladivo"], 2],
  [212, "Zápis 25 HB čteme:", ["25 jednotek tvrdosti dle Rockwella na stupnici B", "25 jednotek", "25 jednotek tvrdosti dle Brinella", "25 jednotek tvrdosti dle Vickerse"], 2],
  [213, "Hodnota Re u zkoušky tahem:", ["Odpovídá hodnotě vratných deformací", "Odpovídá mezi pevnosti", "Odpovídá destrukci materiálu", "Odpovídá mezi kluzu"], 3],
  [214, "Hodnota Rm u zkoušky tahem:", ["Hodnotě napětí vratných deformací", "Hodnotě meze úměrnosti", "Odpovídá hodnotě, kdy ve zkušebním vzorku vznikne první trhlinka", "Hodnotě mezi kluzu"], 2],
  [215, "Oceli třídy 10 jsou určeny zejména pro:", ["Hlubokotažné plechy", "Konstrukční součásti méně důležité bez nosných svarů", "Konstrukční oceli, tavná svařitelnost zaručena", "Tyče tažené zastudena"], 1],
  [216, "Nízkouhlíková ocel 12 020.1 je určena:", ["Pro svařované konstrukce", "Pro nitridování a povrchovému kalení", "Pro cementování", "Pro fosfátování"], 2],
  [217, "Ocel 17 042.2 je určena:", ["Pro pístní čepy a pastorky", "Pro výrobky do korozivního prostředí", "Pro kroužky valivých ložisek", "Pro výrobu podvozků letadel"], 1],
  [218, "Materiál S235JR je materiál:", ["Jedná se o litinu určenou zejména na zemědělské stroje", "Jedná se o konstrukční ocel s minimální hodnotou Re 235 MPa a hodnotě 27 J nárazové práce", "Jedná se plast polyvinylchlorid", "Jedná se o konstrukční ocel s minimální hodnotou Re 27 MPa a hodnotě 235 J nárazové práce"], 1],
  [219, "Materiál GP265GH je:", ["Konstrukční materiál pro všeobecné použití", "Ocel na potrubí k vedení plynu a ropy z vrtných plošin na pobřeží", "Ocel na litou tlakovou nádobu", "Vysokolegovaná ocel pro chirurgické nástroje"], 2],
  [220, "Materiál E295:", ["Jedná se o ocel pro měkké výrobky tažené za studena", "Jedná se o ocel na strojní součásti", "Jedná se o ocel na potrubí", "Jedná se o ocel na kolejnice"], 1],
  [221, "Materiál HS2-9-1-8 je rychlořezná ocel s:", ["2W, 9Nb", "2Zr, 9Ta", "2W, 9Mo, 1V, 8Ni", "2W, 9Mo, 1V, 8Co"], 3],
  [222, "Austenitizace oceli:", ["je proces, který provádíme za účelem změknutí oceli, aby šla lépe obrábět", "je proces, který zlevňuje všechny druhy ocelí", "je proces, při kterém se obrobek zahřeje na určitou teplotu a vytvoří se austenit, který je stabilní při vysokých teplotách", "je proces, který provádíme za účelem změknutí oceli, aby šla lépe obrábět"], 2],
  [223, "Ocel kalíme:", ["Aby se vytvořila co možno nejměkčí struktura oceli", "Aby se zrekrystalizovala zrna po předchozích operacích", "Aby byly dosažena vyšší tvrdost materiálu", "Aby ocel byla co nejlacinější a dobře prodejná"], 2],
  [224, "Kalení oceli je:", ["0.18 C", "nízká teplota", "odstranění křehkosti", "tepelné zpracování pro vyšší tvrdost"], 3],
  [225, "Popouštění je:", ["nitridy", "cementit", "sycení C", "proces po kalení k odstranění křehkosti"], 3],
  [226, "Popouštění za vysokých teplot?", ["černění", "nitridování", "fosfátování", "zušlechťování"], 3],
  [227, "Popouštění se provádí v:", ["Popouštěcích pecích pomalým ohřevem materiálu", "Obloukových elektrických pecích", "V indukčních pecích", "V kyslíkovém konvertoru"], 0],
  [228, "Žíhání provádíme:", ["Abychom zlepšili vlastnosti po předchozím zpracování", "Abychom snížili obsah fosforu v oceli", "Abychom pokryli povrch součásti tenkou vrstvou, která má výborné kluzné vlastnosti", "Abychom zvýšili v oceli obsah legujících prvků"], 0],
  [229, "Žíhání rekrystalizační slouží k:", ["snížení tvrdosti", "zvýšení", "snížení pnutí", "obnovení plasticity zrna"], 3],
  [230, "Žíhání na snížení pnutí slouží:", ["plasticitě", "tažnosti", "změknutí", "snížení vnitřního pnutí"], 3],
  [231, "Žíhání na měkko se provádí v rozmezí:", ["500-550", "1150-1200", "600-620", "680–720 °C"], 3],
  [232, "Cementování provádíme pro:", ["Rm", "legury", "Re", "zvýšení obsahu uhlíku v povrchu"], 3],
  [233, "Cementování v plynné prostředí se provádí:", ["Za účelem nasycení povrchu součásti fosforem a zlepšení jeho kluzných vlastností", "Za účelem zvýšení obsahu uhlíku v povrchové vrstvě nízkouhlíkových ocelí", "Za účelem lepší obrobitelnosti", "Za účelem nasycení povrchu součásti dusíkem"], 1],
  [234, "Oceli jsou kalitelné od hodnoty:", ["0,18 %C", "0,10 %C", "0,15 %C", "0,35 %C"], 3],
  [235, "Na obrázku je kalení:", ["Plamenem", "V peci", "Plynem", "Indukční"], 3],
  [236, "Třískové obrábění je:", ["úběr", "rotační", "zrna", "úběr pomocí břitu nástroje ve formě třísek"], 3],
  [237, "Lamač třísky:", ["Vytváří stužkové smotané třísky", "Zajištuje optimální odvádění třísek", "Vytváří dlouhé šroubovité třísky", "Vytváří spirálové třísky"], 1],
  [238, "Nárůstek na řezném nástroji:", ["Je tvrdší než obráběný materiál a je schopný řezat a přebírá tak částečně funkci břitu nástroje", "Neovlivňuje geometrii řezného nástroje a neovlivňuje jakost obrobené plochy", "Vzniká pokud je při obrábění použito hodně procesní kapaliny", "Vzniká nejvíce, pokud se obrábí litiny"], 0],
  [239, "Frézování obvodem nástroje dělíme:", ["Na frézování pro výrobu drážek na pero", "Na soustředné a nesoustředné", "Na frézování čelem čelní frézy", "Na sousledné a nesousledné"], 3],
  [240, "Podstata vrtání je:", ["odjehlení", "vystružení", "zahlubování", "zhotovování děr"], 3],
  [241, "Na obrázku je znázorněno:", ["Sousledné frézování", "Řezání", "Nesousledné frézování", "Broušení"], 2],
  [242, "Na obrázku vidíme:", ["Frézování „T“ drážky", "Frézování rybinové drážky", "Frézování nesouměrné drážky", "Frézování pravoúhlé drážky"], 2],
  [243, "Na obrázku vidíme:", ["Frézovací hlavu", "Frézu pro výrobu drážek na pero", "Frézu válcovou čelní pro výrobu drážek na pero", "Frézu tvarovou půlkruhovou vydutou nástrčnou"], 3],
  [244, "Na obrázku vidíme upínání:", ["Upínání obrobků na trn", "Upínání obrobku na úhelník", "Upínání tříčelisťovým sklíčidlem", "Upínání mezi hroty"], 0],
  [245, "Na obrázku vidíš nástroj pro:", ["Měkké materiály", "Velmi křehké materiály", "Tvrdé materiály", "Středně tvrdé materiály"], 2],
  [246, "Na obrázku vidíš:", ["Korunkový (trepanační) vrták", "Kopinatý vrták", "Stupňovitý vrták", "Dělový vrták"], 2],
  [247, "Na čele nástroje na obrázku je:", ["tříska", "drážka", "svar", "nárůstek"], 3],
  [248, "Na obrázku vidíš:", ["Popouštění", "Řezání laserem", "Povrchové kalení plamenem", "Kalení indukcí"], 2],
  [249, "Na obrázku je znázorněna dvojice drážek:", ["Rádiusová a modulová", "Pravoúhlá a do tvaru „T“", "Drážka rybinová a pravoúhlá", "Rádiusová a modulová"], 2],
  [250, "Na obrázku vidíš výrobu drážek frézováním. Je zde použit nástroj:", ["Dvojice kotoučových fréz upnutých na společném trnu", "Dvoubřitá fréza", "Korunková fréza", "Úhlová fréza"], 0]
];
