
export const part1 = [
  [1, "Nástrojové úhly – platí α, β, γ, δ jsou úhly:", ["α čela, β břitu, γ hřbetu, δ řezu", "α břitu, β hřbetu, γ čela, δ řezu", "α čela, β břitu, γ řezu, δ hřbetu", "α hřbetu, β břitu, γ čela, δ řezu"], 3],
  [2, "Nástrojové úhly – platí ε, χ, χ´ jsou úhly:", ["ε špičky nástroje, χ nastavení hlavního ostří, χ´ nastavení vedlejšího ostří", "ε špičky nástroje, χ nastavení vedlejšího ostří, χ´ nastavení hlavního ostří", "ε řezu, χ nastavení hlavního ostří, χ´ nastavení vedlejšího ostří", "ε čela, χ´nastavení hlavního ostří, χ nastavení vedlejšího ostří"], 3],
  [3, "Nástrojové úhly - δ je úhel řezu a platí:", ["δ = γ + β", "δ = α + β", "δ = α + ε", "δ = α + γ"], 1],
  [4, "Kinematika obrábění – hlavní řezný pohyb při soustružení je:", ["přímočarý vratný nástroje", "rotační obrobku", "rotační nástroje", "posuvný obrobku"], 1],
  [5, "Kinematika obrábění – hlavní řezný pohyb při frézování je:", ["posuvný obrobku", "rotační obrobku", "přímočarý vratný nástroje", "rotační nástroje"], 3],
  [6, "Kinematika obrábění – hlavní řezný pohyb při obrážení je:", ["rotační obrobku", "přímočarý vratný obrobku", "přímočarý vratný nástroje", "posuvný obrobku"], 2],
  [7, "Kinematika obrábění – hlavní řezný pohyb při hoblování je:", ["přímočarý vratný nástroje", "posuvný nástroje", "rotační obrobku", "přímočarý vratný obrobku"], 3],
  [8, "Kinematika obrábění – hlavní řezný pohyb při broušení je:", ["rotační nástroje", "přímočarý vratný obrobku", "rotační obrobku", "přímočarý vratný nástroje"], 0],
  [9, "Kinematika obrábění – hlavní řezný pohyb při vrtání je:", ["posuvný nástroje", "posuvný obrobku", "rotační obrobku", "rotační nástroje"], 3],
  [10, "Nástrojové oceli jsou:", ["nelegované, legované, rychlořezné, na lité nástroje", "slinuté karbidy, legované, rychlořezné, technické diamanty", "technické diamanty, nelegované, rychlořezné, na lité nástroje", "technické diamanty, legované, rychlořezné, na lité nástroje"], 0],
  [11, "Tvrdé řezné materiály jsou:", ["slinuté karbidy, nelegované oceli, technické diamanty, kubický nitrid boru", "slinuté karbidy, keramické materiály, legované oceli, kubický nitrid boru", "slinuté karbidy, keramické materiály, technické diamanty, legované oceli", "slinuté karbidy, keramické materiály, technické diamanty, kubický nitrid boru"], 3],
  [12, "Tříska tvářená plynulá nebo tvářená článkovitá je charakteristická pro:", ["křehké nekovové materiály", "křehké kovové materiály", "sklo, dřevo", "houževnaté materiály"], 3],
  [13, "Tříska elementární vytrhávaná je charakteristická pro:", ["houževnaté kovové materiály", "houževnaté nekovové materiály", "slitiny hliníku", "sklo, porcelán"], 0],
  [14, "Největší vliv na drsnost obrobené plochy má:", ["řezná rychlost", "geometrie břitu", "posuv", "řezné prostředí"], 2],
  [15, "Tepelná bilance obrábění nám říká:", ["teplo vzniklé při obrábění je rovno teplu, které někam odchází", "teplo vzniklé při obrábění nikam neodchází", "teplo vzniklé při obrábění je menší než teplo, které někam odchází", "teplo vzniklé při obrábění je větší než teplo, které někam odchází"], 0],
  [16, "Teplo, které při obrábění vzniká, odchází do:", ["třísky, obrobku, nástroje, okolí", "třísky, nástroje, obrobku", "nástroje, třísky, prostředí", "nástroje, okolí, třísky"], 0],
  [17, "Rozdělení soustružnických nožů podle materiálu břitu:", ["přímé a ohnuté nože", "nože z rychlořezné oceli, slinutého karbidu, kubického nitridu bóru", "nože levé, pravé, souměrné", "ubírací, zapichovací, závitové, tvarové nože"], 1],
  [18, "Vyměnitelné břitové destičky:", ["mívají více břitů a nepřeostřují se", "mívají více břitů a přeostřují se", "mívají jeden břit a přeostřují se", "mívají jeden břit a nepřeostřují se"], 0],
  [19, "Otáčení obrobku pomocí SRDCE je nutné při upnutí:", ["do univerzálního sklíčidla", "na lícní desku", "mezi hroty", "do kleštin"], 2],
  [20, "Nejpřesnější upnutí obrobku při soustružení je:", ["do univerzálního sklíčidla", "do kleštin", "na lícní desku", "mezi hroty"], 3],
  [21, "LUNETY slouží k:", ["k podpoře dlouhých součástí a umisťují se na konec součásti", "k měření součástí", "k podpoře dlouhých součástí a umisťují se doprostřed součásti", "k přenosu točivého momentu"], 2],
  [22, "Soustružení – upínání na lícní desku je určeno pro:", ["tvarově složité součásti", "dlouhé součásti", "nástroje ze slinutých karbidů", "tvarové nástroje"], 0],
  [23, "Soustruhy ČELNÍ jsou určeny pro:", ["dlouhé součásti velkých průměrů", "dlouhé součásti malých průměrů", "krátké součásti malých průměrů", "krátké součásti velkých průměrů"], 3],
  [24, "Svislé soustruhy – KARUSELY jsou určeny pro:", ["velké, těžké obrobky a mají svislou osu otáčení", "malé, lehké obrobky a mají vodorovnou osu otáčení", "malé, lehké obrobky a mají svislou osu otáčení", "velké, těžké obrobky a mají vodorovnou osu otáčení"], 0],
  [25, "Poloautomatické soustruhy mají automatický pracovní cyklus:", ["kromě upnutí a odepnutí obrobku", "včetně upnutí a odepnutí obrobku", "včetně upnutí obrobku", "kromě upnutí obrobku"], 0],
  [26, "Automatické soustruhy mají automatický pracovní cyklus:", ["včetně upnutí a odepnutí obrobku", "kromě upnutí obrobku", "kromě upnutí a odepnutí obrobku", "včetně upnutí obrobku"], 0],
  [27, "Soustružení – řezná rychlost vc = (π·D·n)⁄1000 (mmin-1), kde D znamená průměr obrobku:", ["před obrobením – jednotky metry", "po obrobení – jednotky metry", "před obrobením – jednotky milimetry", "po obrobení – jednotky milimetry"], 2],
  [28, "Při soustružení na hrubo platí – Ra volím:", ["o stupeň větší (horší) jak na výkrese a nechávám max přídavek na obrábění", "stejné jako na výkrese a nechávám min přídavek na obrábění", "o stupeň větší (horší) jak na výkrese a nechávám min přídavek na obrábění", "o stupeň menší (lepší) jak na výkrese a nechávám min přídavek na obrábění"], 2],
  [29, "Jaký je rozdíl mezi VRTÁNÍM a VYVRTÁVÁNÍM?", ["vyvrtáváme i vrtáme do plného materiálu", "vrtáme do plného materiálu a vyvrtáváme do před chystané díry", "vyvrtáváme do plného materiálu a vrtáme do před chystané díry", "vyvrtáváme i vrtáme do před chystané díry"], 1],
  [30, "KOPINATÉ vrtáky:", ["mají špatný odvod třísky, používají se na vrtání krátkých děr velkých průměrů", "mají dobrý odvod třísky, používají se na vrtání dlouhých děr velkých průměrů", "mají špatný odvod třísky, používají se na vrtání krátkých děr malých průměrů", "mají dobrý odvod třísky, používají se na vrtání dlouhých děr malých průměrů"], 1],
  [31, "ŠROUBOVITÝ vrták pro vrtání oceli a litiny má úhel špičky nástroje roven:", ["90°", "118°", "100°", "145°"], 1],
  [32, "ŠROUBOVITÝ vrták z rychlořezné oceli má:", ["dvě hlavní ostří a jedno příčné", "jedno hlavní ostří a dvě příčné", "dvě hlavní ostří a dvě příčné", "jedno hlavní ostří a jedno příčné"], 0],
  [33, "Při broušení ŠROUBOVITÉHO vrtáku z rychlořezné oceli dochází ke změně jeho:", ["délky i průměru", "délky", "nepřebrušuje se", "průměru"], 1],
  [34, "Sdružené vrtáky se používají:", ["v kusové výrobě, protože jsou hodně náročné na broušení", "v hromadné výrobě, protože jsou málo náročné na broušení", "v hromadné výrobě z důvodu úspory výrobního času", "v kusové výrobě, z důvodu dlouhého výrobního času"], 2],
  [35, "VRTAČKA STOLNÍ se používá přibližně do vrtaného průměru:", ["80 mm", "40 mm", "16 mm", "100 mm"], 2],
  [36, "VRTAČKA SLOUPOVÁ se používá přibližně do vrtaného průměru:", ["100 mm", "40 mm", "80 mm", "16 mm"], 1],
  [37, "VRTAČKA STOJANOVÁ se používá přibližně do vrtaného průměru:", ["40 mm", "100 mm", "80 mm", "16 mm"], 2],
  [38, "VRTAČKA RADIÁLNÍ se používá přibližně do vrtaného průměru:", ["40 mm", "16 mm", "80 mm", "100 mm"], 3],
  [39, "Pro vrtání děr vysokou přesností (IT2-5) a přesnou roztečí použiji vrtačku:", ["Sloupovou", "Stojanovou", "Souřadnicovou", "Stolní"], 2],
  [40, "SOUSLEDNÉ frézování:", ["dochází k většímu opotřebení břitu nástroje než u nesousledného frézování", "zub frézy zabírá v místě maximální tloušťky třísky", "má horší kvalitu obrobené plochy než u nesousledného frézování", "zub frézy zabírá z nulové třísky"], 1],
  [41, "NESOUSLEDNÉ frézování:", ["zub frézy zabírá v místě maximální tloušťky třísky", "dochází k menšímu opotřebení břitu nástroje než u sousledného frézování", "má lepší kvalitu obrobené plochy než u sousledného frézování", "zub frézy zabírá z nulové třísky"], 3],
  [42, "Rozdělení fréz podle umístění břitu je např:", ["celistvé, skládané, s vyměnitelnými břitovými destičkami", "válcové, čelní, tvarové, kuželové", "s přímými zuby, se zuby ve šroubovici", "stopkové, nástrčné"], 1],
  [43, "Rozdělení fréz podle upínání je:", ["stopkové, nástrčné", "celistvé, skládané, s vyměnitelnými břitovými destičkami", "s přímými zuby, se zuby ve šroubovici", "válcové, čelní, tvarové"], 0],
  [44, "Rozdělení fréz podle konstrukce je:", ["s přímými zuby, se zuby ve šroubovici", "celistvé, skládané, s vyměnitelnými břitovými destičkami", "stopkové, nástrčné", "válcové, čelní, tvarové"], 1],
  [45, "Nástrčné frézy se upínají:", ["do svěráku", "na trn, točivý moment se přenáší většinou perem", "ozubeným kolem", "do sklíčidla"], 1],
  [46, "Točivý moment u nástrčné frézy se přenáší:", ["tvarovým spojem, většinou perem", "ozubeným kolem", "srdcem", "kolíkem"], 0],
  [47, "Frézky", ["jsou přípravky pro frézování", "jsou nástroje na frézování", "jsou etalony pro frézování", "jsou stroje na frézování"], 3],
  [48, "U vodorovné konzolové frézky je vřeteno:", ["kolmé na pracovní stůl", "pod úhlem 60°k pracovnímu stolu", "rovnoběžné s pracovním stolem", "pod úhlem 30°k pracovnímu stolu"], 2],
  [49, "U svislé konzolové frézky je vřeteno:", ["pod úhlem 60°k pracovnímu stolu", "kolmé na pracovní stůl", "rovnoběžné s pracovním stolem", "pod úhlem 30°k pracovnímu stolu"], 1],
  [50, "U rovinné frézky se pracovní stůl pohybuje pouze:", ["ve svislém směru", "ve svislém i podélném směru", "v šikmém směru", "v podélném směru"], 3],
  [51, "Při výrobě ozubených kol dělícím způsobem, upínáme do dělícího přístroje:", ["nástroj", "nic, nepotřebujeme ho", "obrobek", "můžeme obrobek i nástroj"], 2],
  [52, "Hoblovací nože jsou podobné:", ["soustružnickým nožům", "frézám", "brusným kotoučům", "vrtákům"], 0],
  [53, "Obrážecí nože jsou podobné:", ["vrtákům", "frézám", "brusným kotoučům", "soustružnickým nožům"], 3],
  [54, "Protahování a protlačování slouží k obrábění", ["pouze vnitřních rovinných ploch nebo tvarových přímkových ploch", "pouze vnějších přímkových tvarových ploch", "vnitřních i vnějších rovinných nebo tvarových přímkových ploch", "pouze vnějších rovinných ploch nebo tvarových přímkových ploch"], 2],
  [55, "Protahovací trn je:", ["jednobřitým nástrojem používaným v kusové výrobě", "vícebřitým nástrojem používaným v kusové výrobě", "jednobřitým nástrojem používaným v sériové a hromadné výrobě", "vícebřitým nástrojem používaným v sériové a hromadné výrobě"], 3],
  [56, "Brusný kotouč je složen pouze z:", ["brusiva, pojiva a pórů", "brusiva a pojiva", "brusiva a pórů", "brusiva"], 0],
  [57, "Při broušení je v záběru:", ["jeden břit, který odebírá třísky různých velikostí", "velké množství břitů, které odebírají třísky různých velikostí", "jeden břit, který odebírá třísky různých velikostí", "velké množství břitů, které odebírají třísky jedné velikosti"], 1],
  [58, "Volná brusná zrna najdeme u:", ["brusných pláten", "brusných kotoučů", "brusných past", "brusných kamenů"], 2],
  [59, "Vázaná brusná zrna najdeme u:", ["brusného prášku", "brusné pasty", "brusných papírů", "brusné kapaliny"], 2],
  [60, "Pro tvrdý obrobek volíme brusný kotouč:", ["měkčí", "ještě tvrdší", "žádný, nelze brousit", "stejně tvrdý"], 0],
  [61, "Pro měkký obrobek volíme brusný kotouč:", ["je to jedno, jaký zvolím", "ještě měkčí", "tvrdší", "stejně měkký"], 2],
  [62, "Při broušení předcházím chvění a tím zhoršení obrobeného povrchu:", ["volbou tvrdšího kotouče", "volbou měkčího kotouče", "upnutím brusného kotouče do papírových podložek", "vyvažováním brusného kotouče"], 3],
  [63, "Planetové broušení použiji:", ["pro velké obrobky", "pro malé obrobky", "místo broušení zápichového", "místo broušení rovinného"], 0],
  [64, "Při jemném soustružení mám:", ["vysokou řeznou rychlost", "velkou hloubku třísky", "velký posuv", "malou řeznou rychlost"], 0],
  [65, "Při jemném frézování mám:", ["vysokou řeznou rychlost", "velký posuv", "velkou hloubku třísky", "malou řeznou rychlost"], 0],
  [66, "Při honování vykonává nástroj:", ["pouze přímočarý vratný pohyb", "otáčivý i přímočarý vratný pohyb", "pouze otáčivý pohyb", "pouze posuvný pohyb"], 1],
  [67, "Honování je v podstatě:", ["broušení velkou řeznou rychlostí bez přívodu chladící kapaliny", "broušení velkou řeznou rychlostí za vydatného přívodu chladící kapaliny", "broušení malou řeznou rychlostí bez přívodu chladící kapaliny", "broušení malou řeznou rychlostí za vydatného přívodu chladící kapaliny"], 3],
  [68, "Honovat můžeme pouze:", ["vnitřní rotační plochy", "vnitřní rovinné plochy", "vnitřní i vnější rotační i rovinné plochy", "vnitřní rotační i rovinné plochy"], 3],
  [69, "Co neopravujeme honováním:", ["ovalitu", "souosost", "kuželovitost", "vlnitost ploch"], 1],
  [70, "Lapovat můžeme:", ["ručně i strojně", "pouze strojně", "pouze ručně", "pouze strojně, ostrým nástrojem"], 0],
  [71, "Lapování nám umožňuje pouze:", ["přesné rozměry a tvar", "vysokou jakost obrobeného povrchu, přesné rozměry a tvar", "vysokou jakost obrobeného povrchu a přesný tvar", "vysokou jakost obrobeného povrchu a přesné rozměry"], 1],
  [72, "Lapovací nástroj:", ["je tvořen brusnými zrny rozptýlenými v pastě", "je tvořen brusnými zrny rozptýlenými v kapalině", "má negativní tvar lapované plochy", "má tvar lapované plochy"], 2],
  [73, "Superfinišovací kámen koná pouze:", ["kmitavý pohyb", "přímočarý pohyb", "kmitavý a zároveň přímočarý pohyb", "rotační a zároveň přímočarý pohyb"], 2],
  [74, "Superfinišováním lze obrábět pouze:", ["plasty, hliník a měď", "sklo a litiny", "všechny druhy materiálů", "oceli a litiny"], 3],
  [75, "Superfinišovat můžeme pouze:", ["vnější rotační i rovinné plochy", "vnitřní rotační i rovinné plochy", "vnitřní rovinné plochy", "vnitřní i vnější rotační i rovinné plochy"], 0],
  [76, "Superfinišováním zlepšujeme kvalitu obrobeného povrchu:", ["tvarovou přesnost nezlepšujeme", "i tvarovou přesnost kromě souososti", "i válcovitost a kruhovitost", "i všechnu geometrickou přesnost"], 1],
  [77, "Leštění odstraní nečistoty, drobné nerovnosti a zlepšuje pouze:", ["vzhled", "geometrickou a rozměrovou přesnost", "vzhled a rozměrovou přesnost", "vzhled a geometrickou přesnost"], 0],
  [78, "Leštění nepoužíváme před:", ["niklováním", "nátěrem", "chemickou ochranou povrchu", "chromováním"], 1],
  [79, "Při omílání máme v omílacím bubnu pouze:", ["abrazivní materiál a obrobky", "aktivní kapalinu a abrazivní materiál", "aktivní kapalinu, abrazivní materiál a obrobky", "aktivní kapalinu a obrobky"], 2],
  [80, "Omíláním zlepšujeme:", ["drsnost povrchu a přesnost rozměru", "drsnost povrchu", "přesnost rozměru a tvaru", "drsnost povrchu a přesnost rozměru a tvaru"], 1],
  [81, "Válečkováním dochází v povrchové vrstvě ke zvýšení:", ["pevnosti, tvrdosti a vzniku příznivých tlakových napětí", "pouze tvrdosti a vzniku příznivých tlakových napětí", "pouze pevnosti a tvrdosti", "pouze pevnosti a vzniku příznivých tlakových napětí"], 0],
  [82, "Kuličkováním dochází v povrchové vrstvě ke zvýšení:", ["pouze pevnosti a vzniku příznivých tlakových napětí", "pouze tvrdosti a vzniku příznivých tlakových napětí", "pevnosti, tvrdosti a vzniku příznivých tlakových napětí", "pouze pevnosti a tvrdosti"], 2],
  [83, "Podle kinematiky obrábění ozubených kol rozdělujeme výrobu na:", ["protahování a tváření", "obrážení a frézování", "dělícím a odvalovacím způsobem", "soustružení a frézování"], 2],
  [84, "Při výrobě ozubených kol dělícím způsobem je v dělícím přístroji upnut:", ["nástroj i obrobek", "měřidlo", "obrobek", "nástroj"], 2],
  [85, "Frézování ozubených kol dělícím způsobem se provádí", ["pouze tvarovou stopkovou frézou", "pouze tvarovou nástrčnou frézkou", "tvarovou stopkovou nebo tvarovou nástrčnou frézou", "tvarovou stopkovou nebo tvarovou nástrčnou frézkou"], 2],
  [86, "Při obrážení ozubených kol dělícím způsobem má nástroj:", ["tvar zubové mezery a upíná se do dělícího přístroje", "tvar zubu ozubeného kola a upíná se do dělícího přístroje", "tvar zubu ozubeného kola, do dělícího přístroje se upíná obrobek", "tvar zubové mezery, do dělícího přístroje se upíná obrobek"], 0],
  [87, "Při obrážení odvalovacím způsobem je nástrojem:", ["kotoučová nebo stopková odvalovací fréza", "pouze kotoučový obrážecí nůž", "pouze hřebenový obrážecí nůž", "kotoučový nebo hřebenový obrážecí nůž"], 3],
  [88, "Výroba ozubených kol protahováním je určena pro:", ["hromadnou výrobu, obrobek je upnut v dělícím přístroji", "hromadnou výrobu, nástroj je upnut v dělícím přístroji", "kusovou výrobu, nástroj je upnut v dělícím přístroji", "kusovou výrobu, obrobek je upnut v dělícím přístroji"], 1],
  [89, "Dokončovací operace čelních ozubených kol NENÍ:", ["ševingování", "lapování", "jemné soustružení", "broušení"], 2],
  [90, "Ševingování je vhodná:", ["hrubovací operace pro nekalená kola", "dokončovací operace pro nekalená kola", "hrubovací operace pro kalená kola", "dokončovací operace pro kalená kola"], 1],
  [91, "Na obrázku je příklad upnutí obrobku pomocí:", ["pravoúhlé upínky s vačkou", "upínky s výstředníkem a opěrkou", "upínky se šroubem a opěrkou", "upínky, vačky a opěrky"], 2],
  [92, "Na obrázku je dokončovací operace výroby ozubených kol:", ["ševingováním", "zaběháváním", "lapováním", "broušením"], 0],
  [93, "Výroba ozubených kol – o jakou technologii kotoučovým nožem se jedná?", ["frézování", "obrážení", "broušení", "hoblování"], 1],
  [94, "Výroba ozubených kol – o jakou technologii kotoučovým nožem se jedná?", ["frézování", "broušení", "hoblování", "obrážení"], 3],
  [95, "Výroba ozubených kol – o jakou technologii se jedná?", ["obrážení", "hoblování", "broušení", "frézování"], 0],
  [96, "Výroba ozubených kol – o jakou technologii se jedná?", ["broušení odvalovacím způsobem", "broušení dělícím způsobem", "frézování dělícím způsobem", "frézování odvalovacím způsobem"], 3],
  [97, "Výroba ozubených kol – o jakou technologii se jedná?", ["protahování dělícím způsobem", "frézování dělícím způsobem", "protahování odvalovacím způsobem", "frézování odvalovacím způsobem"], 2],
  [98, "Výroba ozubených kol – o jakou technologii se jedná?", ["tváření odvalovacím způsobem", "tváření dělícím způsobem", "frézování dělícím způsobem", "frézování odvalovacím způsobem"], 0],
  [99, "O jakou dokončovací operaci se jedná?", ["válečkování", "superfinišování", "lapování", "honování"], 1],
  [100, "O jaký druh třísky se jedná?", ["tvářená elementární", "tvářená článkovitá", "tvářená plynulá", "vytrhávaná elementární"], 2],
  [101, "O jaký druh třísky se jedná?", ["vytrhávaná elementární", "tvářená článkovitá", "tvářená plynulá", "tvářená elementární"], 3],
  [102, "O jaký druh třísky se jedná?", ["vytrhávaná elementární", "tvářená článkovitá", "tvářená elementární", "tvářená plynulá"], 1],
  [103, "O jakou dokončovací operaci se jedná?", ["lapování", "superfinišování", "honování", "válečkování"], 2],
  [104, "O jakou dokončovací operaci se jedná?", ["honování", "lapování", "superfinišování", "válečkování"], 1],
  [105, "Na obrázku vidíme univerzální vertikální stroj na:", ["válečkování rovinných ploch", "superfinišování rovinných ploch", "honování rovinných ploch", "lapování rovinných ploch"], 3],
  [106, "O jakou dokončovací operaci se jedná?", ["válečkování", "superfinišování", "honování", "lapování"], 0],
  [107, "O jakou dokončovací operaci se jedná?", ["superfinišování", "kuličkování", "honování", "lapování"], 1],
  [108, "O jaké soustružení se jedná?", ["podélné", "čelní", "upichovací", "zapichovací"], 1],
  [109, "O jaké soustružení se jedná?", ["upichovací", "čelní", "podélné", "zapichovací"], 2],
  [110, "O jaké soustružení se jedná?", ["zapichovací čelní", "zapichovací", "čelní", "podélné"], 0],
  [111, "O jaké soustružení se jedná?", ["soustružení kuželu", "upichovací", "podélné", "zapichovací čelní"], 1],
  [112, "Na obrázku vidíme:", ["nožovou hlavu brusky", "nožovou hlavu frézky", "měřící přístroj na měření úhlů", "nožovou hlavu soustruhu"], 3],
  [113, "Revolverová hlava na obrázku slouží k upnutí:", ["nástrojů", "kalibrů", "obrobků", "měřících přístrojů"], 0],
  [114, "Na obrázku vidíme upnutí:", ["do kleštin", "na upínací lícní desku", "do sklíčidla", "mezi hroty"], 3],
  [115, "Na obrázku vidíme:", ["univerzální tříčelisťové sklíčidlo", "lunetu", "univerzální čtyřčelisťové sklíčidlo", "lícní desku"], 2],
  [116, "Na obrázku vidíme:", ["univerzální tříčelisťové sklíčidlo", "lícní desku", "lunetu", "kleštinu"], 0],
  [117, "Na obrázku vidíme upnutí obrobku:", ["do univerzálního tříčelisťového sklíčidla", "na lícní desku", "mezi hroty", "do kleštin"], 1],
  [118, "Na obrázku je univerzální hrotový soustruh - pozice 5 je:", ["sklíčidlo", "koník", "vřeteník", "suport"], 3],
  [119, "Na obrázku je univerzální hrotový soustruh - pozice 4 je:", ["převodovka", "suport", "vřeteník", "lože"], 1],
  [120, "Na obrázku je univerzální hrotový soustruh - pozice 3 je:", ["suport", "lože", "elektromotor", "převodovka"], 1],
  [121, "Na obrázku je univerzální hrotový soustruh - pozice 2 je:", ["koník", "lože", "vřeteník", "suport"], 2],
  [122, "Na obrázku je:", ["radiální vrtačka", "univerzální hrotový soustruh", "karusel", "univerzální konzolová frézka"], 1],
  [123, "Na obrázku vidíme schéma soustruhu:", ["hrotového", "revolverového", "čelního", "svislého"], 1],
  [124, "Na obrázku vidíme schéma soustruhu:", ["hrotového", "svislého", "revolverového", "čelního"], 3],
  [125, "Na obrázku je:", ["vrtací hlava", "kopinatý vrták", "dělový vrták", "šroubovitý vrták"], 2],
  [126, "Na obrázku je:", ["šroubovitý vrták", "středící vrták", "dělový vrták", "vrtací hlava"], 0],
  [127, "Na obrázku je:", ["středící vrták", "šroubovitý vrták", "vrtací hlava", "dělový vrták"], 0],
  [128, "Na obrázku je:", ["vrtací hlava", "jednoduchý dělový vrták", "trepanační vrták", "šroubovitý vrták"], 2],
  [129, "Na obrázku vidíme vrtání:", ["jednoduchým dělovým vrtákem", "šroubovitým vrtákem", "trepanačním vrtákem na jádro", "vrtací hlavou"], 3],
  [130, "Na obrázku vidíme vrtání:", ["středícím vrtákem", "jednoduchým dělovým vrtákem", "trepanačním vrtákem na jádro", "šroubovitým vrtákem"], 1],
  [131, "Na obrázku vidíme vrtání:", ["sdruženým nástrojem", "středícím vrtákem", "jednoduchým šroubovitým vrtákem", "jednoduchým dělovým vrtákem"], 0],
  [132, "Na obrázku je vrtačka:", ["sloupová", "stolní", "stojanová", "souřadnicová"], 3],
  [133, "Na obrázku je vrtačka - pozice 1 je:", ["vřeteník", "vřeteno", "sloup", "motor"], 0],
  [134, "Na obrázku je vrtačka - pozice 2 je:", ["vřeteno", "sloup", "vřeteník", "motor"], 2],
  [135, "Na obrázku je vrtačka:", ["sloupová", "stojanová", "stolní", "souřadnicová"], 0],
  [136, "Na obrázku vidíme postupně operace - z leva:", ["vrtání, vystružování, vyhrubování", "vystružování, vyhrubování, vyvrtávání", "vrtání, vyhrubování, vystružování", "vyvrtávání, vyhrubování, vystružování"], 2],
  [137, "Na obrázku vidíme frézování válcové frézy:", ["čelem - nesousledné", "obvodem - nesousledné", "čelem - sousledné", "obvodem - sousledné"], 1],
  [138, "Na obrázku vidíme frézování válcové frézy:", ["obvodem - nesousledné", "čelem - sousledné", "čelem - nesousledné", "obvodem - sousledné"], 3],
  [139, "Na obrázku je fréza:", ["nástrčná čelní", "stopková čelní", "nástrčná válcová", "nástrčná tvarová"], 2],
  [140, "Na obrázku je fréza:", ["nástrčná válcová", "stopková válcová", "nástrčná čelní", "stopková kuželová"], 1],
  [141, "Na obrázku je fréza:", ["nástrčná tvarová", "stopková válcová", "nástrčná válcová", "stopková tvarová"], 3],
  [142, "Na obrázku je fréza:", ["nástrčná kotoučová", "nástrčná tvarová", "stopková tvarová", "nástrčná válcová"], 0],
  [143, "Na obrázku je fréza s vyměnitelnými břitovými destičkami", ["čelní nástrčná", "tvarová nástrčná", "tvarová stopková", "čelní stopková"], 0],
  [144, "Na obrázku vidíme upnutí obrobku při frézování, pozice 1 je:", ["obrobek", "opěrka", "upínka", "stůl frézky"], 3],
  [145, "Na obrázku vidíme upnutí obrobku při frézování, pozice 2 je:", ["obrobek", "stůl frézky", "opěrka", "upínka"], 0],
  [146, "Na obrázku vidíme upnutí obrobku při frézování, pozice 5 je:", ["obrobek", "upínka", "stůl frézky", "opěrka"], 1],
  [147, "Na obrázku vidíme upnutí obrobku při frézování, pozice 6 je:", ["stůl frézy", "obrobek", "stůl frézky", "upínka"], 1],
  [148, "Na obrázku vidíme:", ["frézování čelem čelní frézy", "frézování obvodem tvarové frézy", "frézování čelem frézovcí hlavou", "frézování obvodem válcové frézy"], 0],
  [149, "Na obrázku vidíme:", ["frézování obvodem tvarové frézy", "frézování čelem čelní frézy", "frézování obvodem válcové frézy", "frézování čelem kuželové frézy"], 3],
  [150, "Na obrázku je konzolová frézka:", ["svislá", "portálová", "vodorovná", "vodorovně svislá"], 2],
  [151, "Na obrázku je konzolová frézka, pozice 5 je:", ["stůl", "vřeteník", "konzola", "stojan"], 1],
  [152, "Na obrázku je konzolová frézka, pozice 4 je:", ["konzola", "stůl", "stojan", "vřeteník"], 0],
  [153, "Na obrázku je konzolová frézka:", ["vodorovná", "svisle vodorovná", "svislá", "portálová"], 2],
  [154, "Na obrázku je konzolová frézka, pozice 5 je:", ["stojan", "vřeteník", "stůl", "konzola"], 2],
  [155, "Na obrázku je konzolová frézka, pozice 4 je:", ["stojan", "konzola", "vřeteník", "stůl"], 1],
  [156, "Na obrázku je konzolová frézka, pozice 1 je:", ["stojan", "vřeteník", "konzola", "stůl"], 0],
  [157, "Na obrázku je protahovací trn,kóta a je:", ["upínací část", "zadní vedení", "kalibrovací část", "řezná část"], 0],
  [158, "Na obrázku je protahovací trn,kóta c je:", ["kalibrovací část", "řezná část", "upínací část", "zadní vedení"], 1],
  [159, "Na obrázku je protahovací trn,kóta d je:", ["zadní vedení", "upínací část", "řezná část", "kalibrovací část"], 3],
  [160, "Na obrázku je protahovací trn,kóta e je:", ["upínací část", "řezná část", "kalibrovací část", "zadní vedení"], 3],
  [161, "Na obrázku vidíme:", ["kotoučový protahovák", "nástrčnou frézku", "nástrčnou frézu", "obrážecí nůž"], 0],
  [162, "Na obrázku je protahovačka:", ["svislá", "vodorovná", "kruhová", "šikmá"], 1],
  [163, "Na obrázku je protahovačka, pozice 4 je:", ["obrobek", "hydraulický válec", "píst", "protahovací trn"], 2],
  [164, "Na obrázku je protahovačka, pozice 3 je:", ["píst", "obrobek", "protahovací trn", "hydraulický válec"], 3],
  [165, "Na obrázku je protahovačka:", ["kruhová", "šikmá", "vodorovná", "svislá"], 3],
  [166, "Na obrázku je protahovačka, pozice 4 je:", ["píst", "protahovací trn", "hydraulický válec", "obrobek"], 3],
  [167, "Na obrázku je protahovačka, pozice 3 je:", ["hydraulický válec", "protahovací trn", "obrobek", "píst"], 1],
  [168, "Na obrázku je broušení:", ["bezhroté", "hloubkové", "zápichové", "planetové"], 2],
  [169, "Na obrázku je broušení:", ["bezhroté", "hloubkové", "zápichové", "planetové"], 0],
  [170, "Na obrázku je broušení rovinné:", ["brousícím pásem", "obvodem kotouče", "brousící pastou", "čelem kotouče"], 3],
  [171, "Na obrázku je broušení rovinné:", ["čelem kotouče", "brousící pastou", "brousícím pásem", "obvodem kotouče"], 3],
  [172, "Na obrázku je broušení rovinné:", ["obvodem kotouče", "brousícím pásem", "brousící pastou", "čelem kotouče"], 0],
  [173, "Na obrázku je hrotová bruska s:", ["posuvným stolem", "posuvným stojanem", "posuvným vřeteníkem", "posuvným sklíčidlem"], 0],
  [174, "Na obrázku je hrotová bruska s:", ["posuvným stojanem", "posuvným vřeteníkem", "posuvným sklíčidlem", "posuvným stolem"], 1],
  [175, "V plošně středěné krystalové mřížce krystalizují kovy", ["Měď, hliník, železo gama", "Titan, wolfram, železo alfa", "Platina, zinek, železo alfa", "Zlato, stříbro, železo alfa"], 0],
  [176, "V krystalové mřížce prostorově středěné krystalizují kovy", ["Chrom, molybden, železo alfa", "Titan, tantal, wolfram", "Měď, nikl, železo alfa", "Zlato, platina, stříbro"], 0],
  [177, "V šesterečné krystalové mřížce krystalizují", ["Lithium, zinek, vanad", "Rtuť, beryllium, magnesium", "Zinek, kobalt, titan", "Chrom, zinek, tantal"], 2],
  [178, "Co je teplotní hystereze u chladnutí a ohřevu čistých kovů", ["Jev, při kterém teplota tání čistého kovu leží výše než teplota krystalizace", "Jev, při kterém je teplota krystalizace čistého kovu výše než teplota tání", "Jev, který se vůbec nevyskytuje", "Jev, při kterém je teplota tání a teplota krystalizace stejná"], 0],
  [179, "Austenit je", ["Směs krystalů cementitu a feritu", "Tuhý roztok uhlíku v železe gama", "Směs krystalů feritu a ledeburitu", "Tuhý roztok uhlíku v železe alfa"], 1],
  [180, "Ferit je", ["Směs krystalů feritu a ledeburitu", "Směs krystalů cementitu a doprovodných prvků", "Tuhý roztok uhlíku v železe alfa", "Tuhý roztok uhlíku v železe gama"], 2],
  [181, "Teplota AC1 v diagramu Fe-Fe3C je", ["800 °C", "727 °C", "911 °C", "1400 °C"], 1],
  [182, "Segregační křivka Acm v diagramu Fe-Fe3C je", ["Křivka, na které se segregují zrna feritu", "Křivka, na které se segregují zrna cementitu", "Křivka, na které se segregují zrna austenitu", "Křivka, na které se segregují zrna čistého železa"], 1],
  [183, "Tahový diagram znázorňuje", ["Závislost napětí materiálu na poměrném prodloužení", "Tvrdost materiálu", "Měkkost materiálu", "Ohebnost materiálu na poměrném prodloužení"], 0],
  [184, "Zkušební tělísko u zkoušky tahem má tvar", ["Tyčinky s vyznačenými body před zkouškou", "Tyčinky ze speciální oceli s trojúhelníkovým průřezem", "Tyčinky, která je zpevněna plastem na obou koncích", "Tyčinky, která má libovolný tvar"], 0],
  [185, "Bod „U“ na tahovém diagramu je", ["Mez napětí, kde výslednicí ke přímka", "Mez úměrnosti, kde výslednicí je přímka", "Tento bod se v tahovém diagramu nevyskytuje", "Mez úměrnosti, kde výslednicí je lehká křivka"], 1],
  [186, "Urči, co vidíš na obrázku:", ["Žíhání na snížení pnutí", "Rekrystalizační žíhání", "Žíhání na měkko", "Normalizační žíhání"], 1],
  [187, "Bod „E“ na tahovém diagramu je", ["Mez elasticity, kde se materiál stává kapalinou", "Mez napětí, kde se materiál lehce natrhne", "Mez elasticity, kde vznikne první trhlinka, která se šíří dál", "Mez elasticity, do které se jedná o vratné deformace"], 3],
  [188, "Bod „K“ v tahovém diagramu je", ["Mez kluzu, která odpovídá hodnotě Rm se strojnických tabulkách", "Mez destrukce, kde vznikne první trhlinka, která se šíří dál", "Mez kluzu, kterému odpovídá hodnota Re ve strojnických tabulkách", "Mez napětí, kde se materiál stává kapalinou"], 2],
  [189, "Bod „P“ v tahovém diagramu je", ["Mez pevnosti, do které se jedná o vratné deformace", "Tento bod se v tahovém diagramu nevyskytuje", "Mez kluzu, která odpovídá hodnotě Re se strojnických tabulkách", "Mez pevnosti, kde vznikne první trhlinka, která se šíří dál"], 3],
  [190, "Tvárnost u kovů a jejich slitin je:", ["Deformační chování materiálu s porušením materiálu", "Teplota tvárného materiálu", "Tvrdost materiálu", "Schopnost měnit svůj tvar působením vnější síly při plastické deformaci bez přerušení celistvosti materiálu"], 3],
  [191, "Tvárnost u kovů a jejich slitin úzce souvisí s", ["Vnitřní stavbou materiálu, teplotou tvárného materiálu, druhem tvářecího procesu", "Viskozitou materiálu", "Houževnatostí materiálu", "Chemickým složením, teplotou viskózního toku, teplotou skelného přechodu"], 0],
  [192, "Zkouška rázem v ohybu se provádí kvůli", ["Zjištění objemu materiálu před zkouškou a po zkoušce", "Zjištění tvrdosti daného materiálu", "Zjištění, jaké má materiál chemické složení", "Zjištění spotřebované energie potřebné k přeražení vzorku"], 3],
  [193, "Výsledkem u zkoušky rázem v ohybu jsou jednotky", ["N", "N*m", "kWh", "J"], 3],
  [194, "U zkoušky rázem v ohybu zjišťujeme", ["Výkon", "Hodnotu tvrdosti", "Termodynamickou teplotu", "Houževnatost materiálu"], 3],
  [195, "Tvrdost je:", ["Jak je předmět nebo zkoumaná součást chemicky odolná", "Jak je součást nebo polotovar křehký", "Schopnost materiálu odolávat pronikání cizích předmětů do objemu materiálu", "Je to veličina, která se nezkoumá"], 2],
  [196, "Tvrdost se zkoumá:", ["Metodou dle Charpyho kladiva", "Metodami jen na základě empirického poznání", "Metodami dle Brinella, Rockwella a Vickerse", "Metodami dle diagramu IRA, ARA"], 2],
  [197, "Zkouška tvrdosti dle Brinella se provádí:", ["Vtlačováním diamantu do povrchu materiálu a otisk je výslednicí", "Vtlačování kubického nitridu bóru do materiálu a otisk je výslednicí", "Vtlačováním kuličky z tvrdokovu a zjišťováním průměru otisku", "Vtlačováním diamantového kužele do materiálu a výsledný otisk se vyhodnocuje dle kružnic"], 2],
  [198, "Zkouška tvrdosti dle Vickerse se provádí", ["Vtlačováním ocelové kuličky", "Vtlačováním diamantového kužele do materiálu a výsledný otisk se vyhodnocuje dle kružnic", "Vtlačováním kuličky ze slinutých karbidů", "Vtlačováním diamantového jehlanu do materiálu"], 3],
  [199, "Zápis HRC min. 63 čteme", ["Hodnota 63 jednotek na stupnici C dle Rockwella", "Hodnota tvrdosti je minimálně 63 jednotek dle Rockwella na stupnici C", "Hodnota tvrdosti 63", "Hodnota tvrdosti 63 HR"], 1],
  [200, "Výroba šedé litiny probíhá nejvíce v", ["Šachtové peci – kuplovně", "V obloukové peci", "V indukční peci", "V kyslíkové peci"], 0],
  [201, "Litina má obsah uhlíku", ["Do 2,11 %", "Nad 2,11 %", "Nad 4,3 %", "Kolem 0,657"], 1],
  [202, "V obloukové elektrické peci je dosahována teplota", ["Indukcí", "Elektrickým obloukem", "Foukáním kyslíku do taveniny", "Vířivými proudy"], 1],
  [203, "Očkování litiny magnesiem se provádí za účelem:", ["Aby byla litina levnější", "Aby byla litina těžší a získala odolnost vůči chvění", "Aby se uhlík vlivem reakce stočil do globulí a vytvořil globulární grafit", "Aby litina získala ještě větší tvrdost"], 2],
  [204, "Z litiny se vyrábí např", ["Skříně pro obráběcí stroje, stojany", "Dráty a kabely", "Kryty, dveře pro skříně s nářadím", "Navijáky, kufry, světlomety"], 0],
  [205, "Ocel 19 824 je", ["Ocel na odlitky", "Ocel uhlíková", "Ocel nízkolegovaná", "Ocel rychlořezná"], 3],
  [206, "Ocel rychlořezná je určena pro", ["Kladiva, kleště, šroubováky", "Zednické nářadí a vrtáky na dřevo", "Ruční nástroje a nářadí jako třeba nůžky na plech, razidla na mince", "Obzvláště vysoce namáhaná kovátka pro rotační kování"], 2],
  [207, "Ocel 11 373 je ocel", ["Konstrukční ocel, tavná svařitelnost obtížná", "Nerezová, vhodná pro potravinářské účely", "Konstrukční ocel nevhodná pro nosné svary", "Konstrukční ocel, tavná svařitelnost zaručena"], 3],
  [208, "Nerezová ocel 42 2905.9 se používá pro", ["Tlukadla a vysoké duté nýty", "Řezné materiály odolné proti popouštění", "Součásti vyráběné na rychloběžných automatech", "Oběžná kola a lopatky vodních turbín"], 3],
  [209, "Mechanické vlastnosti technických materiálů popisují chování při", ["Při elektrické vodivosti", "Magnetické zátěži", "Zátěži v chemickém prostředí", "Zatěžování statickými a dynamickými silami"], 3],
  [210, "Technologické vlastnosti popisují chování materiálů při", ["Zatížení na tah a tlak", "Zkouškách tvrdosti", "Technologických operacích jako např. slévatelnost, obrobitelnost", "Zatížení na ohyb a krut"], 2],
  [211, "Zařízení pro zkoušku tahem se jmenuje", ["Poldi kladívko", "Vstřikovací a řídící jednotka", "Trhací stroj", "Charpyho kladivo"], 2],
  [212, "Zápis 25 HB čteme", ["25 jednotek tvrdosti dle Rockwella na stupnici B", "25 jednotek", "25 jednotek tvrdosti dle Brinella", "25 jednotek tvrdosti dle Vickerse"], 2],
  [213, "Hodnota Re u zkoušky tahem", ["Odpovídá hodnotě vratných deformací", "Odpovídá mezi pevnosti", "Odpovídá destrukci materiálu", "Odpovídá mezi kluzu"], 3],
  [214, "Hodnota Rm u zkoušky tahem", ["Hodnotě napětí vratných deformací", "Hodnotě meze úměrnosti", "Odpovídá hodnotě, kdy ve zkušebním vzorku vznikne první trhlinka", "Hodnotě mezi kluzu"], 2],
  [215, "Oceli třídy 10 jsou určeny zejména pro", ["Hlubokotažné plechy", "Konstrukční součásti méně důležité bez nosných svarů", "Konstrukční oceli, tavná svařitelnost zaručena", "Tyče tažené zastudena"], 1],
  [216, "Nízkouhlíková ocel 12 020.1 je určena", ["Pro svařované konstrukce", "Pro nitridování a povrchovému kalení", "Pro cementování", "Pro fosfátování"], 2],
  [217, "Ocel 17 042.2 je určena", ["Pro pístní čepy a pastorky", "Pro výrobky do korozivního prostředí", "Pro kroužky valivých ložisek", "Pro výrobu podvozků letadel"], 1],
  [218, "Materiál S235JR je materiál", ["Jedná se o litinu určenou zejména na zemědělské stroje", "Jedná se o konstrukční ocel s minimální hodnotou Re 235 MPa a hodnotě 27 J nárazové práce", "Jedná se plast polyvinylchlorid", "Jedná se o konstrukční ocel s minimální hodnotou Re 27 MPa a hodnotě 235 J nárazové práce"], 1],
  [219, "Materiál GP265GH je", ["Konstrukční materiál pro všeobecné použití", "Ocel na potrubí k vedení plynu a ropy z vrtných plošin na pobřeží", "Ocel na litou tlakovou nádobu", "Vysokolegovaná ocel pro chirurgické nástroje"], 2],
  [220, "Materiál E295", ["Jedná se o ocel pro měkké výrobky tažené za studena", "Jedná se o ocel na strojní součásti", "Jedná se o ocel na potrubí", "Jedná se o ocel na kolejnice"], 3],
  [221, "Materiál HS2-9-1-8", ["Jedná se o rychlořeznou ocel s obsahem legujících prvků v pořadí 2 % wolframu, 9 % niobu, 1 % titan, 8 % kobaltu", "Jedná se o rychlořeznou ocel s obsahem legujících prvků v pořadí 2 % zirkonu, 9 % tantal, 1 % vanadu, 8 % kobaltu", "Jedná se o rychlořeznou ocel s obsahem legujících prvků v pořadí 2 % wolframu, 9 % molybdenu, 1 % vanadu, 8 % kobaltu", "Jedná se o rychlořeznou ocel s obsahem legujících prvků v pořadí 2 % wolframu, 9 % molybdenu, 1 % vanadu, 8 % niklu"], 2],
  [222, "Austenitizace oceli", ["je proces, který provádíme za účelem změknutí oceli, aby šla lépe obrábět", "je proces, který zlevňuje všechny druhy ocelí", "je proces, při kterém se obrobek zahřeje na určitou teplotu a vytvoří se austenit, který je stabilní při vysokých teplotách", "je proces, který provádíme za účelem změknutí oceli, aby šla lépe obrábět"], 2],
  [223, "Ocel kalíme", ["Aby se vytvořila co možno nejměkčí struktura oceli", "Aby se zrekrystalizovala zrna po předchozích operacích", "Aby byly dosažena vyšší tvrdost materiálu", "Aby ocel byla co nejlacinější a dobře prodejná"], 2],
  [224, "Kalení oceli je", ["Tepelné zpracování za účelem dosažení vyšší tvrdosti oceli", "Schopnost materiálu dosáhnout kalením tvrdosti i při obsahu uhlíku do 0,18 % C", "Tepelné zpracování při nízké teplotě (do 350 °C)", "Odstranění křehkosti a tvrdosti materiálu"], 0],
  [225, "Popouštění je", ["Proces, při kterém se na povrchu vytvoří velmi tenká vrstva nitridů", "Proces, při kterém se v povrchové vrstvě vytvoří cementit", "Proces, prováděný po kalení a odstraňuje křehkost a pnutí v materiálu", "Proces, při kterém se povrchu součásti dostane více uhlíku a potom se lépe popouští"], 2],
  [226, "Popouštění za vysokých teplot nazýváme:", ["Brinýrování neboli černění", "Nitridování", "Fosfátování", "Zušlechťování"], 3],
  [227, "Popouštění se provádí v", ["Popouštěcích pecích pomalým ohřevem materiálu", "Obloukových elektrických pecích", "V indukčních pecích", "V kyslíkovém konvertoru"], 0],
  [228, "Žíhání provádíme", ["Abychom zlepšili vlastnosti po předchozím zpracování", "Abychom snížili obsah fosforu v oceli", "Abychom pokryli povrch součásti tenkou vrstvou, která má výborné kluzné vlastnosti", "Abychom zvýšili v oceli obsah legujících prvků"], 0],
  [229, "Žíhání rekrystalizační slouží k", ["Snížení tvrdosti", "Ke zvýšení tvrdosti", "K obnovení plasticity zrna", "Ke snížení pnutí"], 2],
  [230, "Žíhání na snížení pnutí slouží", ["Na obnovu plasticity zrna po předchozím tažení", "Aby se zvýšila tažnost", "Aby materiál změkl", "Aby se snížilo vnitřní pnutí po předchozích operacích"], 3],
  [231, "Žíhání na měkko se provádí", ["V rozmezí teplot 500-550 °C z důvodu zlepšení obrobitelnosti", "V rozmezí teplot 1150-1200 °C z důvodu zlepšení obrobitelnosti", "V rozmezí teplot 600-620 °C z důvodu zlepšení obrobitelnosti", "V rozmezí teplot 680-720 °C z důvodu zlepšení obrobitelnosti"], 3],
  [232, "Cementování provádíme za účelem:", ["zvýšení hodnoty Rm uvedené ve strojnických tabulkách", "zvýšení obsahu legujících prvků jako titan, tantal, molybden", "zvýšení hodnoty Re uvedené ve strojnických tabulkách", "zvýšení obsahu uhlíku"], 3],
  [233, "Cementování v plynné prostředí se provádí:", ["Za účelem nasycení povrchu součásti fosforem a zlepšení jeho kluzných vlastností", "Za účelem zvýšení obsahu uhlíku v povrchové vrstvě nízkouhlíkových ocelí", "Za účelem lepší obrobitelnosti", "Za účelem nasycení povrchu součásti dusíkem"], 1],
  [234, "Oceli jsou kalitelné od hodnoty", ["0,18 %C", "0,10 %C", "0,15 %C", "0,35 %C"], 3],
  [235, "Na obrázku je kalení", ["Plamenem", "V peci", "Plynem", "Indukční"], 3],
  [236, "Třískové obrábění je", ["Odebírání materiálu pomocí břitu nástroje a přebytečný materiál odchází ve formě třísek", "Odebírání materiálu jen pomocí brusných zrn", "Odebírání materiálu, při kterém koná obrobek hlavní řezný pohyb", "Odebírání materiálu při kterém materiál odchází ve formě malých kuliček"], 0],
  [237, "Lamač třísky", ["Vytváří stužkové smotané třísky", "Zajištuje optimální odvádění třísek", "Vytváří dlouhé šroubovité třísky", "Vytváří spirálové třísky"], 1],
  [238, "Nárůstek na řezném nástroji", ["Je tvrdší než obráběný materiál a je schopný řezat a přebírá tak částečně funkci břitu nástroje", "Neovlivňuje geometrii řezného nástroje a neovlivňuje jakost obrobené plochy", "Vzniká pokud je při obrábění použito hodně procesní kapaliny", "Vzniká nejvíce, pokud se obrábí litiny"], 0],
  [239, "Frézování obvodem nástroje dělíme", ["Na frézování pro výrobu drážek na pero", "Na soustředné a nesoustředné", "Na frézování čelem čelní frézy", "Na sousledné a nesousledné"], 3],
  [240, "Podstata vrtání je", ["Odjehlení a sražení hran", "Třískové obrábění, při kterém zhotovujeme průchozí nebo neprůchozí díry", "Třískové obrábění, při kterém je materiál odebíraný mnohabřitým nástrojem...", "Zahlubování otvorů"], 1],
  [241, "Na obrázku je znázorněno", ["Sousledné frézování", "Řezání", "Nesousledné frézování", "Broušení"], 2],
  [242, "Na obrázku vidíme", ["Frézování „T“ drážky", "Frézování rybinové drážky", "Frézování nesouměrné drážky", "Frézování pravoúhlé drážky"], 0],
  [243, "Na obrázku vidíme:", ["Frézovací hlavu", "Frézu pro výrobu drážek na pero", "Frézu válcovou čelní pro výrobu drážek na pero", "Frézu tvarovou půlkruhovou vydutou nástrčnou"], 2],
  [244, "Na obrázku vidíme upínání:", ["Upínání obrobků na trn", "Upínání obrobku na úhelník", "Upínání tříčelisťovým sklíčidlem", "Upínání mezi hroty"], 2],
  [245, "Na obrázku vidíš nástroj pro:", ["Měkké materiály", "Velmi křehké materiály", "Tvrdé materiály", "Středně tvrdé materiály"], 0],
  [246, "Na obrázku vidíš", ["Korunkový (trepanační) vrták", "Kopinatý vrták", "Stupňovitý vrták", "Dělový vrták"], 0],
  [247, "Na obrázku na čele nástroje je", ["Nárůstek", "Tříska", "Drážka", "Svar"], 0],
  [248, "Na obrázku vidíš", ["Popouštění", "Řezání laserem", "Povrchové kalení plamenem", "Kalení indukcí"], 2],
  [249, "Na obrázku je znázorněna dvojice drážek", ["Rádiusová a modulová", "Pravoúhlá a do tvaru „T“", "Drážka rybinová a pravoúhlá", "Rádiusová a modulová"], 2],
  [250, "Na obrázku vidíš výrobu drážek frézováním. Je zde použit nástroj", ["Dvojice kotoučových fréz upnutých na společném trnu", "Dvoubřitá fréza", "Korunková fréza", "Úhlová fréza"], 0]
];
