
export const part3 = [
  [501, "Co znamenají v anglickém názvu písmenu USM", ["ultrasonic mix up mineral", "ultrasonic machinning", "unrealistic machinning", "ultrasonic stuck mark"], 1],
  [502, "Ultrazvuk je vlnění o frekvenci", ["mezi (17-25)kHz", "mezi (17-25) Hz", "nad 17 MHz", "do 17 kHz"], 0],
  [503, "Jeden ze dvou nástrojů pro opracování ultrazvukem je brusivo, který z materiálů se nepoužívá při tomto opracování", ["korund(Al2O3), karborundum(SiC)", "olivínový písek", "kubický nitrid bóru (BL), karborundum(SiC)", "syntetický dimant (DD), křemenný písek"], 1],
  [504, "Jak se nazývá zařízení, které převádí vlnové kmity na mechanické kmity", ["převodník, který využívá princip kapilární elevace", "převodník, který využívá princip magnetostrikce", "převodník, který využívá princip fotoelektrického jevu", "převodník, který využívá princip indukce"], 1],
  [505, "Na obrázku je stroj pro obrábění ultrazvukem. Vyber tvrzení, které správně popisuje jeho části", ["1-generátor ultrazvukových kmitů, 2-převodník(magnetostrikce) + držák nástroje 3-zařízení pro přívod+odvod brusiva v suspenzi, 4-obrobek, 5-nástroj", "1-generátor mechanických kmitů, 2- držák nástroje 3-zpodavač pro přívod+odvod suchého brusiva , 4-obrobek, 5-nástroj", "1-zdroj mechanických kmitů, 2-držák nástroje, -3-přívod+odvod brusiva v suspenzi, 4-obrobek, 5-nástroj", "1-generátor ultrazvukových kmitů, 2-držák nástroje 3-zařízení pro přívod a odvod brusiva se suspenzí sui, 4-obrobek, 5-nástroj"], 0],
  [506, "Pro obrábění pomocí ultrazvuku se používá", ["2 nástroje: jeden nástroj, který má pozitivní tvar opracované plochy, druhý nástroj který tvoří kapalina", "2 nástroje: jeden nástroj, který má negativní tvar opracované plochy, druhý nástroj který tvoří brusivo v suspenzi kapaliny", "1 nástroj,j který má negativní tvar opracované plochy a kmitá s frekvencí 25kHz za sucha", "2 nástroje: jeden nástroj, který má negativní tvar opracované plochy, druhý nástroj který tvoří suché brusivo"], 1],
  [507, "Pro obrábění pomocí ultrazvuku se požívá brusivo, které :", ["brusivo je pojené do pevného tvaru nástroje, který má negativní tvar opracované plochy a používá se kapalina pouze ke smáčení opracované plochy", "brusivo je pojené do pevného tvaru nástroje, který má negativní tvar opracované plochy a nepoužívá se kapalina", "brusivo je volné a je v suspenzi vody v poměru cca 40% brusiva/60% kapaliny", "brusivo je volné a je v suspenzi vody v poměru cca 80% brusiva/20% kapaliny"], 2],
  [508, "Při opracování ultrazvukem se využívá dějů:", ["disociace kovového obrobku způsobená průchodem el. proudu vkapalině= elektrolytu mezi nástrojem a obrobkem, elektrolyt vytváří kapalina kam se řadí voda, petrolej nebo olej.", "eroze materiálu způsobená kavitaceí praskajícíh bublinek v kapalině(voda, olej, petrolej) , bublinky vznikají za vysokého kmitání kapaliny frekvencí 17kHz", "eroze materiálu díky kmitání brusných zrn vysokou frekvencí, za současného působení kavitace praskajícíh bublinek v kapalině (voda, olej, petrolej) , bublinky vznikají za vysokého kmitání kapaliny frekvencí 17kHz", "chemické rozpouštění materiálu díky kmitání brusných zrn v kapalině která je tvořená (vodou, olejem, petrolejm)"], 2],
  [509, "Zkratka AWJM v českém překladu znamená", ["opracování ultrazvukem s abrazivem", "nanášení plazmových povlaků", "opracování vodním paprskem", "opracování vodním paprskem s abrazivem"], 3],
  [510, "Zkratka WJM znamená anglicky", ["Watter Job Machinning", "Wash Job Machinning", "Abrasive Watter Jet Machinning", "Watter Jet Machinning"], 3],
  [511, "Urči 2 materiály, které se používají jako abrazivo pro opracování AWJM", ["syntetický diamantDD, kubický nitrid bóru BL", "křemenný písek tříděný, syntetický diamant DD", "korund Al2O3,karborundum SiC", "oplový písek, kubický nitrid bóru BL"], 2],
  [512, "Na obrázku jeznázorněna technologie opracování, určete její anglickou značku", ["WJM", "AWJM", "USM", "LBM1"], 1],
  [513, "Určete, který z obrázků představuje schématicky opracování AWJM", ["a)", "d)", "b)", "c)"], 3],
  [514, "Safírová tryska na výstupu se používá pro řezání v trysce pro technologii, která má zkratku:", ["AWJM", "USM", "WJM", "LBM1"], 2],
  [515, "Při řezání vodním paprskem se :", ["může a nemusí počítat s technologickým přídavkem, u slabých materiálů je úkos do 2o(stupeň), u silnějších materiálů se musí počítat s úkosem od (2 -6)o (stupeň)", "musí počítat s přídavkem na obrábění, který vzniká technologickým úkosem (6-10)o (stupeň)", "nepočítá s přídavkem na obrábění, vzniká úkos jen do hodnoty 0,6o(stupeň)", "nepočítá s přídavkem na obrábění, nevzniká žádný úkos"], 0],
  [516, "Na obrázku je zařízení, označené otazníkem, které se používá u řezání vodním paprskem , jak se jmenuje", ["lapač a separátor třísek, které vzniknou řezáním vodním paprskem", "stator, ve kterém se vyrábí keramické kuličky abrazivním účinkem kinetické energie vodního paprsku", "lapač kinetické energie vodního paprsku při dokončení řezání materiálu vodním paprskem", "zařízení pro filtraci vody k zpětnému využití v řezání vodním paprskem"], 2],
  [517, "Na obrázku je shéma zařízení pro opracování technologií AWJM. Určete správný popis jednotlivých popzic", ["1-safírová tryska, 2-výstupní tryska ze slinutých karbidů, 3-zásobník, 4-uzávěr zásobníku, 5-spalovací komůrka, 6-obrobek", "1-safírová tryska, 2-výstupní tryska ze slinutých karbidů, 3-zásobník, 4-uzávěr zásobníku, 5-směšovací komůrka, 6-obrobek", "1-vstupní tryska, 2-výstupní tryska-obě z wolframu, 3-zásobník prekurzoru, 4- havarijní uzávěr zásobníku, 5-tavící komůrka pro prekurzor, 6-obrobek", "1- tryska ze slinutých karbidů , 2-výstupní safírová tryska, 3-zásobník, 4-uzávěr zásobníku, 5-směšovací komůrka, 6-obrobek"], 1],
  [518, "Na obrázku jeznázorněný řezací stroj. Určete technologie opracování, pro kterou je určen a její anglickou značku", ["řezání vodním paprskem, WJM", "řezání vodním paprskem s abrazivem, AWJM", "řezání plazmou, PBM", "řezání laserem, LBM"], 1],
  [519, "Na obrázku je krystalická mřížka, o který typ mřížky se jedná", ["šesterečná (hexagonální) krystalová mřížka plošně středěná (plošně centrovaná)", "šesterečná (hexagonální) krystalová mřížka prostorově středěná (prostorově centrovaná)", "krychlová (kubická) krystalová mřížka plošně středěná (plošně centrovaná)", "krychlová (kubická) krystalová mřížka prostorově středěná (prostorově centrovaná)"], 3],
  [520, "Na obrázku je bodová porucha v krystalové mřížce, o jakou poruchu se jedná", ["prostorová dislokace mřížky", "intersticiálně umístěný atom v meziprostoru mřížky", "cizí atom umístěný v uzlovém bodu mřížky", "vakantní místo v krystalové mřížce"], 3],
  [521, "Na obrázku je bodová porucha v krystalové mřížce, o jakou poruchu se jedná", ["intersticiálně umístěný atom v meziprostoru mřížky", "nejedná se o žádnou poruchu v krystalové mřížce", "vakantní místo v krystalové mřížce", "cizí atom umístěný v uzlovém bodu mřížky"], 0],
  [522, "Na obrázku je teplota tání a tuhnutí nepolymorfního kovu – vyznačte, jaký název má hodnota 'r'", ["teplotní hystereze u nepolymorfního kovu", "průběh teplotního gradientu nepolymorfního kovu u tavení", "objemový rozdíl u polymorfního kovu", "průběh teplotního gradientu nepolymorfního kovu u tuhnutí"], 3],
  [523, "Co znamená slovo 'polyformie kovů'", ["krystalizace kovů v jediné krystalové mřížce", "krystalizace kovů jen ve dvou krystalových mřížkách při stejné teplotě", "krystalizace kovů jen ve dvou krystalových mřížkách při rozdílné teplotě a různém tlaku", "krystalizace kovů v různé krystalové mřížce při různých teplotách"], 3],
  [524, "Na obrázku je znázorněná", ["polymorfie zinku", "polymorfie železa", "difuze železa", "dislokace železa"], 1],
  [525, "Na obrázku je binární diagram kovů rozpustných v tekutém a nerozpustných v tuhém stavu", ["C-3", "A-1", "D-3", "B-2"], 0],
  [526, "Na obrázku je binární diagram kovů rozpustných v tekutém a nerozpustných v tuhém stavu", ["písmeno B", "písmeno C", "písmeno A", "písmeno E"], 3],
  [527, "Na obrázku je binární diagram kovů rozpustných v tekutém a nerozpustných v tuhém stavu", ["číslice 4 = eutektikum a krystaly látky B", "číslice 2 = eutektikum a krystaly látky A", "číslice 1 = čistá látka A", "číslice 2 = eutektikum + krystaly látky B"], 0],
  [528, "Na obrázku je binární diagram dvou látek", ["Látka A a B, které jsou nerozpustné v tekutém a nerozpustné tuhém stavu", "Látka A a B, které jsou rozpustné v tekutém stavu částečně rozpustné v tuhém stavu", "Látka A a B, které jsou ideálně rozpustné v tekutém stavu a zcela nerozpustné v tuhém stavu", "Látka A a B, které jsou ideálně rozpustné v tekutém a ideálně rozpustné v tuhém stavu"], 2],
  [529, "Na obrázku je binární diagram kovů rozpustných v tekutém a tuhém stavu, urči správnou křivku tuhnutí pro 20%A+80%B", ["žádná křivka neodpovídá zadání", "A", "B", "C"], 2],
  [530, "Binární diagram Fe-Fe3C je diagram", ["stabilní", "neurčitý", "nestabilní", "polostabilní"], 3],
  [531, "Binární diagram Fe-Fe3C má správný název", ["železo-grafit", "kov-karbid železo-ferit", "uhlíku", "železo-karbid železa"], 3],
  [532, "Binární diagram Fe-Fe3C má na ose x koncentrace uhlíku – které hodnoty jsou správné?", ["0,78–2,14–4,6 (%C)", "0,76–2,14–6,80 (%C)", "0,76–2,11–4,2 (%C)", "0,008–2,11–4,2 (%C)"], 2],
  [533, "Koncentrace uhlíku v binárním diagramu FeFe3C, který představuje eutektoidní bod S, je", ["6,3%C", "0,76%C", "2,11%C", "4,2%C"], 1],
  [534, "Teplota Ac1 v binárním diagramu Fe-Fe3C je", ["911°C", "1538°C", "727°C", "1127°C"], 2],
  [535, "A = austenit, je", ["intersticiální tuhý roztok uhlíku v železe modifikace γ (Fey)", "substituční tuhý roztok uhlíku v železe modifikace γ (Fey)", "směs cementitu a feritu v poměru 7:1", "intersticiální tuhý roztok uhlíku v železe modifikace α (Fea)"], 0],
  [536, "F = ferit, vyber možnost a 2 vlastnosti feritu", ["intersticiální tuhý roztok uhlíku v železe modifikace α (Fea), velmi tvrdý, křehký", "intersticiální tuhý roztok uhlíku v železe modifikace α (Fea), houževnatý, nemagnetický", "intersticiální tuhý roztok uhlíku v železe modifikace α (Fea), měkký, magnetický", "substituční tuhý roztok uhlíku v železe γ (Fey), nemagnetický, středně pevný"], 2],
  [537, "Perlit je", ["tuhý roztok uhlíku v železe modifikace γ (Fey), koncentrace uhlíku 87,5%C", "směs (eutektikum) tvořená jemnými krystalky austenitu a cementitu v poměru 7:1", "tuhý roztok uhlíku v železe modifikace α (Fea), koncentrace uhlíku 12,5%C", "směs (eutektoid) tvořená jemnými krystalky feritu a cementitu v poměru 7:1"], 3],
  [538, "Binární diagram Fe-C je stabilní diagram, podle kterého tuhnou litiny. Urči výslednou strukturu litiny", ["grafit + austenit", "grafit + grafitový eutektoid", "cementit + grafitový eutektoid", "grafit + austenit + grafitové eutektikum"], 1],
  [539, "U metody svařování TIG se používá", ["Netavící se elektroda", "Obalovaná elektroda", "Trubičková tavící se elektroda", "Tavící se elektroda"], 0],
  [540, "Které ochranné plyny se používají u metody svařování TIG", ["Kyslík, Dusík", "Dusík, Acetylén", "Argon, Helium", "CO2, Kyslík"], 2],
  [541, "Pro svařovací metodu MAG se používá výhradně:", ["Střídavý proud", "žádný proud - jedná se hořící plynovou náplň v hořáku", "Stejnosměrný proud", "Střídavý i stejnosměrný proud"], 2],
  [542, "Jaká je teplota varu wolframové elektrody u metody TIG", ["1500°C", "57000°C", "3700°C", "5700°C"], 3],
  [543, "Které tvrzení je pravdivé?", ["Přívodní armatury kyslíkových lahví musí být suché bez oleje.", "Plamenem nelze svařovat ve všech polohách. Vhodné pouze pro svařování ve vodorovné poloze", "Acetylen je rozpuštěn v argonu, protože při velkém stlačení by došlo k explozi", "Bodové svařování je možné použít pouze pro plasty"], 0],
  [544, "Mezi tavné svařování nepatří", ["Svařování plamenem", "Svařování obalovanou elektrodou", "Svařování netavnou elektrodou v ochranném plynu", "Bodové svařování"], 3],
  [545, "Dobrou svařitelnost u legovaných ocelí ovlivňuje", ["Obsah uhlíku musí být větší jak 0,5%", "Dosahovaná tvrdost materiálu", "Teplota svařovacího agregátu", "Obsah uhlíku menší jak 0,2%"], 3],
  [546, "Ekvivalentní obsah ulhíku hraje roli pro svařitelnost", ["Plastů", "Hliníku a neželezných kovů", "Legovaných ocelí", "Nelegovaných ocelí"], 2],
  [547, "Metoda svařování, kdy mezi dvěma elektrodami dojde pod tlakem bez přídavného materiálu k roztavení a svaření dvou materiálů se nazývá:", ["Bodové svařování", "Svařování metodou MAG", "Svařování plasmou", "svařování elektrickým obloukem"], 0],
  [548, "Jako inertní plyn se při svařování metodou MIG používá", ["Oxid uhličitý", "Helium", "Kyslík", "Vzduch"], 1],
  [549, "Jak se nazývá spojování kovů působením tepla, kdy dochází k natavení základního i přídavného materiálu?", ["Letování", "Svařování", "Lisování", "Pájení"], 3],
  [550, "Co je hlavním účelem svarového spoje?", ["Umožnit snadnou demontáž", "Zvýšit tvrdost povrchu", "Zlepšit estetiku výrobku", "Trvale spojit součásti"], 3],
  [551, "Jak se nazývá oblast základního materiálu v blízkosti svaru, která byla zahřáta, ale neroztavila se?", ["Předehřátá oblast", "Přechodová zóna", "Tepelně ovlivněná oblast (TOO)", "Tavná linie"], 2],
  [552, "Která metoda svařování patří mezi tavné?", ["Svařování výbuchem", "Svařování třením", "Svařování tlakem za studena", "Obloukové svařování"], 3],
  [553, "Jaký zdroj energie se používá u obloukového svařování?", ["Mechanická energie", "Stlačená pára", "Stlačený vzduch", "Elektrická energie"], 3],
  [554, "Jaký druh proudu se používá při obloukovém svařování?", ["Jen pulzní proud", "Pouze střídavý proud", "Pouze stejnosměrný proud", "Střídavý i stejnosměrný proud"], 3],
  [555, "Co chrání roztavený kov svaru před oxidací při obloukovém svařování obalenou elektrodou?", ["Voda", "Tavidlo (obal elektrody)", "Ocelový plášť", "Tlak plynu"], 1],
  [556, "Jak se nazývá ztuhlá vrstva strusky na povrchu svaru?", ["Okoviny", "Struskový obal", "Povlak", "Struska"], 3],
  [557, "Jaký plyn se nejčastěji používá při svařování MIG?", ["Kyslík", "Argon", "Vodík", "Dusík"], 1],
  [558, "Jaký je rozdíl mezi metodou MIG a MAG?", ["Druh tavidla", "Použitý ochranný plyn", "Druh základního materiálu", "Druh elektrody"], 1],
  [559, "Jak se označuje svařování wolframovou elektrodou v inertním plynu?", ["Plasma", "TIG", "MIG", "MAG"], 1],
  [560, "Která metoda svařování využívá vlastní kov jako přídavný materiál bez elektrody?", ["Svařování TIG", "Svařování tlakem", "Svařování plamenem", "Svařování MIG"], 1],
  [561, "Jaký druh plamene se používá pro svařování oceli?", ["Karburační", "Oxidační", "Neutrální", "Neutrální nebo mírně redukční"], 2],
  [562, "Jaká část elektrického oblouku má nejvyšší teplotu?", ["Oblast katody", "Plášť oblouku", "Oblast anody", "Střed oblouku"], 3],
  [563, "Jaká je teplota svařovacího oblouku?", ["500 °C", "až 6000 °C", "1500 °C", "3000 °C"], 1],
  [564, "Který druh elektrod se používá pro svařování nerezových ocelí?", ["Nízkouhlíkové elektrody", "Legované elektrody", "Nelegované elektrody", "Litinové elektrody"], 1],
  [565, "Co je kořen svaru?", ["Okraj svaru", "Horní část housenky", "Nejnižší část svarového spoje", "Začátek svaru"], 2],
  [566, "Která metoda patří mezi svařování tlakem?", ["TIG", "Svařování třením", "Plamenem", "MAG"], 1],
  [567, "Jak se označuje svařovací poloha „pod hlavou“?", ["PA", "PB", "PC", "PE"], 3],
  [568, "Jaký je hlavní důvod předehřívání při svařování?", ["Zrychlit svařování", "Zvýšit tvrdost svaru", "Omezit vznik trhlin", "Ušetřit energii"], 2],
  [569, "Jaké jsou nejčastější vady svarů?", ["Otřepy a výstupky", "Nesouosost a koroze", "Póry, trhliny, vměstky", "Vroubky a jamky"], 2],
  [570, "Která metoda svařování je vhodná pro hliník?", ["Plamenem", "MAG v CO2", "TIG", "Obalenou elektrodou"], 2],
  [571, "Jak se nazývá rychlost, kterou se svarová housenka posouvá při svařování?", ["Přísuv elektrody", "Rychlost svařování", "Posuv hořáku", "Posuv drátu"], 1],
  [572, "Co se používá při svařování laserem jako zdroj energie?", ["Elektronový paprsek", "Laserový paprsek", "Plamen", "Oblouk"], 1],
  [573, "Jaký je hlavní rozdíl mezi pájením a svařováním?", ["Druh tavidla", "Druh přídavného materiálu", "Druh ochranného plynu", "Při pájení se základní materiál netaví"], 3],
  [574, "Jaký je účel kořenové vrstvy svaru?", ["Zpevnit povrch", "Usnadnit čištění", "Zvýšit estetiku svaru", "Zajistit celistvost spoje v celé tloušťce"], 3],
  [575, "Jak se nazývá zařízení, které stabilizuje oblouk a reguluje proud při svařování?", ["Generátor plynu", "Hořák", "Svařovací zdroj", "Redukční ventil"], 2],
  [576, "Jaký je účel normalizačního žíhání svarových spojů?", ["Zvýšit tvrdost povrchu", "Snížit elektrický odpor", "Zlepšit odolnost proti korozi", "Zjemnit zrno a zlepšit mechanické vlastnosti"], 3],
  [577, "Jaký vliv má žíhání na tepelně ovlivněnou oblast (TOO)?", ["Zvětšuje její tvrdost", "Způsobuje praskání", "Zvyšuje vnitřní pnutí", "Zjemňuje strukturu"], 3],
  [578, "Které tepelné zpracování se používá k odstranění tvrdých a křehkých martenzitických struktur ve svaru?", ["Kalení", "Povrchové kalení", "Popouštění", "Nitridace"], 2],
  [579, "Jak se nazývá postup, kdy se svařený celek pomalu ohřívá a ochlazuje, aby se snížilo vnitřní pnutí?", ["Žíhání pnutí", "Kalení", "Cementace", "Normalizace"], 0],
  [580, "Proč se někdy předehřívá materiál před svařováním?", ["Kvůli rychlejšímu odpaření strusky", "Kvůli zvýšení tvrdosti", "Aby se omezil vznik trhlin", "Kvůli zlepšení povrchového vzhledu"], 2],
  [581, "Jak se označuje tepelné zpracování, při němž se po svařování součást ohřeje nad kritickou teplotu a pak se ochladí na vzduchu?", ["Žíhání", "Popouštění", "Normalizace", "Kalící proces"], 2],
  [582, "Co se stane s vnitřním pnutím svaru po vhodném tepelném zpracování?", ["Způsobí křehnutí", "Sníží se", "Zůstane beze změny", "Zvýší se"], 1],
  [583, "Jak se nazývá proces, který kombinuje účinek žíhání a popouštění za účelem dosažení rovnovážné struktury?", ["Nitridace", "Stabilizační žíhání", "Kalení", "Cementace"], 1],
  [584, "K čemu slouží závit v technické praxi?", ["Přenos momentu klínem", "Spojování součástí šroubovým spojem", "Zajištění pružnosti spoje", "Spojování hřídelí"], 1],
  [585, "Jaký je základní profil metrického závitu?", ["Lichoběžníkový", "Rovnoramenný trojúhelník 60°", "Trapezový", "Obdélníkový"], 1],
  [586, "Který závit se používá pro šrouby běžného spojovacího materiálu?", ["Metrický", "Násuvný", "Trapezový", "Whitworthův"], 0],
  [587, "Který úhel vrcholového profilu má metrický závit?", ["60°", "55°", "45°", "30°"], 0],
  [588, "Jak se značí metrický závit?", ["M", "TR", "T", "W"], 0],
  [589, "Jaký profil má trapézový závit?", ["Trojúhelníkový", "Čtvercový", "Lichoběžníkový", "Kruhový"], 2],
  [590, "Kde se nejčastěji používají trapézové závity?", ["V ozubených kolech", "V běžných spojích", "U matic kol", "U pohybových šroubů"], 3],
  [591, "Jak se vyrábí závit závitníkem?", ["Válcováním", "Odvalováním", "Řezáním", "Lisováním"], 2],
  [592, "Kolik dílů tvoří běžná sada ručních závitníků?", ["3", "1", "4", "2"], 0],
  [593, "Co určuje stoupání závitu?", ["Tuhost spoje", "Hloubku", "Úhel hrotu", "Vzdálenost sousedních závitů v ose šroubu"], 3],
  [594, "Jaké stoupání má běžný metrický závit?", ["Speciální", "Hrubé", "Podle normy (hrubé nebo jemné)", "Jemné"], 2],
  [595, "Jaký je základní nástroj pro řezání závitů ručně?", ["Pilník", "Závitník a závitnice", "Račnový klíč", "Fréza"], 1],
  [596, "Jaký závit se používá pro vedení pohybu?", ["Metrický", "Whitworthův", "Kruhový", "Trapézový"], 3],
  [597, "Jaký je úhel profilu u Whitworthova závitu?", ["30°", "55°", "45°", "60°"], 1],
  [598, "Který způsob výroby závitů je beztřískový?", ["Válcování", "Frézování", "Řezání", "Soustružení"], 0],
  [599, "Jaká je výhoda válcovaných závitů?", ["Snadnější opracování", "Nižší přesnost", "Vyšší pevnost a únavová odolnost", "Vyšší drsnost"], 2],
  [600, "Jak se značí levý závit?", ["Levý", "R", "L", "LH"], 3],
  [601, "Jak se vyrábí závit na soustruhu?", ["Vrtákem", "Závitovým nožem", "Výstružníkem", "Válcováním"], 1],
  [602, "Jaký závit se používá u vodovodních trubek?", ["Kruhový", "Metrický", "Trubkový (Whitworthův)", "Trapézový"], 2],
  [603, "Co je vícechodý závit?", ["Více než jeden profil", "Dvojitá hlava šroubu", "Závit s více než jedním chodem", "Závit bez konce"], 2],
  [604, "Jak se určuje stoupání vícechodého závitu?", ["Roztečí závitu násobenou počtem chodů", "Šířkou závitu", "Úhlem hrotu", "Hloubkou závitu"], 0],
  [605, "Co je hlavním účelem vrtání?", ["Frézování drážek", "Tvorba válcových otvorů", "Soustružení", "Broušení"], 1],
  [606, "Jaký je základní nástroj pro vrtání?", ["Soustružnický nůž", "Fréza", "Vrták", "Výstružník"], 2],
  [607, "Jaký je nejpoužívanější druh vrtáku?", ["Kuželový", "Trubkový", "Stupňovitý", "Šroubovitý"], 3],
  [608, "Jaká je funkce šroubovice vrtáku?", ["Zpevnění vrtáku", "Odvod třísek", "Zlepšení přesnosti", "Zvýšení tuhosti"], 1],
  [609, "Jaký úhel hrotu má běžný šroubovitý vrták pro ocel?", ["100°", "60°", "118°", "90°"], 2],
  [610, "Jak se nazývá stroj určený k vrtání?", ["Hoblovka", "Soustruh", "Frézka", "Vrtačka"], 3],
  [611, "Jaký druh vrtačky se používá pro přesné vrtání malých otvorů?", ["Ruční", "Radiální", "Stolní", "Stojanová"], 2],
  [612, "Jaký druh vrtačky se používá pro těžké kusy?", ["Radiální", "Ruční", "Stolní", "Sloupová"], 0],
  [613, "K čemu slouží vyvrtávání?", ["K řezání závitů", "K hrubování", "K přesnému zvětšení otvorů", "K výrobě závitů"], 2],
  [614, "Jaký nástroj se používá při vyvrtávání?", ["Vyvrtávací tyč", "Soustružnický nůž", "Pilník", "Vrták"], 0],
  [615, "Co je výstružník?", ["Nástroj na dokončování otvorů", "Nástroj na frézování", "Nástroj na broušení", "Nástroj na soustružení"], 0],
  [616, "Co určuje posuv při vrtání?", ["Otáčky vřetena", "Posuv na otáčku", "Druh chladiva", "Průměr dílce"], 1],
  [617, "Jaké otáčky se volí pro větší průměr vrtáku?", ["Vyšší", "Střední", "Nižší", "Nemění se"], 2],
  [618, "Jak se nazývá část vrtáku, která vede vrták v otvoru?", ["Drážka", "Tělo", "Hrot", "Vodicí část"], 3],
  [619, "Co je zahlubování?", ["Zvětšování průměru", "Frézování drážek", "Rozšíření otvoru u ústí", "Tvorba slepých děr"], 2],
  [620, "K čemu se používá kuželový vrták?", ["Na závity", "Na hluboké díry", "Na tvrdokovy", "Na plech"], 3],
  [621, "Jaký je účel středicího vrtáku?", ["Na soustružení", "Na závity", "Na zahlubování", "Na vytvoření důlku pro přesné vrtání"], 3],
  [622, "Jaký otvor vytvoří šroubovitý vrták?", ["Oválný", "Trojúhelníkový", "Válcový", "Kuželový"], 2],
  [623, "Jaký vrták se používá pro hluboké otvory?", ["Kuželový", "Korunkový", "Stupňovitý", "Dělový"], 3],
  [624, "Jaký je účel zahlubovacího vrtáku?", ["Na plechy", "Na hluboké otvory", "Na kuželové kolíky", "Na zapuštění hlavy šroubu"], 3],
  [625, "Jak se nazývá proces zvětšování přesnosti otvoru?", ["Soustružení", "Vrtání", "Výstružování", "Frézování"], 2],
  [626, "Jaká vrtačka umožňuje pohyb vřetene po rameni?", ["Radiální", "Ruční", "Sloupová", "Stojanová"], 0],
  [627, "Kde je upnut vrták u sloupové vrtačky?", ["Do čelisti soustruhu", "Do sklíčidla", "Do vřetene vrtačky", "Do děličky"], 2],
  [628, "Co je hlavní výhodou vyvrtávání oproti vrtání?", ["Vyšší přesnost a kvalita otvoru", "Jednoduchost", "Rychlost", "Nižší cena"], 0],
  [629, "Jaká je hlavní výhoda tváření za studena?", ["Větší nároky na ohřev", "Vyšší spotřeba energie", "Vyšší přesnost a kvalita povrchu", "Menší přesnost"], 2],
  [630, "Při jaké teplotě probíhá tváření za studena?", ["900 °C", "Nad 1000 °C", "Pod teplotou rekrystalizace", "600–800 °C"], 2],
  [631, "Jaký je vliv tváření za studena na pevnost materiálu?", ["Zvyšuje pevnost (deformační zpevnění)", "Nemá vliv", "Snižuje tvrdost", "Snižuje pevnost"], 0],
  [632, "Jaká je nevýhoda tváření za studena?", ["Menší přesnost", "Vysoká tvorba okují", "Nutnost vysokých teplot", "Vyšší tvářecí síly a opotřebení nástrojů"], 3],
  [633, "Která metoda patří mezi tváření za studena?", ["Lisování plechů", "Kování na bucharech", "Válcování za tepla", "Volné kování"], 0],
  [634, "Jaký proces se používá při výrobě plechových nádob?", ["Hloubkové tažení", "Protlačování", "Válcování", "Kování"], 0],
  [635, "Jaký je důsledek deformačního zpevnění?", ["Snížení tvrdosti", "Snížení pevnosti", "Zlepšení tažnosti", "Zvýšení pevnosti a tvrdosti"], 3],
  [636, "Jak lze odstranit účinky deformačního zpevnění?", ["Válcováním", "Kalením", "Rekrystalizačním žíháním", "Lisováním"], 2],
  [637, "Jaký stroj se používá pro lisování plechů?", ["Lis", "Soustruh", "Vrtačka", "Buchar"], 0],
  [638, "Jaký proces se používá pro zmenšení průměru drátu?", ["Válcování", "Lisování", "Kování", "Tažení drátu"], 3],
  [639, "Co je charakteristické pro tváření za studena?", ["Snížení přesnosti", "Zhoršení povrchu", "Vznik okují", "Hladký povrch a vysoká přesnost"], 3],
  [640, "Jaký vliv má tváření za studena na strukturu kovu?", ["Nemění mikrostrukturu", "Zjemňuje zrno", "Zvětšuje zrno", "Zpevňuje materiál"], 3],
  [641, "Který proces patří mezi beztřískové dělení?", ["Broušení", "Soustružení", "Stříhání plechu", "Frézování"], 2],
  [642, "Jaký proces se používá při výrobě šroubů za studena?", ["Frézování", "Soustružení", "Závitové válcování", "Válcování za tepla"], 2],
  [643, "Jaký je účel mazání při tažení drátu?", ["Snížení tření a opotřebení", "Zvýšení tažnosti", "Snížení tvrdosti drátu", "Zpevnění povrchu"], 0],
  [644, "Která metoda se používá při výrobě složitých výlisků z plechu?", ["Frézování", "Tlakové lisování", "Soustružení", "Kování"], 1],
  [645, "Jak se nazývá proces zmenšování tloušťky plechu mezi válci?", ["Protlačování", "Válcování za studena", "Stříhání", "Lisování"], 1],
  [646, "Jaký je důvod provádění více tahů při tažení drátu?", ["Zmenšení tření", "Postupné snižování průměru bez porušení drátu", "Zlepšení povrchu", "Zvýšení teploty"], 1],
  [647, "Který z následujících výrobků je typický pro tváření za studena?", ["Hrubé plechy", "Kancelářské sponky", "Výkovky", "Nosníky"], 1],
  [648, "Co je hlavním problémem tváření za studena?", ["Snadné přetvoření", "Potřeba velkých tvářecích sil", "Nízká pevnost výrobků", "Vznik okují"], 1],
  [649, "Jaká je hlavní výhoda tváření za tepla?", ["Možnost tváření složitých tvarů", "Možnost použití levnějších strojů", "Nižší rozměrová přesnost", "Menší tvrdost výrobku"], 0],
  [650, "Při jaké teplotě se ocel obvykle tváří za tepla?", ["200–400 °C", "Nad teplotou rekrystalizace (obvykle nad 1000 °C)", "900–1000 °C", "600–800 °C"], 1],
  [651, "Jaký vliv má tváření za tepla na strukturu kovu?", ["Nemá vliv na mikrostrukturu", "Zvětšuje zrno", "Zjemňuje zrno a odstraňuje vnitřní pnutí", "Zvyšuje vnitřní pnutí"], 2],
  [652, "Jaká je nevýhoda tváření za tepla?", ["Vyšší rozměrová přesnost", "Tvorba okují a menší přesnost", "Nižší spotřeba energie", "Zlepšení povrchu"], 1],
  [653, "Která metoda patří mezi tváření za tepla?", ["Kování na bucharech", "Lisování za studena", "Hloubkové tažení", "Tažení drátu"], 0],
  [654, "Jak se nazývá proces postupného zmenšování průřezu kovu mezi rotujícími válci?", ["Lisování", "Kování", "Válcování", "Protlačování"], 2],
  [655, "Jaký je hlavní účel ohřevu před tvářením za tepla?", ["Zvýšení tvárnosti materiálu", "Zvýšení tvrdosti", "Odstranění povrchových vad", "Snížení tvářecí síly"], 0],
  [656, "Jaké zařízení se používá pro volné kování za tepla?", ["Buchar", "Excentrický lis", "Hydraulický lis", "Šroubový lis"], 0],
  [657, "Jak se nazývá výrobní metoda, kdy je polotovar vtlačován do dutiny zápustky?", ["Válcování", "Tažení", "Volné kování", "Zápustkové kování"], 3],
  [658, "Jaké výrobky se typicky vyrábějí válcováním za tepla?", ["Tyče, plechy a nosníky", "Plechy tenké pod 1 mm", "Dráty", "Výkovky složitých tvarů"], 0],
  [659, "Jaký vliv má rychlé ochlazení kovu po tváření za tepla?", ["Zvětšuje zrno", "Nemá žádný vliv", "Zlepšuje obrobitelnost", "Může způsobit zakalení a pnutí"], 3],
  [660, "Jak se nazývá proces, kdy je kov protlačován otvorem matrice?", ["Válcování", "Protlačování", "Lisování", "Tažení"], 1],
  [661, "Který z následujících strojů se používá při zápustkovém kování?", ["Soustruh", "Kovadlina a výheň", "Lis nebo buchar", "Vrtačka"], 2],
  [662, "Jaký je hlavní přínos tváření za tepla na mechanické vlastnosti kovu?", ["Zlepšuje kujnost a tvárnost", "Zhoršuje plasticitu", "Zvyšuje tvrdost", "Snižuje houževnatost"], 0],
  [663, "Co vzniká na povrchu oceli při tváření za tepla?", ["Mazací film", "Okuj", "Zrcadlový povrch", "Tvrdá vrstva"], 1],
  [664, "K čemu slouží ohřev indukčními cívkami při tváření za tepla?", ["Rychle a rovnoměrně ohřívá materiál", "Způsobuje deformace", "Způsobuje kalení", "Zvyšuje pevnost"], 0],
  [665, "Jaký druh kovu je nejčastěji tvářen za tepla?", ["Hliník", "Mosaz", "Ocel", "Měď"], 2],
  [666, "Jaký je rozdíl mezi volným a zápustkovým kováním?", ["Použití maziva", "Použití zápustky pro určení tvaru", "Použití různých kovů", "Způsob ohřevu"], 1],
  [667, "Jaký je účel předkování (předkovů) při zápustkovém kování?", ["Snížení spotřeby energie", "Odstranění okují", "Příprava tvaru pro konečné kování", "Chlazení materiálu"], 2],
  [668, "Jaký druh zápustky se používá pro složité tvary?", ["Uzavřená zápustka", "Otevřená zápustka", "Lisovací forma", "Válcová matrice"], 0],
  [669, "Jaké tváření je energeticky méně náročné?", ["Obě stejně", "Závisí na stroji", "Za tepla", "Za studena"], 3],
  [670, "Jaký je typický problém při válcování za tepla?", ["Vznik okují a nerovností povrchu", "Nedostatečná plasticita", "Nedostatečné mazání", "Nedostatečné zpevnění"], 0],
  [671, "Jak se nazývá proces spojování dvou kovových polotovarů za tepla tlakem?", ["Nýtování", "Svařování obloukem", "Kovářské svařování", "Lisování"], 2],
  [672, "Jaký vliv má vyšší tvářecí teplota na odpor proti tváření?", ["Kolísá", "Odpor klesá", "Nemění se", "Odpor stoupá"], 1],
  [673, "Jaký je účel normalizačního žíhání po tváření za tepla?", ["Zhoršení obrobitelnosti", "Zvýšení tvrdosti", "Odstranění povrchových vad", "Uvolnění pnutí a zjemnění zrna"], 3],
  [674, "Mezi mechanické vlastnosti materiálů nepatří", ["tvárnost", "hodnota spořeenované nárazové práce", "tvrdost", "pevnost v tahu"], 1],
  [675, "U materiálů, které mají nevýraznou mez kluzu Re (MPa) se zavádí pojem, který ji nahrazuje, vyber správnou odpověď", ["smluvní mez kluzu Rm", "předpokládaná mez kluzu Rm", "smluvní mez kluzu Rp0,2", "dohodnutá mez kluzu Rp0,2"], 2],
  [676, "Na obrázku jsou dva pevnostní diagramy . Pro prodloužení ε=0,2% se používá značka pro smluvní mez kluzu. Vyber z uvedených 4 možností správnou", ["ReH", "Rp0,2", "Rp0,5", "ReL"], 1],
  [677, "Na obrázcích jsou 4 diagramy, zapiš písmeno správného diagramu", ["c)", "a)", "d)", "b)"], 3],
  [678, "Určete, které vztahy popisující výsledky zkoušky tahem jsou správné", ["A= ε · 100 (%) Rm = Fmax/So (MPa)", "A = ε (%) Rm = ε/A (%)", "A= ε / 100 (%) Rm = Fmin/So (MPa)", "A= ε (-) Rm = Fmax/Su (N)"], 0],
  [679, "Určete, které vztahy popisující výsledky zkoušky tahem jsou správné", ["b)", "c)", "a)", "d)"], 2],
  [680, "Tvrdost je schopnost materiálu odolávat vniknutí cizích předmětů do povrchu. Na obrázku je jeden ze způsobů určení tvrdosti. Urči, o kterou tvrdost a značku tvrdosti se jedná", ["zkouška tvrdosti dle Rockwella, HRC", "zkouška tvrdosti dle Vickerse, HV", "zkouška tvrdosti dle Brinella HBW", "zkouška tvrdosti dle Rockwella, HRC"], 0],
  [681, "Tvrdost je schopnost materiálu odolávat vniknutí cizích předmětů do povrchu. Na obrázku je jeden ze způsobů určení tvrdosti. Urči, pro jaké materiály se používá a značku tvrdosti", ["používá se pro materiály tvrdé, měří se hloubka vtisku, značí se HRC", "používá se pro materiály tvrdé, měří se hloubka vtisku , značí se HRB", "používá se pro materiály měkké, měří se průměr otisku, značí se HBS nebo HBW", "používá se pro materiály tvrdé, měří se velikost úhlopříčky otisku, značí se HV"], 0],
  [682, "Tvrdost je schopnost materiálu odolávat vniknutí cizích předmětů do povrchu, pokud budu zkoušet měkčí materiály a indentor bude kulička z tvrdokovu (slinutého karbidu), potom název tvrdosti bude mít značku :", ["HBW", "HBS", "HV", "HRA"], 0],
  [683, "Zkouška tvrdosti odrazem je často používaná jako tvz. provozní zkouška. Urči název metody určení tvrdosti a značku tvrdosti", ["určení tvrdosti dle Lagrange, HL", "určení tvrdosti dle Rockwella, HRC", "určení tvrdosti dle Leeba, HL", "určení tvrdosti dle Brinella, HBS"], 2],
  [684, "Při zkoušce rázem v ohybu jsou rozměry zkuševního tělíska s vrubem \"U\"", ["průřez 10 mm × 10 mm, délka 200mm, vrub U uprostřed obou protilehlých delších stran, šířka vrubu 8mm", "průřez 20 mm × 20 mm, délka 55 mm, U-vrub v 1/3 délky delší strany zkušebního tělíska šířka - vrubu 2 mm", "průřez 10 mm × 10 mm délka 55 mm, V- vrub s úhlem 45o , vrub uprostřed delší strany", "průřez 10 mm × 10 mm, délka 55 mm, U- vrub uprostřed delší strany, šířka vrubu 2 mm"], 3],
  [685, "Na obrázku je technologická zkouška, urči její správný název", ["zkouška drátů střídavým ohybem", "zkouška plechů hloubením dle Eirichsena", "zkouška kujnosti", "zkouška plechů a pásů střídavým ohybem"], 3],
  [686, "Na obrázku je technologická zkouška, urči její správný název", ["zkouška hloubením dle Erichsena", "zkouška pěchováním", "zkouška hloubením dle Brinella", "zkouška kujnosti za tepla"], 0],
  [687, "Etalonový materiál pro zkoušku obrobitelnosti má ČSN a EN značku :", ["dle ČSN EN :X30 Cr13, dle ČSN: 117023", "dle ČSN EN : E295, dle ČSN: 11500", "dle ČSN EN :C45, dle ČSN:12050", "dle ČSN EN : 17MnCr5, dle ČSN: 114220"], 2],
  [688, "Na obrázku je technologická zkouška: urči správnou odpověď", ["ERICHSENOVA zkouška obrobitelnosti", "JOMINIHO zkouška kalitelnosti", "JOMINIHO zkouška obrobitelnosti", "ERICHSENOVA zkouška kalitelnost"], 1],
  [689, "Na obrázku je NDT zkouška: urči správnou odpověď", ["UT: zkouška ultrazvukem", "MT: zkouška magnetická", "PT: zkouška penetrační", "RT: zkouška prozařováním"], 0],
  [690, "Zkouška PT=penetrační zkouška, urči správnou odpověď", ["penetrační kapalina = identifikační kapalina má barvu červenou nebo fialovou, detekční kapalina po uschnutí má barvu bílou", "penetrační kapalina = identifikační kapalina má barvu bílou, detekční kapalina po uschnutí má červenou nebo fialovou barvu", "používá se pouze detekční kapalina, která má bílou barvu", "používá identifikační se kapalina s fluorescenčním efektem, součást musí být zmagmetovaná , detekce se provádí pod UV(ultrafialovou) lampou"], 0],
  [691, "Zkouška MT = magnatická zkouška se používá pro:", ["nemagnetické materiály", "magnetické materiály, zejména oceli", "všechny kovy", "všechny materiály"], 1],
  [692, "RT zkouška princip zkoušky vada vytvořená dutinou - urči správnou odpověď", ["zkoušená součást pohlcuje RTG či jiné měkké záření které jí prochází , a tím dojde v místě vady = dutiny k silnějšímu ozáření fotografického filmu a vada se projeví tmavší než materiál", "zkoušená součást násobí RTG či jiné záření které jí prochází , a tím dojde v místě vady = dutiny ke slabšímu ozáření fotografického filmu a vada se projeví světlejším odstínem než materiál", "zkoušená součást pohlcuje RTG či jiné záření které jí prochází, a tím dojde v místě vady = dutiny k slabšímu ozáření fotografického filmu a vada se projeví světlejší než materiál", "zkoušená součást pohlcuje RTG či jiné(tvrdé) záření které jí prochází , a tím dojde v místě vady = dutiny k silnějšímu ozáření fotografického filmu a vada se projeví tmavší než materiál"], 2],
  [693, "Která metoda NDT je nejvhodnější pro detekci povrchových trhlin v nemagnetických materiálech?", ["magnetická metoda (MT)", "penetrační metoda PT", "vizuální zkouška VT", "zkouška ultrazvukem UT"], 1]
];
